### ISSUE TITLE
Timings Errors

### ISSUE THREAD

**Issue by joeylgutierrez** [jdalrymple/gitbeaker#1045]
**Description**
When trying to use the api to approve a merge request.  I constantly get an error like:
`{"name":"HTTPError","timings":{"start":1595954372745,"socket":1595954372745,"lookup":1595954372746,"connect":1595954372746,"secureConnect":1595954372751,"upload":1595954372745,"response":1595954372854,"end":1595954372855,"phases":{"wait":0,"dns":1,"tcp":0,"tls":5,"request":null,"firstByte":109,"download":1,"total":110}}}
`
My goal here is to do an auto release of many projects at once so I use the api to create a merge request that can be merged when pipeline succeeds. It does sometimes work for a project or two but most of the time i get this error.

**Steps to reproduce**
I'm looping multiple projects and making 3 requests and waiting for their responses before calling the next.  MergeRequests.create, MergeRequests.approve, and finally MergeRequests.accept with merge_when_pipeline_succeeds: true.

I'm expecting the following to happen under the covers:
`POST /projects/:id/merge_requests` 
`POST /projects/:id/merge_requests/:merge_request_iid/approve` 
`PUT /projects/:id/merge_requests/:merge_request_iid/merge with merge_when_pipeline_succeeds: true`

**Expected behaviour**
I should receive a successful promise and the merge request should be marked to merge when the build succeeds.

**Actual behaviour**
I receive a rejected promise with the error
`{"name":"HTTPError","timings":{"start":1595954372745,"socket":1595954372745,"lookup":1595954372746,"connect":1595954372746,"secureConnect":1595954372751,"upload":1595954372745,"response":1595954372854,"end":1595954372855,"phases":{"wait":0,"dns":1,"tcp":0,"tls":5,"request":null,"firstByte":109,"download":1,"total":110}}}
`

**Possible fixes**
I'm spoke with gitlab about the issue and they suggested it is probably something with my library causing the issue.  I'm going to look through the source code for possible issues but i have so suggestions at the moment

**Comment by jdalrymple** [comment]
Do you see similar behaviour just doing a raw request to the gitlab api without the library?

**Comment by joeylgutierrez** [comment]
When i do it locally one at a time it's fine but with the script it's making many more calls.  I've backed it off to take time in between but i think i'll need to use wireshark or something to see what errors i'm actually getting
