### ISSUE TITLE
HTTPError: 404 not found for almost every request

### ISSUE THREAD

**Issue by alannaidon** [jdalrymple/gitbeaker#1070]
Hello. Tried to find anything under `/src` but I didn't find anything that could help, so I'm creating this issue.  

I'm trying to use the attributes/methods/properties shown in documentation (ProjectsBundle and GroupsBundle), but everytime I try something different than `Projects.all() / Groups.all()` I receive a `HTTPError: Response code 404 (Not Found).`  

I need to retrieve metrics like:  

- Projects from a specific Group;
- Time spent on a specific sprint/milestone;  
- Time spent on a specific/or all tasks/job;  
- Time spent per user on a milestone  

```
const { Gitlab, ProjectsBundle, UsersBundle, GroupsBundle } = require('@gitbeaker/node')

const Groups = new GroupsBundle({
  host: 'https://example.com',
  token: 'XXXXXX'
})


const Projects = new ProjectsBundle({
  host: 'https://example.com',
  token: 'XXXX'
})

const projects = services.Project.all().then((project) => {
  console.log(project) // WORKS
}).catch((error) => {
  console.log(error)
})
```    

Also couldn't get the `Milestones` from a group. Returns `undefined` but there are open milestones right now.   
Trying something like [THIS](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/group_milestones.md)

```
(async () => {
  const vraw = await Groups.Groups.show(3).ProjectMilestones // undefined - although there is a project with id 3
  console.log(vraw)
})()
```  

am I doing something wrong?

**Comment by jdalrymple** [comment]
- Projects from a specific Group: use the GroupProjects API

- Time spent on a specific sprint/milestone; I dont think this exposed in the API :/ but if it was you can use the GroupMilestones/ProjectMilestones API
- Time spent on a specific/or all tasks/job: Same as above
- Time spent per user on a milestone: same as above
