### ISSUE TITLE
Why minify packages for node?

### ISSUE THREAD

**Issue by apla** [jdalrymple/gitbeaker#1114]
**Description**
I'm trying to debug custom requester and I see such useless backtraces:

```
    at handler (requester-project/js/utils/gitlabRequester.js:139:22)
    at Object.requester.<computed> [as get] (requester-project/js/utils/gitlabRequester.js:96:10)
    at Object.<anonymous> (requester-project/node_modules/@gitbeaker/core/dist/index.js:1)
    at requester-project/node_modules/@gitbeaker/core/dist/index.js:1
    at Object.next (requester-project/node_modules/@gitbeaker/core/dist/index.js:1)
    at requester-project/node_modules/@gitbeaker/core/dist/index.js:1
    at new Promise (<anonymous>)
    at u (requester-project/node_modules/@gitbeaker/core/dist/index.js:1)
    at Object.e [as get] (requester-project/node_modules/@gitbeaker/core/dist/index.js:1)
    at t.current (requester-project/node_modules/@gitbeaker/core/dist/index.js:1)
```

I can install your project, million of its dependencies and try to dive deeper into the error, but actually I should see the real backtrace and find out where is error comes from without any additional steps.

**Proposal**

Modules should not be minified and should represent original sources.

**Comment by jdalrymple** [comment]
The code is minified to reduce its footprint when being used in other packages. To aid in debugging, you could always just use the source and npm link it locally.

**Comment by Dianoga** [comment]
I don't think most other projects go full minimized source. If footprint size is a concern there are fairly easy options for shipping projects to minimize things to their own specifications. Needing to pull the source and link isn't a great option.

**Comment by jdalrymple** [comment]
Thats fair, what would you two suggest?

**Comment by Dianoga** [comment]
I did some searching this morning to see how other projects handle it and the answer seems to be "it's complicated". There's a good discussion over here but no real resolution (https://github.com/googleapis/google-cloud-node/issues/2867). 

I think the thing that would have helped me the most is just not minimizing the source. That would let me do basic things like use a debugger and step through calls to see what's happening.

**Comment by jdalrymple** [comment]
Hmm, what if i just minified the browser version? I feel like the browser files are the ones most affected by package size.

**Comment by jdalrymple** [comment]
Or i could include the source maps

**Comment by Dianoga** [comment]
If you're going to minify a version doing that just for the browser makes sense. But in a world where many projects make use of tools like webpack to assemble their final bundle you may not need to worry about minification. The only place where I think you would want that is if you were distributing the library via a CDN for simple script tag inclusion but I don't see that mentioned in the docs anywhere.

**Comment by jdalrymple** [comment]
Ive removed the minification in the latest builds for everything besides the browser release :rocket:
