### ISSUE TITLE
Add MergeRequests.rebase 

### ISSUE THREAD

**Issue by Haniyya** [jdalrymple/gitbeaker#1120]
**Description**
There is an api to rebase a merge-request against its target branch:

https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request

Which as far as I can tell is not yet supported by Gitbeaker. It would be very helpful to have. 

**Proposal**
Add the `rebase` method to the service defined in `packages/gitbeaker-core/src/services/MergeRequests.ts` and probably some more procedure like tests etc? I'm not very familiar with this project sorry 😅 

﻿﻿

**Comment by jdalrymple** [comment]
haha, yup you have the right idea. Ill try to get around to it soon, still need to sort out #1112 before anything :cry:

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`24.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/24.1.0) :rocket:

**Comment by Haniyya** [comment]
@jdalrymple thank you ❤️
