### ISSUE TITLE
Search commits betweens dates

### ISSUE THREAD

**Issue by antrichard** [jdalrymple/gitbeaker#1130]
**Description**
I would like to know if it's possible to add two new parameters when looking for pushed (or any other action) commits of a specific user. Those two parameters would be limitations dates like "before" and "after"

**Proposal**

This would appear on this kind of call for example :

```
api.Users.events(user_id, {
		action: 'pushed',
		after: 'YYYY-MM-DD',
		before: 'YYYY-MM-DD'
	}).then((events) => {

	});
```

**Comment by jdalrymple** [comment]
Seems useful, does the gitlab API support this natively? Or something similar?

**Comment by jdalrymple** [comment]
Also sorta similar to #1079

**Comment by jdalrymple** [comment]
This is already supported using the [since/until](https://docs.gitlab.com/ee/api/commits.html#list-repository-commits) query parameters
