### ISSUE TITLE
typo at readme.md should be showExpanded instead of showExtended 

### ISSUE THREAD

**Issue by ccckblaze** [jdalrymple/gitbeaker#1134]
typo at readme.md should be showExpanded instead of showExtended 

<!-- *(Brief description of your issue here)*

none

**Steps to reproduce**

none

**Expected behaviour**
none

**Actual behaviour**
none

**Possible fixes**
recorrect the readme.md please, it wasted me 10 mins to locate the issues by look into the source code

**Comment by jdalrymple** [comment]
Good catch, oops!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`24.0.1`](https://github.com/jdalrymple/gitbeaker/releases/tag/24.0.1) :rocket:
