### ISSUE TITLE
404 not found when getting ALL group variables under linux with pagination

### ISSUE THREAD

**Issue by holyspidoo** [jdalrymple/gitbeaker#1167]
Getting paginated groups variables works fine under windows. 

Under linux, it gives a 404 not found. 

The curl command under linux works fine with the same token.

_Node.js >12_

``return await this.api.GroupVariables.all(groupId)``

**Comment by jdalrymple** [comment]
Hmm, i tested this on the latest arch linux build without any issue. Can you share any more information about the request? Or create a sample group so i can recreate the problem.
