### ISSUE TITLE
Support for one entry.

### ISSUE THREAD

**Issue by brizer** [jdalrymple/gitbeaker#1217]
**Description**
Support for one entry, so we can import this package in both node and browser environment.

**Proposal**
Use `dynamic import` to import  different package  between node  and  browser . So we can  use :

``` js 
import gitlab  form 'gitbreaker' 
```
in both node  and  brower .

Please think  about  it, or If there is any problem with this design, please point it out, thank you

**Comment by jdalrymple** [comment]
Each build has different content, thus supporting a singular entry doesn't make sense. For example the browser version is building using a browser friendly request library, where as the node version is built using a node specific request library. This follows for many libraries used.

**Comment by brizer** [comment]
Why not refer to `axios· and solve this problem through the adapter？ For example:

``` js
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

**Comment by jdalrymple** [comment]
I dont recall the exact reason we chose not to use axios, but there was a reason back in the discussion. I can try and dig it up and get back to you

**Comment by jdalrymple** [comment]
In the same vein, couldnt you dynamically import gitbeaker/node or gitbeaker/browser?

**Comment by brizer** [comment]
> In the same vein, couldnt you dynamically import gitbeaker/node or gitbeaker/browser?

I just do it now. I don’t want you to use axios, but you can refer to it and solve your cross-terminal problems through the adapter.

**Comment by jdalrymple** [comment]
Ah i understand. Though this would add some dependencies to the build, i could create something for it as a wrapper. Ill add this as a FR, and get to it once some more bugs are squashed.

**Comment by jdalrymple** [comment]
Yay, weve reached the future, now with the introduction of the native fetch support this seems way more attractive. Less deps, smaller codebase, less packages. Its still experimental, but it might be good to go by next LTS.
