### ISSUE TITLE
Support the Freeze Period API

### ISSUE THREAD

**Issue by nlochschmidt** [jdalrymple/gitbeaker#1227]
As far as I can see the API managing [freeze periods](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/freeze_periods.md) is missing.

Is this something you plan to add near-term or would you be interested in a PR for this?

**Comment by jdalrymple** [comment]
Wasnt on my radar at the moment, but id be more than happy to accept a PR!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`24.3.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/24.3.0) :rocket:
