### ISSUE TITLE
Property 'id' does not exist on type 'Record<string, unknown> | Record<string, unknown>[]'.

### ISSUE THREAD

**Issue by avevlad** [jdalrymple/gitbeaker#1306]
**Description**

Version:     "@gitbeaker/node": "^25.2.0"

**Error:**
```bash
Property 'id' does not exist on type 'Record<string, unknown> | Record<string, unknown>[]'.
  Property 'id' does not exist on type 'Record<string, unknown>[]'.ts(2339)
```

What am I doing wrong?

![image](https://user-images.githubusercontent.com/2889662/98290939-6a6ff680-1fbb-11eb-81fb-f3a2199d8927.png)

```ts
import { Gitlab } from "@gitbeaker/node"; // All Resources

let GITLAB_PROJECT_ID = process.env.GITLAB_PROJECT_ID;

if (!GITLAB_PROJECT_ID) {
  throw new Error("set env GITLAB_PROJECT_ID");
}

const api = new Gitlab({
  host: "https://git.stage.com",
  token: process.env.GITLAB_ACCESS_TOKEN,
});

(async () => {
  let project = await api.Projects.show(GITLAB_PROJECT_ID);
  console.log("project", project);
  if (!project) {
    throw Error("Project not found");
  }
  let ppl = await api.Pipelines.all(project.id);
  // console.log(ppl.length);
})();

```

**Comment by Enough7** [comment]
@avevlad Do you know any advice how to work around this?

**Comment by avevlad** [comment]
@Enough7 `// @ts-ignore` :(

**Comment by Enough7** [comment]
I also found this [here](https://43081j.com/2019/02/typescript-avoid-using-any)
![image](https://user-images.githubusercontent.com/30051680/111183637-69298880-85b0-11eb-9644-6aa8322485fd.png)

**Comment by jdalrymple** [comment]
> @avevlad Do you know any advice how to work around this?

The canary build from the #1104  PR should fix this, but this is still very much a beta build. For the time being @avevlad suggestion should work.
