### ISSUE TITLE
Type CreateMergeRequestOptions has labels in type string

### ISSUE THREAD

**Issue by wamry** [jdalrymple/gitbeaker#1354]
**Description**

CreateMergeRequestOptions has labels as string instead of string[]

```ts
export interface CreateMergeRequestOptions {
    //...
    labels?: string;
    //...
}
```
Same goes for Types `UpdateMergeRequestOptions` and `AllMergeRequestsOptions`

**Expected behaviour**
to have type `string | Array<string>`

**Actual behaviour**
it has type `string`

**Possible fixes**
make it of type `string | Array<string>`

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`25.5.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/25.5.0) :rocket:
