### ISSUE TITLE
Support for getting GPG signature of a commit?

### ISSUE THREAD

**Issue by martin-helmich** [jdalrymple/gitbeaker#1381]
**Description**
I noticed that the [`Commits` API](https://github.com/jdalrymple/gitbeaker/blob/ad9aebb611eeb21e6340759f44f50ac09ca36086/packages/gitbeaker-core/src/services/Commits.ts#L57) does not seem to support the [`GET /projects/:id/repository/commits/:sha/signature` call](https://docs.gitlab.com/13.6/ee/api/commits.html#get-gpg-signature-of-a-commit).

**Proposal**
Add a method `signature(projectId: string | number, sha: string, options?: BaseRequestOptions)` to said class. I'm willing to provide a PR if desired.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`28.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/28.0.0) :rocket:
