### ISSUE TITLE
Increase type definition

### ISSUE THREAD

**Issue by RoXuS** [jdalrymple/gitbeaker#1398]
**Description**
Why we have to use `as X` to get the right type 
````ts
    const user = (await gitlabApi.Users.current()) as UserSchema;
    // OR
    const projects = (await gitlabApi.Projects.search(name)) as Array<ProjectSchema>;
````
To get the good type?

**Proposal**
For this case current should be something like this:
````ts
    current(options?: Sudo): Promise<UserSchema>;
    // OR
    search(projectName: string): Promise<ProjectSchema>;
````

**Comment by jdalrymple** [comment]
Because i havent had the time to go through and update all the types haha working on it though #1104 #492
