### ISSUE TITLE
Add Project remote mirrors API 

### ISSUE THREAD

**Issue by AUtech-dev** [jdalrymple/gitbeaker#1449]
**Description**
Project remote mirrors API is missing.

GitLab documentation: https://docs.gitlab.com/ee/api/remote_mirrors.html

**Proposal**
Add as an API like e. g. [PushRules](https://github.com/jdalrymple/gitbeaker/blob/master/packages/gitbeaker-core/src/services/PushRules.ts)

**Comment by jdalrymple** [comment]
Next up is the #1104 , but feel free to put together a PR if you need this sooner!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
