### ISSUE TITLE
ProjectSchema doesn't return all properties  

### ISSUE THREAD

**Issue by eranelbaz** [jdalrymple/gitbeaker#1493]
**Description**
By GitLab docs for [Projects.all](https://docs.gitlab.com/ee/api/projects.html#list-all-projects) they return a lot of extra properties that aren't include in `ProjectSchema` object such as `default_branch`, 
and if i want to get it i need to create something like that:
```typescript
type ProjectSchemaCamelizedExtended = ProjectSchemaCamelized & { defaultBranch: string };
const projects = (await this.gitlabClient.Projects.all({ membership: true })) as ProjectSchemaCamelizedExtended[];
``` 
and only than I can use
```typescript
projects.defaultBranch
```
because it isn't part of `ProjectSchemaDefault` or `ProjectSchemaCamelized`

**Possible solutions**
add the missing properties to the object

**Comment by jdalrymple** [comment]
Working on it right now in #1104
