### ISSUE TITLE
How to use sudo and admin rights?

### ISSUE THREAD

**Issue by AlexBHarley** [jdalrymple/gitbeaker#1500]
I've created an oAuth application and I'm trying to do the edit user operation on behalf of the user.

Got `api`, `sudo` and `read_user` scopes but I receive a combination of `403 Forbidden - Must be admin to use sudo` and `403 Forbidden` while trying to do this operation.

**Comment by jdalrymple** [comment]
Can you share you example code? Just so i have a better understanding of how youre calling it?

**Comment by AlexBHarley** [comment]
Trying to update a users bio, looks like this

```
  const user = new Users({
    sudo: '8091631',
    oauthToken: session.accessToken,
  });
  await user.edit(8091631, {
    bio: 'hello',
  });
```

**Comment by jdalrymple** [comment]
Hmm, the sudo is part of the function call, not the service instantiation. At least that's how it is currently. Perhaps making that change will fix the issue!
