### ISSUE TITLE
Missing types on returned objects

### ISSUE THREAD

**Issue by Roguyt** [jdalrymple/gitbeaker#1532]
**Description**

I'm seeing an increasing number of types being incorrect compared to the data returned by the API.
For example some endpoints returns a `Record<string, unknown>[]` which is fine since I just need to look at Gitlab API, whereas some others return fully typed objects but they are missing data, such as ` ProjectSchema`

**Steps to reproduce**

1. Users.projects(id) returns a fully usable `Record<string, unknown>[]`
2. Groups.projects(id) returns a incomplete ` ProjectSchema|]`

**Expected behaviour**
Either have a non fully typed data that can be used with the Gitlab API Documentation, or fixing the types.

**Actual behaviour**
Typescript is complaining of missing types
![image](https://user-images.githubusercontent.com/8149856/107160878-3f6db800-6999-11eb-9191-fee0ec756ea5.png)
While the actual data does have the informations
![image](https://user-images.githubusercontent.com/8149856/107160909-6c21cf80-6999-11eb-836f-29d4623a9783.png)

**Possible fixes**
I'm not entirely sure how to fix it permanently and reliably. Either I could make a PR to replace the type by a standard Record<>[] and loose the type safe feature of TS but it would work. Either updating the type, while also testing other endpoints using it are not affected by the updated types.

**Comment by jdalrymple** [comment]
Tackling this in a few other PR's /  Issues. Mainly #1104.  This PR sets the default to Record<string, unknown> and for places where the types have been added (such as ProjectSchema), it will utilize those which will extend off of Record<string, unknown>.

Those don't FULLY cover everything, the next step will be going through and updating the types of these schemas since they've definitely changed since they were initially added.

**Comment by Roguyt** [comment]
Hey @jdalrymple,

Thanks for the fast answer, I had seen that draft and kinda expected this was the solution.
This would indeed be a good compromise, given how complicated it would be to fully type the whole Gitlab API.

**Comment by jdalrymple** [comment]
Right? and they switch it up so often :cry:  haha. If you have any thoughts on that draft btw, feel free to share!
