### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Jerry4013** [jdalrymple/gitbeaker#1566]
Hi,
I am trying to fetch the gitlab merge request list using this library. In my Typescript class, I define an async function called getMergeRequestList(): Promise<Record<string, MergeRequestResponse>[]>. Inside this function, I use
 `let data = await api.MergeRequests.all({
      projectId,
      state: state,
      perPage: pageSize,
      page,
      showExpanded: true,
    });
  return data as Record<string, MergeRequestResponse>[];`
However, I can't assign the type of the data. I tried a lot about the Promise <Record<>> but it doesn't work. I don't know how to use this "data" because its type is Record<string, unknow>.

Could you give a little more example about how I can get the response of this api?

Thank you very much!

**Comment by jdalrymple** [comment]
Yup! This will be sorta fixed in #1104! Though what you have written there is a bit...confusing. Wouldnt you be returning:

```
data as MergeRequestResponse
```

Also how is MergeRequestResponse defined?

**Comment by Jerry4013** [comment]
> Yup! This will be sorta fixed in #1104! Though what you have written there is a bit...confusing. Wouldnt you be returning:
> 
> ```
> data as MergeRequestResponse
> ```
> 
> Also how is MergeRequestResponse defined?

I defined MergeRequestResponse as the same object as in the Gitlab api docs. I did not understand Record in Typescript. After some research today, I think Record in the response represents one single "merge request object", right? Sometimes it is an array because this "list merge request" api will return a list of merge request object. 

I hope there are some clarification for the return type. For example, each Record is one of the object as following.

[
  {
    "id": 1,
    "iid": 1,
    "project_id": 3,
    "title": "test1",
    "description": "fixed login page css paddings",
    "state": "merged",
    "merged_by": {
      "id": 87854,
      "name": "Douwe Maan",
      "username": "DouweM",
      "state": "active",
      "avatar_url": "https://gitlab.example.com/uploads/-/system/user/avatar/87854/avatar.png",
      "web_url": "https://gitlab.com/DouweM"
    },
...

I wish we can have some examples about how to use the returned data. For example, 
`let data = await api.MergeRequests.all()`
How can I use the data here? What is the type of this data? If it is a Record<string, any>[], then how to loop this array and get the "merge request objects"? 

Thank you!

**Comment by jdalrymple** [comment]
It returns an javascript object that is of type Record<string, unknown>[]. This issue is a duplicate though (will be fixed in the MR mentioned above), so i will close for now
