### ISSUE TITLE
Basic Example not Working

### ISSUE THREAD

**Issue by ProfessorManhattan** [jdalrymple/gitbeaker#1576]
**Description**

Example not working

**Steps to reproduce**

Install the @gitbeaker/node library and run the following code on https://repl.it

```
import { Gitlab } from '@gitbeaker/node';

const api = new Gitlab({
      token: 'xxx',
    });
api.Projects.all().then((projects) => {
  console.log('hey');
    console.log(projects);
  });
```

**Expected behaviour**

It should list all the projects associated with my user

**Actual behaviour**

Script hangs with no response. It never gets to the `console.log('hey')` line.

**Possible fixes**

The GitLab API status page shows everything is green. I have no idea what the issue is.

**Comment by jdalrymple** [comment]
Hey! Just tested this on runkit and got a response. Im guessing its hanging because there are so many results?  This returns ALL the projects that your user can see. Not sure your projects.

**Comment by monkeydaichan** [comment]
Same issue.

```
const { Gitlab } = require('@gitbeaker/node');

const api = new Gitlab({
  host: 'https://gitlab.com',
  token: 'XXX',
});
api.Projects.all().then((projects) => {
  console.log(projects);
});
```

Script hangs with no response.
Following curl command works good, I think it's not problem about personal token.

```
curl "https://gitlab.com/api/v4/projects?private_token=XXX"
```

```
$ node -v
v12.0.0
```

**Comment by jdalrymple** [comment]
Might be related to #1880, ill follow up when i know more
