### ISSUE TITLE
Question: How To Add a Runner For a Project (ie - POST /projects/:id/runners)

### ISSUE THREAD

**Issue by vguaglione** [jdalrymple/gitbeaker#1591]
**QUESTION/HELP**

I need to add a runner to a project, as I would using this gitlab API syntax:

curl --request POST --header "PRIVATE-TOKEN: ***" "https://gitlab.mydomain.com/api/v4/projects/9/runners" --form "runner_id=12"

I am using gitbeaker to retrieve information from my instance with no problem, but now I need to send/update information for my instance.  My sample code is listed below.  When I run this code, I see that gitbeaker is issuing a PUT request, not a POST request, and am receiving an HTTP 400 - bad request.  What would I need to change/fix to have gitbeaker send the POST request for this API call?

const { Gitlab } = require('@gitbeaker/node');
const { ProjectsBundle } = require('@gitbeaker/node');

const api = new ProjectsBundle({
    host: 'https://gitlab.mydomain.com',
    token: gitlab_token,
});

obj = await api.Projects.edit(project_id, "runners", {runner_id:12});

**Comment by jdalrymple** [comment]
Runners exists as its own service for convenience. To update or [enable](https://docs.gitlab.com/ee/api/runners.html#enable-a-runner-in-project) a runner:

```js
const { Gitlab } = require('@gitbeaker/node');

const api = new Gitlab({
   host: 'https://gitlab.mydomain.com',
   token: gitlab_token,
});

let obj = await api.Runners.enable(project_id,  12);
```

**Comment by jdalrymple** [comment]
Currently no, though the code itself its pretty well structured. Though its not ideal, quickly checking the gitbeaker-core/src/services directory will give a quick outline of whats available where. There is a ton of  documentation work that needs to be done, unfortunately, its still on the back burner until certain functionality is fixed.

**Comment by vguaglione** [comment]
No problem.  I appreciate the help!
