### ISSUE TITLE
Edit a note to resolve a discussion thread

### ISSUE THREAD

**Issue by MathieuPuech** [jdalrymple/gitbeaker#1620]
**Description**

[GitLab API specification](https://docs.gitlab.com/ee/api/discussions.html#modify-an-existing-merge-request-thread-note):

* `body`: The content of the note/reply (exactly one of body or resolved must be set
* `resolved`: Resolve/unresolve the note (exactly one of body or resolved must be set

When I try with `MergeRequestDiscussions.editNote` with content `null` and options: `{ resolved: true}`, I get a http 400 error from GitLab:
> body, resolved are mutually exclusive

**Proposal**

Add a `MergeRequestDiscussions.resolveNote` with the `resolved` attribute or change the `editNote` to remove the `body` when it is set to `null`

**Comment by jdalrymple** [comment]
Ill see if i can update the editNote function, since the content parameter doesnt seem to be required.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`29.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/29.2.0) :rocket:
