### ISSUE TITLE
Add support for the Package Registry API

### ISSUE THREAD

**Issue by Enough7** [jdalrymple/gitbeaker#1623]
Hey,
at first great work. It is a little hard to get into gitbeaker, so I wonder is it possible to download a package from GitLab's package registry? Another question I got in mind is, are there other authentication-flows except a personal accesstoken suppoted by gitbeaker?

**Comment by jdalrymple** [comment]
Hey! Thank you!!

1. Do you mean the packages api? These are the functions [available](https://github.com/jdalrymple/gitbeaker/blob/master/packages/gitbeaker-core/src/services/Packages.ts). These can be accessed like:

```
import { Packages } from '@gitbeaker/node'

...
const service = new Packages({ token: 'your personal access token' OR another authentication option here })

const allPackages = await service.all(projectId)
```
2. In the Get Started]( section of the ReadMe, it mentions a couple other authentication options. Check the Available instantiating options list, currently there is jobToken, oauthToken, and token (personal access token)

**Comment by Enough7** [comment]
> Do you mean the packages api?
- Yes. By downloading I mean actually downloading a Package File, as described [here](https://docs.gitlab.com/ee/user/packages/generic_packages/#download-package-file)

> Check the Available instantiating options list.
- Nice I was looking for OAuth but I have to get the OAuth-Token by myself by implementing [this Auth flow](https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-flow), am I right?
- By the way whats the meaning of the asterisk in the Optional column?
![image](https://user-images.githubusercontent.com/30051680/111670510-341f6f00-8818-11eb-8a13-9ae92e270319.png)

**Comment by jdalrymple** [comment]
> @jdalrymple
> 
> > Do you mean the packages api?
> 
>     * Yes. By downloading I mean actually downloading a Package File, as described [here](https://docs.gitlab.com/ee/user/packages/generic_packages/#download-package-file)
> 
> 
> > Check the Available instantiating options list.
> 
>     * Nice I was looking for OAuth but I have to get the OAuth-Token by myself by implementing [this Auth flow](https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-flow), am I right?
> 
>     * By the way whats the meaning of the asterisk in the Optional column?
>       ![image](https://user-images.githubusercontent.com/30051680/111670510-341f6f00-8818-11eb-8a13-9ae92e270319.png)

Good point haha, its meant to point to additional information but i must of missed adding it in the description. Ill create an issue to fix it! Thank you!! For those options, its meant to point to the fact that ONE is required as mentioned in their descriptions.

I didnt even see that additional API information. We dont currently support that unfortunately, though PR's are welcome! It seems gitlab is coming out with new API's on the regular haha its hard to keep up

**Comment by Enough7** [comment]
Thank you ❤️

**Comment by jdalrymple** [comment]
Im going to reopen this one @Enough7 so i dont forget to add the support.

**Comment by Enough7** [comment]
[This](https://www.npmjs.com/package/openid-client) might help you @jdalrymple

**Comment by jdalrymple** [comment]
@Enough7 Give the canary build a look when you get a min. Just to make sure i didnt bugger up the API calls for the registry

**Comment by Enough7** [comment]
@jdalrymple I am sorry but I most likely won't due to my bachelor thesis. In behalf of the community, thanks for your work though.

**Comment by jdalrymple** [comment]
No worries! Glad I can help anyways
