### ISSUE TITLE
Problem fetching image files 

### ISSUE THREAD

**Issue by Pryx** [jdalrymple/gitbeaker#1624]
Hi, I've encountered a problem when trying to download image files from a repository using the `nodejs` version of gitbeaker and the `RepositoryFiles.showRaw` function. I've been able to track the problem down to this switch statement 

https://github.com/jdalrymple/gitbeaker/blob/4b1ea4afc400c7913559f95624d63cd9c32a99ed/packages/gitbeaker-node/src/GotRequester.ts#L54-L66

Basically the result (e.g. `image/png`) falls into the default code block and is converted to string. But to me, the switch statement seems wrong - it is treating any non-matching mime as a string, which would cause problems with many other filetypes. Treating only the text mime type and its subtypes as string and defaulting to buffer for everything else seems like a much better idea. I know I can just write my own requester function (and I'll probably do that in the meantime), but I feel like this should be fixed upstream. I will be glad to make a PR :slightly_smiling_face:

**Comment by jdalrymple** [comment]
This is a much better idea! If you whip this up in a PR, I can get it merged ASAP (If you dont mind, add the same change to the KyRequester file as well :pray:  plz)

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`28.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/28.2.0) :rocket:

**Comment by Pryx** [comment]
Thank you for such a fast merge and release :+1: Closing this as the issue was resolved :slightly_smiling_face:
