### ISSUE TITLE
Issue Unsubscribe Returns 404

### ISSUE THREAD

**Issue by divido** [jdalrymple/gitbeaker#1725]
**Description**

When using `gitlab.Issues.unsubscribe(project.id, issue.iid)`, I get a 404 response from the server.
Also occurs when running `gitbeaker issues unsubscribe` with the same project ID and Issue IID.

Reviewing the gitbeaker code, it looks like it is attempting a DELETE operation for this. The [GitLab API Documentation](https://docs.gitlab.com/ee/api/issues.html#unsubscribe-from-an-issue) shows that this is supposed to be a POST operation. You can check that out by running a `curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/5/issues/93/unsubscribe"` (example from the GitLab documentation; which works in my private instance).

**Steps to reproduce**

CLI is easiest to reproduce -- fill in the url / token of a server you operate, choose any project and issue and try to subscribe / unsubscribe to it. Subscribing works, but the unsubscribe will return a 404. Fill in your url / token / project / issue details on the curl command to see that the GitLab server is working fine.

**Expected behaviour**

GitLab unsubscribes the user from that issue.

**Actual behaviour**

GitLab returns 404

**Possible fixes**

Change `del` to `post`.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`28.4.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/28.4.0) :rocket:
