### ISSUE TITLE
Remove token-requirement on APIs that work without authentication

### ISSUE THREAD

**Issue by dotWee** [jdalrymple/gitbeaker#173]
Some of the APIs GitLab provides are usable without a user generated token, like the `/users/:user_id/projects` path ([reference](https://docs.gitlab.com/ee/api/projects.html#list-user-projects)):

> Get a list of visible projects owned by the given user. When accessed without authentication, only public projects are returned.

It would be awesome to use those without getting an _token is mandatory_ error!

**Comment by jdalrymple** [comment]
For the time being, I could remove the requirement for a token and anything that does require a token would just error out :s not the most elegant solution but until we add the proposed mapping, it would be a waste of time to implement throughout all the services.

**Comment by dotWee** [comment]
Please correct me if I'm wrong, but wouldn't _error'ing out_ result in just like any request with an invalid token? aka. the implemented `StatusCodeError: 401 Unauthorized`
Anyway, an implementation after #104 seems reasonable.

**Comment by jdalrymple** [comment]
Yup! Which is still pretty clear of a message. Ill make a PR this weekend.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.1.0) :rocket:
