### ISSUE TITLE
Add support for Jobs List pipeline bridges

### ISSUE THREAD

**Issue by vboulaye** [jdalrymple/gitbeaker#1763]
Hi,
Thanks for this library!

**Description**

The gitlab api to get the list of ["pipeline bridges"](https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-bridges) (ie child pipelines) is missing

**Proposal**

add the api call to the Jobs service `showPipelineBridges` (similar to  `showPipelineJobs`)

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`29.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/29.1.0) :rocket:
