### ISSUE TITLE
showPipelineBridges declaration missing in @gitbeaker/core dist/types/services/Jobs.d.ts

### ISSUE THREAD

**Issue by vboulaye** [jdalrymple/gitbeaker#1779]
**Description**
Hi,
this is a follow up regarding #1766 
First thanks for the quick merge!

However it seems that the typescript types have not been updated in the released package.
Inside @gitbeaker/core `dist/types/services/Jobs.d.ts` I can not find the `showPipelineBridges` declaration

**Steps to reproduce**

npm install @gitbeaker/node

**Expected behaviour**

showPipelineBridges should be declared in the Jobs.d.ts file

**Actual behaviour**

showPipelineBridges is not in the Jobs.d.ts file
(but it is present in the compiled index.js)

**Possible fixes**

I tried npm run build and the file is generated properly: maybe something went wrong int the release process ?

**Comment by jdalrymple** [comment]
Weird! Ill double check!

**Comment by jdalrymple** [comment]
Yea it looks like the types were not released...and i dont know why. The same commands i run locally are run in the CI build. It doesnt even look like the feature was added in the distribution [file](https://unpkg.com/@gitbeaker/core@29.1.0/dist/index.es.js) :angry:

**Comment by jdalrymple** [comment]
Should be there now @vboulaye

**Comment by vboulaye** [comment]
I works now, thanks!
