### ISSUE TITLE
Poll - Does anyone actually use the bundles

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/gitbeaker#1792]
Wondering if this is unneeded logic in the library. I have a feeling they are not used haha, but figured i should ask the community just in case. I'm referring to the ProjectsBundle, UsersBundle or the GroupsBundle

**Comment by zanella** [comment]
👋, I'm not a heavy TS user, that being said, I gave up on using your lib cause the type definitions seemed a bit overboard on it's flexibility, enough to make me and Intellij unable to understand at a glance what the returned types were supposed to be...

So, I guess if your question is if you should make the types definition on a more statically manner: yes 😬

**Comment by jdalrymple** [comment]
> wave, I'm not a heavy TS user, that being said, I gave up on using your lib cause the type definitions seemed a bit overboard on it's flexibility, enough to make me and Intellij unable to understand at a glance what the returned types were supposed to be...
> 
> So, I guess if your question is if you should make the types definition on a more statically manner: yes grimacing

Thanks for the feedback! But to clarify do you mean yes-> you would use those bundles, or yes-> they are unneeded?
