### ISSUE TITLE
Trying to upload a file using Projects.upload in Node - resulting file is a corrupt tarball

### ISSUE THREAD

**Issue by KennySmash** [jdalrymple/gitbeaker#1843]
**Description**

Hey Guys,  
I am trying to upload a file ( an xls in this case ) and the result from using the below code, 
everything is good till I get the return which is a several times larger than what I uploaded ( 111616 input to 156kb in my filesystem) and its coming out as a tar.gz file which isn't working. I have my file data in as fsTest and its good as a Buffer array with the file working correctly up to the point of upload

```
api.Projects.upload(10, fsTest , {filename: 'user group.xls'}).then((resp)=>{
   res.send({resp, fsTest})
})
```

I get this returned from the server:
```
{
  "alt": "1622584600163.tar.gz",
  "url": "/uploads/bc1f808ceaa5c88c10cd2b445dd9ad89/1622584600163.tar.gz",
  "full_path": "/kenny/ticket-tester/uploads/bc1f808ceaa5c88c10cd2b445dd9ad89/1622584600163.tar.gz",
  "markdown": "[1622584600163.tar.gz](/uploads/bc1f808ceaa5c88c10cd2b445dd9ad89/1622584600163.tar.gz)"
}
```
which upon downloading the file, it won't un-tar citing and unrecognised archive format

I am using the latest version of Gitbeaker and node v15.9.0 with its included fs module

**Steps to reproduce**

reading a file from `let fsTest = fs.readFileSync(attachmentPath)` and using the code above

**Expected behaviour**

a file of the correct file extension and open-enable in its native application

**Actual behaviour**

As described above

**Comment by jdalrymple** [comment]
I'll try and test this out in the next day and follow up!

**Comment by KennySmash** [comment]
Quick update, after some more digging I discovered the big part of my problem was defining the filename. after poking around I discovered that the filename needs to be nested inside a metadata obj. once I got that in and changed my readFileSync to export a raw buffer array. now the files upload properly.

All in all, I guess this one can be chalked up to documentation problems

**Comment by jdalrymple** [comment]
Sorry :(, glad you got it figured out though!
