### ISSUE TITLE
`GroupProjects` in `GroupBundle` doesn't exists! 

### ISSUE THREAD

**Issue by anwar3606** [jdalrymple/gitbeaker#1844]
**Description**
I'm using `@gitbeaker/browser` latest version `29.2.4`

Getting these errors when using GroupProjects in GroupBundle
`TypeError: Cannot read property 'all' of undefined`

Looks like `GroupProjects` doesn't exist anymore inside GroupBundle even though it's written in the readme doc! 

I checked in the source code, it doesn't exist!!! 

```js
declare const GroupsBundle: packages_gitbeaker_core_src_infrastructure.BundleType<{
    Groups: typeof Gitbeaker.Groups;
    GroupAccessRequests: typeof Gitbeaker.GroupAccessRequests;
    GroupBadges: typeof Gitbeaker.GroupBadges;
    GroupCustomAttributes: typeof Gitbeaker.GroupCustomAttributes;
    GroupIssueBoards: typeof Gitbeaker.GroupIssueBoards;
    GroupMembers: typeof Gitbeaker.GroupMembers;
    GroupMilestones: typeof Gitbeaker.GroupMilestones;
    GroupRunners: typeof Gitbeaker.GroupRunners;
    GroupVariables: typeof Gitbeaker.GroupVariables;
    GroupLabels: typeof Gitbeaker.GroupLabels;
    GroupDeployTokens: typeof Gitbeaker.GroupDeployTokens;
    Epics: typeof Gitbeaker.Epics;
    EpicIssues: typeof Gitbeaker.EpicIssues;
    EpicNotes: typeof Gitbeaker.EpicNotes;
    EpicDiscussions: typeof Gitbeaker.EpicDiscussions;
},.....
```
**Steps to reproduce**

```js
let get_group = (token) => {
    return new GroupsBundle({
        oauthToken: token.access_token,
        host: process.env.VUE_APP_GITLAB_HOST,
    });
}

export async function get_group_projects_list() {
    let token = await auth.getAccessToken();
    return get_group(token).GroupProjects.all(process.env.VUE_APP_GITLAB_GROUP_ID, {archived: false, simple: true})
}
```

Even when I'm trying to use `GroupsBundle.Groups.projects` functions it doesn't let pass additional query params like 
`{archived: false, simple: true})` this, when I could do this in version 25! If I try to pass these, it would go to an infinity loop.

I have forced to use version 29 cause of these to service `IssueAwardEmojis, IssueNoteAwardEmojis` where `IssueNoteAwardEmojis` didn't exists in 25 and `IssueAwardEmojis` wouldn't let me award the issue itself!!!

Any Idea how can get a list of projects in a group with some query like not archived?

**Comment by jdalrymple** [comment]
Hey @anwar3606 no stress haha, the remnant in the readme is my fault. Must if missed updating it. 

The group projects were removed in one of the recent [PRs](https://github.com/jdalrymple/gitbeaker/pull/1768#issue-641752463) because it was a duplicate endpoint. You can access group projects from the Groups resource:

```js
Groups.projects
```

**Comment by jdalrymple** [comment]
As you noticed, the GroupProjects resource was removed because it was a duplicate. This was done in one of the recent [PRs](https://github.com/jdalrymple/gitbeaker/pull/1768#issue-641752463). From what you describe it seems like a bug! You should be able to pass the same options. 

I'm not sure about the awards stuff, but I'll give it a look and follow up.

**Comment by anwar3606** [comment]
Just for curiosity 

https://github.com/jdalrymple/gitbeaker/blob/04d042fe0106888fa7681f9de64d65f6e7fa8f9f/packages/gitbeaker-core/src/services/Groups.ts#L93

will this be `BaseRequestOptions`?

shouldn't it be more like 
https://github.com/jdalrymple/gitbeaker/blob/04d042fe0106888fa7681f9de64d65f6e7fa8f9f/packages/gitbeaker-core/src/services/Groups.ts#L120

where I can pass any query parameter?

(Newbie in js here)

**Comment by jdalrymple** [comment]
It should be the first one since that allows for any option to be passed. The latter only supports the sudo query parameter.

**Comment by jdalrymple** [comment]
Seems to be another issue connected to this statement in the index.d.ts :

```
: packages_gitbeaker_core_src_infrastructure.BundleType
```

Ill look when i get a moment.

**Comment by jdalrymple** [comment]
Yea, this isnt going to be a small fix. The issue i mentioned above it really slowing down my test of the issue. My only suggestion for now is making due with an older release until I have the proper time to delve into this issue. Sorry for the delay :(

**Comment by jdalrymple** [comment]
While I did find problems in the build, none would result in the behaviour youre having. I was able to create it by modifying my test repos tsconfig file. To verify this is the issue:

```js
    let options =  {archived: false, simple: true}
    return get_group(token).GroupProjects.all(process.env.VUE_APP_GITLAB_GROUP_ID, options)
```

Does this work?

**Comment by jdalrymple** [comment]
Should be good now! Give it a look
