### ISSUE TITLE
How to upload project files?

### ISSUE THREAD

**Issue by Krenodeno** [jdalrymple/gitbeaker#1865]
**Description**

When uploading a file using gitbeaker/node (version 28.3.0), like a png image file, the url returned by the function is a tar.gz file.
Trying the same function using curl directly like in the [Gitlab API Docs](https://docs.gitlab.com/ee/api/projects.html#upload-a-file) return the correct file url, not a tarball url.

**Steps to reproduce**

upload a file using
```js
const { url } = Gitlab.projects.upload(PROJECT_ID, filePath);
```

`url` is a url pointing to a tarball file instead of a url pointing to the given file

**Expected behaviour**

returned url should end with the original file like in this curl command:
```bash
~ curl --request POST --header "PRIVATE-TOKEN: <MY-PRIVATE-TOKEN>" --form "file=@filePath.png" "https://our.git.org/api/v4/projects/PROJECT-ID/uploads"
{"alt":"filePath","url":"/uploads/83b4ce226dd07031c21f095d3d9026ee/filePath.png","full_path":"/GROUP/PROJECT/uploads/83b4ce226dd07031c21f095d3d9026ee/filePath.png","markdown":"![filePath](/uploads/83b4ce226dd07031c21f095d3d9026ee/filePath.png)"}
```

**Actual behaviour**

The url ends with a tar.gz file extension like so : `{ url: "/uploads/3f76dfcfe38bb6ed31bca5d7e4b6201a/1623155594192.tar.gz"}`

**Comment by jdalrymple** [comment]
Hey @Krenodeno,

Just to verify, the upload function takes in the content, not the filepath. This is to avoid having a dependency on the fs package which isnt available in the browser. 

```typescript
  upload(
     projectId: string | number,
     content: string,
     { metadata, ...options }: { metadata?: UploadMetadata } & BaseRequestOptions = {},
  )
```

If you also want to pass additional metadata, these are the options and their defaults.

```typescript
export interface UploadMetadata {
  filename?: string;
  contentType?: string;
}

export const defaultMetadata = {
  filename: `${Date.now().toString()}.tar.gz`,
  contentType: 'application/octet-stream',
};
```

**Comment by Krenodeno** [comment]
Thank you!

I understand my mistake now, we upgraded from the old Gitlab dependency, and I didn't see this difference in parameters.

That is totally my fault, thank you.
I'll try it asap !
