### ISSUE TITLE
ProjectBadges service has same exact implementation as GroupBadges

### ISSUE THREAD

**Issue by Jemaz** [jdalrymple/gitbeaker#1874]
Hi there, thank you all for the hard work you put into this library, really helped me out :smile: 

I'm a novice when it comes to contributing to open-source so with that warning out of the way...

https://github.com/jdalrymple/gitbeaker/blob/6c90d4a41e1b2b7b127427cd21d76430af402769/packages/core/src/services/ProjectBadges.ts#L47-L51

https://github.com/jdalrymple/gitbeaker/blob/6c90d4a41e1b2b7b127427cd21d76430af402769/packages/core/src/services/GroupBadges.ts#L47-L51

Two of these have the same super constructor arguments `groups`. I believe it should be `projects` for the ProjectBadges.ts service but haven't tried it out honestly. I thought I'd at least raise it and let you guys know at the very least.

Thanks :100:

**Comment by jdalrymple** [comment]
Oops! I think i fixed this somewhere but it hasnt been merged yet!

**Comment by jdalrymple** [comment]
Yup! this will be fixed soon!

**Comment by jdalrymple** [comment]
Fixed with #1818
