### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by sandercox** [jdalrymple/gitbeaker#1880]
**Description**

I'm trying to do a .all query to get all results but it seems to be just sending the request for the same page to the gitlab server and I'm waiting indefinately on my issues.

When I added a maxPages=3, I noticed that I do get 3 times my requested page size back, but also 3x the same issues from the first page.

**Steps to reproduce**
```ts
  const api = new Gitlab({token/host});
  const project = await api.Projects.show("projectpath");
  let issues = await api.Issues.all({ projectId: project.id, status: 'opened', perPage: 10});
```

**Expected behaviour**

Get all pages with the relevant information

**Actual behaviour**

Get the same page over and over again (when maxPages is set, if not it just waits till the end of time).

This is all with the latest. I had to revert to release 28.4.1 couldn't get any newer to work. Unfortunately now I don't have typescript type support anymore :-(

**Comment by jdalrymple** [comment]
I think i may know whats up! Ill give it a look and follow up!

**Comment by JiriTrecak** [comment]
Can confirm, 

```typescript
let rawProjects = await instance.Projects.all({ maxPages: 1})
```

works but

```typescript
let rawProjects = await instance.Projects.all()
```

hangs indefinitely, but doesn't throw (throws when running our internal tests as it timeouts ava). Max pages duplicate results. Thanks for looking into it or suggesting a workaround, I have tried few things but couldn't make it to work.

**Comment by jdalrymple** [comment]
Sorry for the delay! been a hectic week. Looking at this now.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`30.3.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/30.3.0) :rocket:

**Comment by jdalrymple** [comment]
Give it a look!

**Comment by sandercox** [comment]
Thanks works as expected again
