### ISSUE TITLE
Unnecessary console.log in RequestHelper

### ISSUE THREAD

**Issue by jakob-kruse** [jdalrymple/gitbeaker#1894]
I think this was not mentioned anywhere before. Why does this `console.log` exist?

This seems like a "debugging artifact" and if it is not, there should be a config option to disable that in my opinion.

https://github.com/jdalrymple/gitbeaker/blob/69582243718526b2f0c7963c74c13950f958d34a/packages/core/src/infrastructure/RequestHelper.ts#L101

It came with this recent pull request https://github.com/jdalrymple/gitbeaker/commit/f6ed4376c0214df4a38e1321044739a4be3dc19b

Have a nice day

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`30.4.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/30.4.0) :rocket:
