### ISSUE TITLE
"total" is missing in latest version pagination

### ISSUE THREAD

**Issue by kunyan** [jdalrymple/gitbeaker#1921]
**Description**
```
paginationInfo: { next: 2, current: 1, previous: null, perPage: 50 }
```

There are no `total` in the `paginationInfo` object

https://github.com/jdalrymple/gitbeaker/blob/cdaacd23641995456f2c3a76ab8d5685f31ddbca/packages/core/src/infrastructure/RequestHelper.ts#L46-L51

I had searched `x-total` in the repo, there are no codes about it    https://github.com/jdalrymple/gitbeaker/search?q=x-total&type=code

**Steps to reproduce**

**Expected behaviour**
```
paginationInfo: { total: 100, next: 2, current: 1, previous: null, perPage: 50 }
```

**Actual behaviour**
```
paginationInfo: { next: 2, current: 1, previous: null, perPage: 50 }
```

**Possible fixes**

**Comment by jdalrymple** [comment]
weird. I removed it #1898 here, but it looks like the docs have been updated again to include it... smh. Ill revert the PR and redeploy

**Comment by jdalrymple** [comment]
I'm definitely confused. What ever, ill fix it ASAP.

**Comment by jdalrymple** [comment]
Following up. So even though it does mention it in the docs, when i actually perform a request, i dont see those values in the headers...

**Comment by jdalrymple** [comment]
Here is the connected issue. https://gitlab.com/gitlab-org/gitlab/-/issues/264375 closing for now.

**Comment by kunyan** [comment]
@jdalrymple 

**Only** **Gitlab.com** will not have x-total and x-total-page
<img width="561" alt="Screen Shot 2021-07-12 at 1 09 34 PM" src="https://user-images.githubusercontent.com/752130/125234137-a6114c00-e312-11eb-9fb8-b55664f93e0d.png">

<img width="855" alt="Screen Shot 2021-07-12 at 1 11 49 PM" src="https://user-images.githubusercontent.com/752130/125234227-d658ea80-e312-11eb-82eb-348f15d210bc.png">

https://docs.gitlab.com/ee/user/gitlab_com/index.html#pagination-response-headers


So I think gitbeaker should keep those 2 fields in case of user connect to self-host gitlab.

**Comment by jdalrymple** [comment]
Ah cool, ill add it back then! Thanks for finding that missing piece!!
