### ISSUE TITLE
Error 404 on RepositoryFiles.showRaw missing ref

### ISSUE THREAD

**Issue by baudouindesvaux** [jdalrymple/gitbeaker#1990]
**Description**

I use `@gitbeaker/browser`
When using `RepositoryFiles.showRaw`, I receive a 404 error. The url is `/projects/:id/repository/files/:file_path/raw`, when I try this url in Postman, I have this message : `{"error": "ref is missing, ref is empty"}`, but if I add `?ref=branch`, that's works !

**Steps to reproduce**

Use `RepositoryFiles.showRaw` like : 
```javascript
import { Gitlab } from '@gitbeaker/browser';

const api = new Gitlab({
  host : 'url',
  token : 'token'
})

api.RepositoryFiles.showRaw(idProject,"file").then((data)=>{
  console.log(data)
})
```

**Expected behaviour**

See the file 

**Actual behaviour**

404 error `{"error": "ref is missing, ref is empty"}`

**Possible fixes**

Add ref parameter to showRaw method on [RepositoryFiles.ts](https://github.com/jdalrymple/gitbeaker/blob/4f2166210b7b6fbfaa766c05a15c2435a8bab293/packages/core/src/resources/RepositoryFiles.ts) file maybe like this : 
```javascript
showRaw(projectId: string | number, filePath: string, ref: string, options ?: BaseRequestOptions) {
  const [pId, path] = [projectId, filePath].map(encodeURIComponent);

  return RequestHelper.get()(
    this,
    `projects/${pId}/repository/files/${path}/raw`,
    {
      ref,
      ...options,
    }
  ) as unknown as Promise<Blob>;
}
```

**Comment by jdalrymple** [comment]
Ill give it  a look!

**Comment by jdalrymple** [comment]
hmm

this is weird, in the docs it still says its optional? https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository

**Comment by baudouindesvaux** [comment]
Yes, I see that...
It's optional for 14.X but my company's version of gitlab it's 13.10... And on 13.X it's required... [https://docs.gitlab.com/13.12/ee/api/repository_files.html#get-file-from-repository](https://docs.gitlab.com/13.12/ee/api/repository_files.html#get-file-from-repository)
I don't know when they have plan to upgrade GitLab...

**Comment by jdalrymple** [comment]
ah, hmm, Im really aiming to improve the version control for 14 going forward to avoid these kind of problems. Making it a required parameter would be a bit of a regression for now. I know its a pain, but the best move for you would probs just be passing the param to your logic like you did. I will add information for the supported gitlab version going forward though. I've been meaning to do this with #1592
