### ISSUE TITLE
RepositoryFiles.showRaw missed the 'ref' option

### ISSUE THREAD

**Issue by motorin** [jdalrymple/gitbeaker#2020]
**Description**
In previous version `RepositoryFiles.showRaw` had 'ref' option. 
For now, only `RepositoryFiles.show` has this option, but `showRaw` doesn't.

It's not clean, why? How can I use `showRaw` now for files in a specific branch?

**Possible fixes**

Return 'ref' option to `RepositoryFiles.showRaw` method.

I did PR with fix:
https://github.com/jdalrymple/gitbeaker/pull/2019

If it's not correct, please explain how can I use `showRaw` for specific branches.
Thank you!

**Comment by jdalrymple** [comment]
This is because its not [required](https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository) for the latest gitlab version. You can still pass ref, using the options argument:

```js
showRaw(123314213,  'myfilepath', { ref: 'your ref' })
```
