### ISSUE TITLE
Support passing token to specific requests

### ISSUE THREAD

**Issue by lianghx-319** [jdalrymple/gitbeaker#2026]
**Description**

In some cases, got a token dynamically. But we must create more and more instance for every token;

**Proposal**

Just like `Sudo`, as an option for each request.

**Comment by jdalrymple** [comment]
Reintializing the instance shouldn't be that big of an issue. Can you provide some usecases where this would be a problem that would be solved by passing a custom token to a method?

**Comment by jdalrymple** [comment]
Closing for now! Open to reopening with more information
