### ISSUE TITLE
Support Update of Code Owner on Protected Branches

### ISSUE THREAD

**Issue by hong823** [jdalrymple/gitbeaker#2072]
**Description**

Currently, there's no support update of code owner on protected branches API. See below:

```
PATCH /projects/:id/protected_branches/:name
```

Reference: https://docs.gitlab.com/ee/api/protected_branches.html#require-code-owner-approvals-for-a-single-branch

**Proposal**

Implement the missing API above in 

https://github.com/jdalrymple/gitbeaker/blob/d4b916bc247b1e6bbe537bdd44bd82308e35c74f/packages/core/src/resources/ProtectedBranches.ts#L25

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
