### ISSUE TITLE
ProjectExtendedSchema doesn't include the squash_option attribute

### ISSUE THREAD

**Issue by GMZwinge** [jdalrymple/gitbeaker#2083]
**Description**

The extended project schema does not include the `squash_option` attribute with possible values `never`, `always`, `default_on`, or `default_off`.

See GitLab API [Get Single Project](https://docs.gitlab.com/ee/api/projects.html#get-single-project).

**Steps to reproduce**

Call `Projects.show()` on a project.

**Expected behaviour**

The returned project data should include the `squash_option` attribute.

**Actual behaviour**

The returned project data does not include the `squash_option` attribute.

**Possible fixes**

Add `squash_option` as an optional attribute to `ProjectExtendedSchema`.

**Comment by jdalrymple** [comment]
Easy fix, simply adding this to the ProjectExtendedSchema would be a good first PR.

**Comment by GMZwinge** [comment]
It turns out that even though the attribute is documented in the GitLab API, it may not be fully usable. [Projects API show whether a project requires/prevents squashing](https://gitlab.com/gitlab-org/gitlab/-/issues/261458) was only closed 3 months ago and [Support squash commits option on Projects REST API](https://gitlab.com/gitlab-org/gitlab/-/issues/254942) to set the attribute is still opened with no plan to address it.

**Comment by GMZwinge** [comment]
@jdalrymple From https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66122, it looks like the option is now available in 14.1 and higher. I cannot test this because we are still at 14.0. Should we re-open and merge this for others?

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
