### ISSUE TITLE
Users.current() should return UserExtendedSchema

### ISSUE THREAD

**Issue by 10ko** [jdalrymple/gitbeaker#2084]
**Description**

I would expect the `Users.current()` function to return `UserExtendedSchema` as opposed to the current return type `UserSchema`. Is this expected? 

**Steps to reproduce**

Just trying to use the `Users.current()` function should show the issue.

**Expected behaviour**

I would expect the return type to be `Promise<UserExtendedSchema | undefined>`

**Actual behaviour**

`Users.current()` returns `Promise<UserSchema>`

**Possible fixes**

I am no expert of this codebase but it looks like it would be as easy as changing the type in [here](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Users.ts#L78).
I can make a PR if that's what's needed. 🌻

**Comment by jdalrymple** [comment]
This is gonna wait until i fix #1897

**Comment by 10ko** [comment]
Gotcha, thanks for taking a look!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
