### ISSUE TITLE
Errors thrown when using the package

### ISSUE THREAD

**Issue by andreasciamanna** [jdalrymple/gitbeaker#2099]
**Description**

I'm unable to use `@gitbeaker/node` as it seems to use deprecated packages.

I hope I'll manage to provide all the needed info.

**Steps to reproduce**

1. Use the latest Node LTS.
2. Create a new React App with the TypeScript template.
3. Install gitBeaker.
4. Run any API request to GitLab (in my case, I'm trying to use `Repositories.compare` .
5. Run the app `npm run start`.

**Expected behaviour**

Not get errors, I guess.

**Actual behaviour**

I get this:

```
./node_modules/http2-wrapper/source/index.js
Module not found: Can't resolve 'http2' in '/Users/andreasciamanna/WebstormProjects/embrazo/deploy-tools/node_modules/http2-wrapper/source'
```

My assumption is that I'm missing the `http2` package.
Even though is deprecated, I give it a try with `npm install http2`.
Starting the app again with `npm run start`, I get this:

```
./node_modules/http2/lib/protocol/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression
```

There might be a reason why `http2` is deprecated, after all.

**Possible fixes**

Do not use `http2`?

**Comment by jdalrymple** [comment]
weird ill give it a look!

**Comment by jdalrymple** [comment]
Which version of nodejs are you using?

**Comment by andreasciamanna** [comment]
v14.17.3

**Comment by jdalrymple** [comment]
Similar issue here: https://stackoverflow.com/questions/54054830/module-not-found-cant-resolve-http2-when-import-firebase-admin

**Comment by jdalrymple** [comment]
If youre using it for frontend code, use the browser release instead of the node one. it wont have a ref to http2

**Comment by andreasciamanna** [comment]
Yes, probably I was using the wrong library (though I'm pretty sure I always used the node one in other front-end apps).

Anyway, I had to push forward with the development and wrote my implementations for the APIs I needed to use.

Next time, I'll try to remember to use the right package.

Thanks!
