### ISSUE TITLE
Project/Group/Instance - Clusters Support

### ISSUE THREAD

**Issue by veenarm** [jdalrymple/gitbeaker#2105]
**Description**

I can't find any support for the Clusters API

**Proposal**

Add support for Clusters API 
-  https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/project_clusters.md
-  https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/group_clusters.md
-  https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/instance_clusters.md

**Comment by jdalrymple** [comment]
I wont be adding support since this has recently been deprecated :(
