### ISSUE TITLE
Add support for `include_merged_yaml` on Lint API

### ISSUE THREAD

**Issue by MartinHowarth** [jdalrymple/gitbeaker#2161]
**Description**

https://docs.gitlab.com/ee/api/lint.html#yaml-expansion (specifically the YAML expansion) is not supported in this package currently, as far as I can tell. This feature proposal adds support for it.

**Proposal**

It should be as simple as adding the option to pass `include_merged_yaml: boolean` to the existing code [here](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Lint.ts#L12) and parsing `merged_yaml` back out of the response.

I'm extremely new to TypeScript so I haven't just submitted a PR as I thought it would be more effort for you to coach me through fixing the PR up than to just add the feature yourself! Please shout if I've got that wrong and I'll look into making an MR.

**Comment by jdalrymple** [comment]
Hey! This would be a perfect small PR. All you have to change is the type parameter from Sudo, to BaseRequestOptions, and update the LintSchema to optionally include the merged_yaml (use a ?)
