### ISSUE TITLE
GroupAccessRequests.approve returns 404

### ISSUE THREAD

**Issue by GuillaumePavic** [jdalrymple/gitbeaker#2172]
**Description**

When using ```api.GroupAccessRequests.approve(resourceId, userId, {accessLevel: AccessLevel)``` I get a 404.
I'm sure to use the correct arguments as ```api.GroupAccessRequests.deny(resourceId, userId)``` works perfectly fine with the same arguments.

**Possible fixes**

When looking into 'core/src/Templates/ResourceAccessRequests.ts' it seems the HTTP method used is POST, whereas it should be PUT according to the GitLab documentation.

**Comment by jdalrymple** [comment]
Nice catch, small bug fix for this

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
