### ISSUE TITLE
How to create merqe request with Description

### ISSUE THREAD

**Issue by satrox28** [jdalrymple/gitbeaker#2196]
Hi,

Thanks for the node module. Can you able to provide us a sample code to create a Gitlab merge request with a description.

Have imported below classes.

import { Gitlab } from '@gitbeaker/node';
import { CommitAction } from '@gitbeaker/core/dist/types/services/Commits'; 
import { CreateMergeRequestOptions } from '@gitbeaker/core/dist/types/services/MergeRequests';

**Comment by jdalrymple** [comment]
```ts
import { MergeRequests } from '@gitbeaker/node';

const api = new MergeRequests({ token: 1232312 })

// Call within an async function 
const mr = await api.create(projectId, sourceBranch, targetBranch, title, { description: 'some description' })

```

**Comment by satrox28** [comment]
thanks it worked @jdalrymple
