### ISSUE TITLE
Issues.all(my_project_id) is not returning any issues

### ISSUE THREAD

**Issue by dlazzy** [jdalrymple/gitbeaker#2208]
**Description**

Hello, I'm trying to use the gitbeaker package but I'm facing an issue with the `Issues.all(my_project_id)` call. Since `Groups.all()` and `Groups.projects(my_group_id)` is working well I don't know with listing project issue is not working.

**Steps to reproduce**

I'm running gitbeaker with NodeJS. This will be a future API using Express.

Declaring my configuration :

```js
const { Gitlab } = require('@gitbeaker/node');

const apiGitlab = new Gitlab({
  host: config.gitlab.host,
  token: config.gitlab.token,
});

router.get('/suggest/gitlab-groups', (req, res) => {
  apiGitlab.Groups.all().then(groups => {
    return res.status(200).json({ success: true, data: groups });
  }, () => {
    return res.status(500).json({ success: false, message: 'Error happen when getting Gitlab groups' });
  });
});
// Works, it return me all groups available

router.get('/suggest/gitlab-issues/:project_id', (req, res) => {
  if (req.params.project_id) {
    apiGitlab.Issues.all(req.params.project_id).then(issues => {
      return res.status(200).json({ success: true, data: issues });
    }, () => {
      return res.status(500).json({ success: false, message: 'Error happen when getting Gitlab issues' });
    });
  } else {
    return res.status(500).json({ success: false, message: 'Missing parameter' });
  }
});
// Don't work, my API return 200 but with an empty array (in res.data)
```

**Expected behaviour**

Issues should be returned since I have 70+ issues on this project.

**Actual behaviour**

Return 200, so no error from Gitbeaker but also return an empty array (in res.data).

**Possible fixes**

I tried to use Gitbeaker in browser (simple html file) to get the call from Gitbeaker but I gave up since I don't know how to use it fast and easily in browser. Maybe I can get it when using it from NodeJS ?

Thanks for you help.

**Comment by jdalrymple** [comment]
The call for all issues is:

```
Issues.all({projectId: yourprojectid})
```

**Comment by dlazzy** [comment]
Oh my bad. Thank you very much it is working now, I didn't see through Gitbeaker docs and Gitlab API docs :)

Have a nice day!
