### ISSUE TITLE
gitbeaker breaks oclif

### ISSUE THREAD

**Issue by jshaw-cm** [jdalrymple/gitbeaker#2215]
**Description**

**Steps to reproduce**

1. Create new oclif project.
2. Import `@gitbeaker/node`
3. run `tsc -b`

**Expected behaviour**

Project Builds

**Actual behaviour**

![Screen Shot 2021-11-17 at 12 30 45 PM](https://user-images.githubusercontent.com/12800520/142261392-b11650cb-606e-48b9-92bd-22a6f1295460.png)

**Possible fixes**

This is the current tsconfig.json -- is there a setting here that could fix this?

![Screen Shot 2021-11-17 at 12 35 46 PM](https://user-images.githubusercontent.com/12800520/142261673-fe73f9d2-7f1f-4440-b384-44ad44e8b23f.png)

**Comment by jdalrymple** [comment]
Hmm, im not sure. Oclif seems to be failing when it encounters a Template type. I dont know if changing the target is going to fix that. Why would oclif change fail on the typing to begin with?

**Comment by jdalrymple** [comment]
what version of ts are you using?
