### ISSUE TITLE
Improve Tags endpoints ts signature

### ISSUE THREAD

**Issue by florentplomb** [jdalrymple/gitbeaker#2246]
Hello 

**Description**
The current tags method signature seems not up to date with the endpoint params.
[  create(projectId: string | number, options?: BaseRequestOptions) ](https://github.com/jdalrymple/gitbeaker/blob/60d028b08579b5fa189889d5a4709c643d682a00/packages/core/src/resources/Tags.ts#L30)
https://docs.gitlab.com/ee/api/tags.html#create-a-new-tag
The "branchName" and "ref" params are missing

**Proposal**

The endpoint should take branchName and ref as the branch method :
.create(projectId: string | number, branchName: string, ref: string, options?: BaseRequestOptions)

**Comment by jdalrymple** [comment]
Since they are added as query params and not body params, currently they are not supported which breaks this function. Definitely a bug, but easy to fix!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`35.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.0.0) :rocket:

**Comment by jdalrymple** [comment]
Delayed release due to #2254
