### ISSUE TITLE
Publishing is broken? Latest changes not in registry.npmjs.org packages

### ISSUE THREAD

**Issue by MartinHowarth** [jdalrymple/gitbeaker#2254]
**Description**

The recent changes we made to the Lint API aren't in the 34.7.0 package found here: https://registry.npmjs.org/@gitbeaker/core/-/core-34.7.0.tgz

That URL is copied out of my `package-lock.json`. 

I think that means that the publishing system for this project is publishing out of date code under the latest tags? Possible that I'm wildly misunderstanding how npm works, but the fact that that tarball doesn't contain the new `lintWithNamespace` function seems pretty strong evidence that the wrong code is being bundled.

The github releases source bundles _do_ contain the right code.

**Comment by jdalrymple** [comment]
UGH, This is frustrating. Im not sure why this happens. Its happened a couple of times and I'm quite confused as to why its not published properly to npm. Lemme trigger a quick build and see if it fixes.

**Comment by jdalrymple** [comment]
The problem is persisting and im not sure why

**Comment by jdalrymple** [comment]
Found IT! Circle CI build cache is wonky.

**Comment by MartinHowarth** [comment]
Great work! I really appreciate how responsive you've been - a pleasure to work with :)

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`35.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.1.0) :rocket:
