### ISSUE TITLE
How to get GitLab API error message, when request failure

### ISSUE THREAD

**Issue by ZeroJian** [jdalrymple/gitbeaker#2264]
**Description**

gitbeaker api catch HttpError, like `HTTPError: Request failed with status code 403`, but GitLab api  returned specific error messages, like { message: "403 Forbidden " }

How to get GitLab API error message?

**Proposal**

**Comment by jdalrymple** [comment]
Right now, to view the error, wrap your call in a try catch. The response follows the [got](https://github.com/sindresorhus/got/blob/main/documentation/8-errors.md) Error structure for now.

```js
try {
// your call
} catch(e){ 
 //e.response?.body
 //e.response?.statusCode ...etc
}
