### ISSUE TITLE
How do I Import Types?

### ISSUE THREAD

**Issue by Balasundaram** [jdalrymple/gitbeaker#2265]
Hi @jdalrymple , 

I am trying to use CommitAction for commiting files from gitbeaker. I am able to get it only by this import

import { CommitAction } from '@gitbeaker/core/dist/types/services/Commits';

I am sure there is better way to do this as yarn tsc is not allowing the above one. Please let me know if there is an alternative.

**Comment by jdalrymple** [comment]
You can import it via any of the [exports pkgs](https://github.com/jdalrymple/gitbeaker#typing-support) (node, core, etc)

```ts
import { Types } from '@gitbeaker/[node|core|browser]'

const a: Types.CommitAction = {}
```

**Comment by Balasundaram** [comment]
Thanks @jdalrymple , however I am not sure if iam doing it right. I am getting unknown module error for the import statement. Am I doing something wrong

"Cannot find module '@gitbeaker/[node|core|browser]' or its corresponding type declarations.ts(2307)"

**Comment by jdalrymple** [comment]
Which version of the library are you using?
