### ISSUE TITLE
`Can't resolve 'form-data'` error with @gitbeaker-browser

### ISSUE THREAD

**Issue by jakub-g** [jdalrymple/gitbeaker#2344]
**Description**

Inside a yarn workspace, when I try to use gitbeaker browser package, I get the following error:

```
ERROR in ./.yarn/cache/@gitbeaker-browser-npm-35.1.0-f353967379-183b977628.zip/node_modules/@gitbeaker/browser/dist/index.js 1:95-115
Module not found: Error: Can't resolve 'form-data' in '/Users/<user>/dev/web-ui/.yarn/cache/@gitbeaker-browser-npm-35.1.0-f353967379-183b977628.zip/node_modules/@gitbeaker/browser/dist'
```

**Steps to reproduce**

My setup: yarn 3.2 + webpack 5.51

```
yarn add @gitbeaker/browser
yarn webpack serve
```

Our `webpack.config.js` is pretty long; I didn't find anything suspicious there, although maybe it can affect the outcome 

**Possible fixes**

By looking at contents of `dist/index.js` it contains a literal call to `require("form-data")`. 
I think this package should be inlined in the dist output by rollup?

My understanding is that `dist/index.js` (which is pointed to by `browser` field in `package.json`) should be standalone and do not have any `require` calls anymore and should not require any additional transpilation steps in webpack.

Especially since it's apparently [only 200 bytes](https://bundlephobia.com/package/form-data@4.0.0) and the browser code [is a trivial oneliner](https://github.com/form-data/form-data/blob/master/lib/browser.js) so maybe even it could be configured inline.

Currently `form-data` is [declared as `external` / `global`](https://github.com/jdalrymple/gitbeaker/blob/master/packages/browser/rollup.config.js#L13-L20)

**Comment by jdalrymple** [comment]
I remember it was added to the external list for a reason, i just dont recall the reason. Ill give it a look!

**Comment by jakub-g** [comment]
By looking at [L13-L28](https://github.com/jdalrymple/gitbeaker/blob/master/packages/browser/rollup.config.js#L13-L28) there are two configs, first for browser, second for node; I think you would want `external` in the latter, but not the first?

However taking a step back, I wonder why a Node/CJS build is needed `browser` package at all? Or is it a CJS build but not really for `node` and the comment is incorrect?  🤔

**Comment by jdalrymple** [comment]
i agree on both counts, ill try removing it and see how it goes

**Comment by jdalrymple** [comment]
Hmm, FormData is supported in the browser natively

**Comment by jdalrymple** [comment]
Can you provide anymore information? I tested with a test repo:

1. yarn init
2. yarn add -D webpack
3. yarn webpack init
4. yarn add @gitbeaker/browser
5. Add "import * as Gitbeaker from '@gitbeaker/browser'" to the index.js file

All worked fine

**Comment by acherkashin** [comment]
@jdalrymple have you used `yarn 3` when you tried to reproduce the issue.

I'm trying to migrate to `yarn 3` in my [pat project](https://github.com/acherkashin/gitlab-codereview-analyzer/tree/dev/use-yarn3), you can use it to reproduce the issue. Make sure you use `dev/use-yarn3` branch. All you need to do is run it and open the browser's console.

![image](https://user-images.githubusercontent.com/9947582/154622802-9893bb10-804e-4464-be41-29aaed880958.png)

**Comment by acherkashin** [comment]
@jdalrymple this issue is fixed when I've added the following code to the `.yarnrc.yml`
```yaml
packageExtensions:
  "@gitbeaker/browser@*":
    dependencies:
      "form-data": "*"
```

**Comment by jdalrymple** [comment]
hmm I wonder why there is a diff. Ill have to do some digging
