### ISSUE TITLE
How to deal with the errors in the declaration file of typesript

### ISSUE THREAD

**Issue by VeryHandSomeBoy** [jdalrymple/gitbeaker#2375]
When I used nestjs to import the package, I encountered the following error:

> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:118 - error TS1110: Type expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                        ~~~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:127 - error TS1005: '}' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                 ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:128 - error TS1128: Declaration or statement expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                  ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:131 - error TS1005: ';' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                     ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:138 - error TS1005: ';' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                            ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:145 - error TS1005: ';' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                                   ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:146 - error TS1005: ';' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                                    ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:150 - error TS1005: ';' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                                        ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:2:180 - error TS1005: '(' expected.
> 
> 2 export declare type CamelizeString<T extends PropertyKey> = T extends string ? string extends T ? string : T extends `${infer F}_${infer R}` ? `${F}${Capitalize<CamelizeString<R>>}` : T : T;
>                                                                                                                                                                                      ~
> 
> node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:14:1 - error TS1160: Unterminated template literal.

**Comment by jdalrymple** [comment]
Might be related #2215 ?

**Comment by VeryHandSomeBoy** [comment]
I try to install typescript@next and solve this problem.

**Comment by jdalrymple** [comment]
ok closing for now
