### ISSUE TITLE
Project path gets double encoded in enable runner API

### ISSUE THREAD

**Issue by ericfitzpatrick** [jdalrymple/gitbeaker#2399]
**Description**

- Node.js version: v16.13.1
- Gitbeaker version: 34.7.0
- Gitbeaker release (cli, node, browser, core, requester-utils): 34.7.0
- OS & version: Windows 10

The projectId input parameter is being encoded twice in the Runners enable API. When a project path is provided, this is causing the forward slash to be encoded twice (from / -> %2f -> %252F), resulting in a 404 Project Not Found error.

The first encodeURIComponent call is in 'enable' (line 55):
https://github.com/jdalrymple/gitbeaker/blob/fe5a2774e84f712a917f4b058c29e8ed30a38a3c/packages/core/src/resources/Runners.ts#L54-L61

The second encodeURIComponent call is in 'endpoint' (line 46):
https://github.com/jdalrymple/gitbeaker/blob/a803c2d288129ee2f61fd848287dd64ec7f591ca/packages/core/src/infrastructure/Utils.ts#L44-L49

Input:                 group/project
First encode:      group%2Fproject
Second encode: group%252Fproject

**Steps to reproduce**

Pass in a project path to the Runners enable API (group/project or user/project) and it will result in a 404 Project Not Found error.

**Expected behaviour**

The projectId input should only be encoded once. The same input works in other gitbeaker APIs (I've used the create branch and create project variable APIs successfully by providing a group/project project path).

**Actual behaviour**

The projectId input is being encoded twice resulting in a 404 Project Not Found error.

[**Possible fixes**]
Remove this line (or at least the pId/projectId part) as it was probably just missed during the last endpoint refactoring update:
https://github.com/jdalrymple/gitbeaker/blob/a803c2d288129ee2f61fd848287dd64ec7f591ca/packages/core/src/resources/Runners.ts#L55

and pass in projectId instead of pId here:
https://github.com/jdalrymple/gitbeaker/blob/fe5a2774e84f712a917f4b058c29e8ed30a38a3c/packages/core/src/resources/Runners.ts#L57

**Checklist**
- [ x ] I have checked that this is not a duplicate issue.
- [ x ] I have read the documentation.

**Comment by jdalrymple** [comment]
Oops! Nice catch!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`35.5.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.5.0) :rocket:
