### ISSUE TITLE
Ability to search issues?

### ISSUE THREAD

**Issue by jcroall** [jdalrymple/gitbeaker#2464]
**Description**

When using the Issues module, is it possible to pass options to it? E.g. to search title/description ("search") or status like opened/closed/all?

At first I thought I could pass options to Issues.all(), but I can't tell if this is actually just pagination options. It doesn't seem to honor the options I'm passing, which are taken from the GitLab API reference. I thought this might work:

```
    let issues = await api.Issues.all({
        projectId: project_id,
        options: {
            search: title_search,
            state: "opened"
        }
    })
```

For a large project the "all" issues could be quite significant and time consuming to filter locally!

Thanks!

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Hey!

With the object styled arguments, you don't need to nest them into an options parameter. This should work: 

```js
 let issues = await api.Issues.all({
        projectId: project_id,
        search: title_search,
        state: "opened"
    })
```

**Comment by jcroall** [comment]
> Hey!
> 
> With the object styled arguments, you don't need to nest them into an options parameter. This should work:
> 
> ```js
>  let issues = await api.Issues.all({
>         projectId: project_id,
>         search: title_search,
>         state: "opened"
>     })
> ```

Thanks! Makes sense, but it still seems to be returning everything. For now I'm post-processing the list, but I worry about scale as projects get larger with longer history.

**Comment by jdalrymple** [comment]
100% Ill give it a double check since it should filter the results with those parameters. 

If you want to paginate those filtered results, you could add offset [pagination settings](https://github.com/jdalrymple/gitbeaker#pagination):

```
const { data, paginationInfo } = await api.Issues.all({
    projectId: project_id,
    search: title_search,
    state: "opened"
    maxPages:2,
    showExpanded: true
});
```

Where the response would be in this format:

```
data: [
...
],
paginationInfo: {
  next: 4,
  current: 2,
  previous: 1,
  perPage: 3,
}
```

**Comment by jdalrymple** [comment]
Its still a bit rough around the edges and is being revisited in #1702, but it should get the job done as it!
