### ISSUE TITLE
Groups resources missing Descendant Groups endpoint

### ISSUE THREAD

**Issue by autumnfound** [jdalrymple/gitbeaker#2483]
**Description**

- Node.js version: 12.22
- Gitbeaker version: latest
- Gitbeaker release (cli, node, browser, core, requester-utils): core
- OS & version: Linux (manjaro-5.15)

Looking into the source of the [Groups resource](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Groups.ts), we are missing the ability to query for descendant groups as described by the [Groups API docs](https://docs.gitlab.com/ee/api/groups.html#list-a-groups-descendant-groups). This is described as being available in 13.5 which I believe is in line with current support.

I'll look into providing a patch for this, as it should be pretty straightforward as it's essentially an extension of the subgroups call that is already available.

**Comment by jdalrymple** [comment]
I was able to add this, but still testing the entire updates in #2258

**Comment by autumnfound** [comment]
No worries, totally get it! Just seeing if the time frame is weeks or months :) much appreciated!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
