### ISSUE TITLE
Please consider adding `Invitations` API

### ISSUE THREAD

**Issue by ccoenen** [jdalrymple/gitbeaker#2484]
**Description**

Currently, one can add a ProjectMember from an existing, known user id. But there seems to be no way to invite users that may or may not have an account on the server. This is usually done via an invitation that's sent out via email.

Documentation: https://docs.gitlab.com/ee/api/invitations.html

**Proposal**

I would love to batch-invite people to a project via gitbeaker. I would like to propose adding Invitations to Gitbeaker.

**Checklist**
- [x] I have checked that this is not a duplicate issue. - only one other issue mentions invite or invitation, and it does not apply.
- [x] I have read the documentation. - there is no Invitation as part of the API, nor does this exist anywhere in the code.

**Comment by jdalrymple** [comment]
Also working on this, just a bit delayed in #2258

**Comment by ccoenen** [comment]
Great! Then we'll just close this, I'm fine with that :-)
