### ISSUE TITLE
Machine-readable error output & exit code

### ISSUE THREAD

**Issue by tennox** [jdalrymple/gitbeaker#2504]
Getting error output like this:
```
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/local/lib/node_modules/@gitbeaker/cli/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1653408838059,
    ...
  },
  description: 'insufficient_scope'
}
```

is a bit problematic to parse.

Can there be a flag to output json format only? as that matches the general output?

Maybe:
```json
{"error": { "code": ..., "description": ... } }
```

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by tennox** [comment]
Also, doesn't seem to return a non-zero exit code... ?!?

**Comment by jdalrymple** [comment]
Yea im forwarding the error from got. There is a case to fix this up. Ill follow up once i get a chance!

**Comment by jdalrymple** [comment]
Fixed in https://github.com/jdalrymple/gitbeaker/pull/2258, the thrown error will include the response object as the 'cause' and use the description in the actual error object.
