### ISSUE TITLE
Typescript unknown type conflict on project schema

### ISSUE THREAD

**Issue by soullivaneuh** [jdalrymple/gitbeaker#2505]
**Description**

- Node.js version: v18
- Gitbeaker version: 35.6.0
- Gitbeaker release (cli, node, browser, core, requester-utils): core
- OS & version: Linux

**Steps to reproduce**

```typescript
gitlab.Groups
  .projects(config.gitlab.groupId, {
    maxPages: 50000,
    include_subgroups: true,
  })
  .then((projects) => {
    const isArchived: boolean = projects[0].archived;

    console.log(isArchived);
  });
```

**Expected behaviour**

Typescript compilation done without any error, as `projects[0].archived` is expected to be a boolean.

**Actual behaviour**

```
error TS2322: Type 'unknown' is not assignable to type 'boolean'.

7     const isArchived: boolean = projects[0].archived;
            ~~~~~~~~~~
```

**Possible fixes**

We should add conditionally typing using `ProjectExtendedSchema` for authenticated requests.

**Comment by jdalrymple** [comment]
Fixed in #2258
