### ISSUE TITLE
GroupHooks support

### ISSUE THREAD

**Issue by soullivaneuh** [jdalrymple/gitbeaker#2512]
**Description**

Similar to current `ProjectHooks`, but for groups.

Ref: https://docs.gitlab.com/ee/api/groups.html#hooks

**Comment by jdalrymple** [comment]
Yup, i put together the work already, but need to finish testing, see the #2258 PR

**Comment by soullivaneuh** [comment]
@jdalrymple I did a specific work for `GroupHooks` in https://github.com/jdalrymple/gitbeaker/pull/2514.

May it be considered?
