### ISSUE TITLE
Add a way to access the request helper

### ISSUE THREAD

**Issue by soullivaneuh** [jdalrymple/gitbeaker#2513]
**Description**

Add a way to access the request helper and make custom GitLab API request but with an already configured client (url, auth...)

The goal is not make the user being stuck because of a not yet supported GitLab API resource scope (for example: #2512).

**Comment by soullivaneuh** [comment]
Hmm can it be doable with this package? https://www.npmjs.com/package/@gitbeaker/requester-utils

I didn't see any documentation about that.

**Comment by jdalrymple** [comment]
Yes that is how you can do it, there is a bit of docs in the Readme but it isnt very verbose, As an example look at the @gitbeaker/node package and see how its implmented

**Comment by soullivaneuh** [comment]
> there is a bit of docs in the Readme but it isnt very verbose

May you please point out a link of that? I may be blind, but I didn't find anything illustrating how to use this requester to communicate directly with the raw GitLab API.

**Comment by jdalrymple** [comment]
https://github.com/jdalrymple/gitbeaker/blob/master/packages/node/src/GotRequester.ts
