### ISSUE TITLE
`SystemHooks.edit()` function throws 404

### ISSUE THREAD

**Issue by lenovouser** [jdalrymple/gitbeaker#2552]
According to the GitLab documentation this functionality doesn't even exist? [docs.gitlab.com/api/system_hooks](https://docs.gitlab.com/ee/api/system_hooks.html)

**Comment by jdalrymple** [comment]
Yea, theyve recently removed it, i need to update the API to match the latest support but i've just been busy with work/thesis stuff :cry:. When i get the chance again, i will have to update to the 15.x API in #2258 , just havent had the time to finish
