### ISSUE TITLE
Consider not overriding user-agent in browser version

### ISSUE THREAD

**Issue by jakub-g** [jdalrymple/gitbeaker#2609]
**Description**

This code overrides user-agent header:

https://github.com/jdalrymple/gitbeaker/blob/6a3292b03342326a98b595a70ab26eb12ddb7ba4/packages/requester-utils/src/BaseResource.ts#L51-L53

However, Chrome doesn't allow this - it's silently ignored, the UA is not overwritten, and requests go out with `user-agent: <standard chrome UA>`.

Firefox allows overriding the UA, but then this triggers a preflight `OPTIONS` request with `Access-Control-Request-Headers: user-agent` header, and the backend must reply with `Access-Control-Allow-Headers: user-agent` -> additional config needed on backend, and a surprising behavior that things fail in Firefox only, while they work in Chrome.

**Proposal**

In browser version, `user-agent` header should not be overridden.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Not a problem. I believe this was done because the underlying library (got and ky) were overriding the user-agent. I will double check and follow up
