### ISSUE TITLE
List projects with node

### ISSUE THREAD

**Issue by abhimeht23** [jdalrymple/gitbeaker#2626]
Hello @jdalrymple and other moderators,

I have a free GitLab account and wanted to test your library in my express app before we finally upgrade to premium. Below is my code to lists all projects but for some reason I am getting an error "Response code 503 (Service Temporarily Unavailable)". 
Pls advise.

`const { Gitlab } = require('@gitbeaker/node');

const api = new Gitlab ({
    host: 'https://gitlab.com/dashboard/projects',
    token: 'hidden',
});

const getUsers = async () => {
    try {
        let users = await api.Projects.all();
        console.log(users);
    } catch (error) {
        console.log(error.message);
    }
    
}

getUsers();

`

**Comment by tomas-rls** [comment]
Use `https://gitlab.com'` as hosts

**Comment by jdalrymple** [comment]
Or just exclude it entirely and the default host `https://gitlab.com` will be used
