### ISSUE TITLE
How to get the data out from api.Users.search

### ISSUE THREAD

**Issue by Importsunflower** [jdalrymple/gitbeaker#2668]
**Description**
I try to get the data from the api.Users.search but it used the .then function when i return the data out from the function it shows undefind.

export function detals(username,tokenpass){
  let pp;
  const api = new Gitlab({
    token: tokenpass,
    });
    api.Users.search(username,{ includeInherited: true }).then( data => {
      pp = data;
      return(pp)
    }).catch( error => {
      return error;
  })
}

**Comment by Importsunflower** [comment]
`export function detals(username,tokenpass){
  let pp;
  const api = new Gitlab({
    token: tokenpass,
    });
    api.Users.search(username,{ includeInherited: true }).then( data => {
      pp = data;
      return(pp)
    }).catch( error => {
      return error;
  })
}`

**Comment by jdalrymple** [comment]
```js
export function details(username, token) {
   const api = new Gitlab({token})
   return api.Users.search( username, {includeInherited: true })
}

const d = await details('username', 'token')

```

This should work

**Comment by Importsunflower** [comment]
> 

It works! thanks for your reply

**Comment by Importsunflower** [comment]
And sorry for another two questions for api.Groups.all I uesd：
`export function Getgroups(tokenpass){
    const api = new Gitlab({tokenpass})
    return api.Groups.all(tokenpass)
}
let d = await Getgroups(token)
`
but it does not have any resopnse, and for api.ProjectMembers.all(ProjectId) it show the '401 Unauthorized' even if I am the owner of that project or group
`export function getprojects(userId,tokenpass){
    const api = new Gitlab({token:tokenpass})
    return api.Users.projects(userId)
}`
