### ISSUE TITLE
Add merge request level approval rules

### ISSUE THREAD

**Issue by InsidersByte** [jdalrymple/gitbeaker#2673]
**Description**

Add merge request level rules https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-merge-request-level-rules

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
fixed by #2258

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
