### ISSUE TITLE
Add function to get a users starred projects

### ISSUE THREAD

**Issue by JulesRenz** [jdalrymple/gitbeaker#2683]
**Description**

Today, gitbeaker already has the ability to get a users projects via `Gitlab.Users.projects()`. This calls the GitLab API endpoint at `/users/:user_id/projects`, see [here](https://docs.gitlab.com/ee/api/projects.html#list-user-projects)

What I miss is the functionality to also get the starred projects of a user, that is expose very similarly by the GitLab API `/users/:user_id/starred_projects`, see [here](https://docs.gitlab.com/ee/api/projects.html#list-projects-starred-by-a-user)

**Proposal**

I propose to implement this as a function `Gitlab.Users.starredProjects()` very similarly as it is done in `Gitlab.Users.projects()` but calling the appropriate endpoint `/users/:user_id/starred_project` instead.
Also, I'm willing to contribute this if you agree, that this is a feature, that should be in gitbeaker

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
