### ISSUE TITLE
Problem in get commit.

### ISSUE THREAD

**Issue by Importsunflower** [jdalrymple/gitbeaker#2686]
I tried to use Commits. all method to get the commit in a project to alculate the number of commits for each member.
But it shows :"description: 'invalid_token'",
I tried the same token in Postman it works.
`export function getcommit(ProjectId,token){
    const api = new Gitlab({token})
    api.Commits.all(
        ProjectId, {includeInherited: true }
    )
}`
In Postman is :"GET/ https://gitlab.com/api/v4//projects/:id/repository/commits"

**Comment by Importsunflower** [comment]
Please tell me if I am using the wrong method.

**Comment by gluecksmensch** [comment]
@Importsunflower how did you solved this? Having the same issue.

**Comment by gluecksmensch** [comment]
For anyone who is also looking for a solution, you need to pass the `maxPages` pagination parameter:

`await commits.all(PROJECT_ID, { maxPages: 1 })`

From this comment https://github.com/jdalrymple/gitbeaker/issues/233#issuecomment-437573978
