### ISSUE TITLE
Endpoint URL for ContainerRegistry.showRegistry() is wrong

### ISSUE THREAD

**Issue by PaulSchult** [jdalrymple/gitbeaker#2695]
**Description**

- Node.js version: 16.13.0
- Gitbeaker version: ^35.6.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: Manjaro 21.3.7

**Steps to reproduce**

1. Connect Via gitbeaker to gitlab
2. Try to query ContainerRegistry.showRepository(projectId: string | number, repositoryId: number, options?: Sudo) 
3. Will return HTTP 404

**Expected behaviour**

Getting Information on this specific repository.

**Actual behaviour**

HTTP 404

**Possible fixes**

The Endpoint URL is wrong for the given task. It shouldn't include "projects/${projectId}".
https://docs.gitlab.com/14.10/ee/api/container_registry.html#get-details-of-a-single-repository

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Not sure how i missed this, nice catch
