### ISSUE TITLE
Invalid type returned by `Pipeline.show`

### ISSUE THREAD

**Issue by szopqa** [jdalrymple/gitbeaker#2700]
**Description**

- Node.js version: v16.16.0
- Gitbeaker version: ^35.7.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: macOS Montery (M1)

I encountered invalid type being returned by `.show` in `PIpelines` resource - currently it returns `PipelineSchema`
![image](https://user-images.githubusercontent.com/16049905/191676948-ee5b5a8b-d45d-48bb-9f7f-22544f9a139b.png)

whereas according to Gitlab spec it's missing some of it's response fields https://docs.gitlab.com/ee/api/pipelines.html#get-a-single-pipeline. I think that `.show` should return https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Pipelines.ts#L35 in this case.

**Steps to reproduce**

1. invoke `const res = await Pipelines.show(...)` method
2. `res.started_at` is reported as missing in return type, whereas it's available in the response

**Expected behaviour**
`Pipelines.show` returns correct `Expended` type

**Actual behaviour**

`Pipelines.show` returns `PipelineSchema` type with missing fields available in the actual response

**Possible fixes**

Correct return type

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:
