### ISSUE TITLE
Wrong type for options in Repositories.showArchive

### ISSUE THREAD

**Issue by melangue** [jdalrymple/gitbeaker#2701]
**Description**

- Node.js version: 16.17.0
- Gitbeaker version: 35.7.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: Ubuntu Linux 21.02

According to https://github.com/jdalrymple/gitbeaker/issues/881 and https://github.com/jdalrymple/gitbeaker/issues/133 I can see that I can pass in `sha` in options object when requesting an archive of a repository. It seems that the types declared for options passed to this method are wrong, as visible on this screenshot:

![image](https://user-images.githubusercontent.com/14099001/191731937-bd205782-d5c7-4298-b9a5-950e2425e4c7.png)

Full TypeScript error:
```
Argument of type '{ sha: string; }' is not assignable to parameter of type '{ fileType?: ArchiveType | undefined; } & Sudo'.
  Object literal may only specify known properties, and 'sha' does not exist in type '{ fileType?: ArchiveType | undefined; } & Sudo'
```

**Steps to reproduce**

Create new instance of either `Repositories` or whole `Gitlab` and try adding `sha` as an argument to options object of `showArchive` method.

**Expected behaviour**

Type should be correct, i.e. I should be able to pass in `sha` as string to options of `showArchive` method.

**Actual behaviour**

I see a TypeScript error about a wrong type.

**Possible fixes**

Fix the types.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
See my response to the connected issue
