### ISSUE TITLE
How to get ReadableStream from Repositores.showArchive?

### ISSUE THREAD

**Issue by melangue** [jdalrymple/gitbeaker#2702]
**Description**

According to https://github.com/jdalrymple/gitbeaker/issues/297 I should be able to get a ReadableStream back from `Repositories.showArchive`, but I cannot find any information about how to do that.

Tried passing
```js
{
 stream: true
}
```
to options object of the method (had to cast it as any, thought maybe it's somehow connected to https://github.com/jdalrymple/gitbeaker/issues/2701) but no dice, the actual return type is still `Promise<Buffer>`

Am I doing something wrong? Or Maybe there should be an example on how to do this?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
I believe there was a bug in the old code that handled streams. I've fixed this in a beta branch (#2258) but its still very much a work in progress. Let me double check over the next few days and follow up

**Comment by melangue** [comment]
Alright, appreciate the fast reply, gonna wait for more info.

**Comment by Hives** [comment]
hi 👋

any news on this? would love to be able to use this feature

thanks

**Comment by jdalrymple** [comment]
Not yet :( sorry, I've just been swamped

**Comment by Hives** [comment]
no worries!
