### ISSUE TITLE
Groups.search options parameter typed only as Sudo but should be PaginatedRequestOptions (or at least BaseRequestOptions)

### ISSUE THREAD

**Issue by phillipB-nmprofile** [jdalrymple/gitbeaker#2812]
**Description**

Currently the Groups.search function's options parameter is typed as a Sudo. However, GitLab supports all the same pagination options as the Groups.all function plus extras like "min_access_level". This is understandable because the documentation of https://docs.gitlab.com/ee/api/groups.html#search-for-group is horrible and doesn't let on that you can pass these extra parameters.

As a general comment, I would not type any of the options parameters as just Sudo unless it can be reasoned that query parameters will NEVER make sense for the given GitLab feature (which should be very rare). Typing them them as at least a BaseRequestOptions will allow for users to still use GitLab API query parameters that gitbreaker hasn't caught up with.

**Proposal**

Change the type of the options parameter of the Groups.search function from Sudo to PaginatedRequestOptions:

  search(nameOrPath: string, options?: PaginatedRequestOptions) {
    return RequestHelper.get()(this, 'groups', {
      search: nameOrPath,
      ...options,
    });
  }

**Checklist**
- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`35.8.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.8.0) :rocket:
