### ISSUE TITLE
TypeScript: How to correctly define a type for a var, that will hold the Gitlab object?

### ISSUE THREAD

**Issue by udondan** [jdalrymple/gitbeaker#2815]
**Description**

The question sounds strange and I feel embarrased to ask it. But I can't figure this out. There might be something wrong with the types in the package or a problem with TypeScript itself or my tsconfig... I just can't figure it out.

I want to build a package that initializes `Gitlab()` in a lazy way on demand, but that requires me to define its type explicitly.

```ts
import { Gitlab } from '@gitbeaker/node';

let gitlab: Gitlab | undefined;

if (!gitlab) {
  gitlab = new Gitlab({
    host: 'my.host',
    token: '1234567890',
  });
}
```

This fails with:

```
'Gitlab' refers to a value, but is being used as a type here. Did you mean 'typeof Gitlab'?ts(2749)
```

![Screenshot 2022-11-07 at 10 31 30](https://user-images.githubusercontent.com/6443408/200278426-f8cdd74f-e424-4dd8-8b45-a2db6a05640b.png)
![Screenshot 2022-11-07 at 10 31 08](https://user-images.githubusercontent.com/6443408/200278398-e969acd4-2123-4d35-a650-4262d09beea5.png)

That's very strange, because when I look at the definition, `Gitlab` itself is defined as `typeof Resources.Gitlab`.

So, when I do what TypeScript suggests:

```ts
import { Gitlab } from '@gitbeaker/node';

let gitlab: typeof Gitlab | undefined;

if (!gitlab) {
  gitlab = new Gitlab({
    host: 'my.host',
    token: '1234567890',
  });
}
```

The assignment fails with:

```
Property 'prototype' is missing in type 'Gitlab<false>' but required in type 'typeof Gitlab'.ts(2741)
```

![Screenshot 2022-11-07 at 10 32 10](https://user-images.githubusercontent.com/6443408/200280379-776ccf92-0506-498e-899e-ad565127c6c2.png)
![Screenshot 2022-11-07 at 10 31 57](https://user-images.githubusercontent.com/6443408/200280413-5e130750-3b52-4aa1-88cf-3296021d4521.png)

I'm running TypeScript 4.8.4 (latest) and this is my tsconfig:

```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "CommonJS",
    "lib": ["es2018", "dom"],
    "declaration": true,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "stripInternal": true,
    "noImplicitAny": true,
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "charset": "utf8",
    "typeRoots": ["./node_modules/@types"],
    "outDir": "dist"
  },
  "include": ["src/*.ts"],
  "exclude": ["node_modules"]
}
```

How to solve this?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by robdonn** [comment]
```ts
import { Gitlab } from '@gitbeaker/node';

let gitlab: InstanceType<typeof Gitlab> | undefined;

if (!gitlab) {
  gitlab = new Gitlab({
    host: 'my.host',
    token: '1234567890',
  });
}
```

**Comment by udondan** [comment]
Interesting. Thanks @robdonn. Doing typescript since ~2 years and never have seen this nor had to do such a stunt. 😸

**Comment by joshjung** [comment]
I realize this is closed, and am thankful for the answer, but this is so unorthodox that I think there should be a more "normal" way to do this :(

**Comment by jdalrymple** [comment]
@joshjung That would be ideal. It looks like the either the re-export in the rest/index.ts file doesnt bubble up the typing as it should. It is there in the file itself, and its even there after the wrapper presets the props, but alas, issues. If you have more insights on how to improve it, Im always open to suggestions! :pray:
