### ISSUE TITLE
Unable to add note to merge request discussion using discussionId

### ISSUE THREAD

**Issue by robdonn** [jdalrymple/gitbeaker#2817]
**Description**

- Node.js version: `18.11.0`
- Gitbeaker version: `35.7.0`
- Gitbeaker release (cli, node, browser, core, requester-utils): `node`
- OS & version: MacOS 12.6
- GitLab version: [15.1.1-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v15.1.1-ee)

When trying to add a note to a merge request discussion, the discussion ID returned by `MergeRequestDiscussions.all` cannot be used as it is a `string` while the `MergeRequestDiscussions.addNote` method requires the discussion ID to be a `number`.

<img width="770" alt="Screenshot 2022-11-10 at 22 30 49" src="https://user-images.githubusercontent.com/7869669/201220656-dfb10d14-0a19-4b02-8227-23715ea1e1ac.png">

_Example response of `MergeRequestDiscussions.all` returning strings for id_

<img width="442" alt="Screenshot 2022-11-10 at 22 43 38" src="https://user-images.githubusercontent.com/7869669/201221766-6bd53235-973a-4684-b349-9a6287bc03cc.png">

**Steps to reproduce**

```ts
const api = new Gitlab({
  token: GITLAB_TOKEN,
  host: GITLAB_HOST,
});

const discussions = await api.MergeRequestDiscussions.all(
  projectId,
  mergeRequestId
);

discussions.forEach((discussion) => {
  if (!discussion?.notes?.length) {
    return;
  }

  const [firstNote] = discussion.notes;

  api.MergeRequestDiscussions.addNote(
    projectId,
    mergeRequestId,
    discussion.id,
    firstNote.id,
    'My reply'
  );
});
```

**Expected behaviour**

The `addNote` method should accept a `string` type for the `discussionId` parameter.

**Actual behaviour**

The `addNote` method only accepts a `number` type for the `discussionId` parameter.

**Possible fixes**

Update the type interface for the `MergeRequestDiscussions` API to accept a `string` type for the `discussionId` parameters in it's methods.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`35.8.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.8.0) :rocket:
