### ISSUE TITLE
Missing key `resolved` in DiscussionNote interface

### ISSUE THREAD

**Issue by DerHerrGammler** [jdalrymple/gitbeaker#2820]
**Description**

- Node.js version: 16.16.0
- Gitbeaker version: 35.7.0
- Gitbeaker release (cli, node, browser, core, requester-utils):
- OS & version: Win 11

If you load some Discussions from a Merge Request you will get discussion notes that can be resolvable.  
In addition to this, there is a key `resolved: boolean` but currently the interface `DiscussionNote` does not have this.

**Steps to reproduce**

1. User the MergeRequestDiscussions Api to load some discussions
2. Try to access the `resolved` key of a note.
3. If you log the note you will see the `resolved` key

**Expected behaviour**

The `DiscussionNote` interface should have the key.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`35.8.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.8.0) :rocket:
