### ISSUE TITLE
How do I pass optional parameters to a function?

### ISSUE THREAD

**Issue by Bmr55** [jdalrymple/gitbeaker#2842]
**Description**

I'm trying to compare branches, but I need to pass the optional parameter `straight=true` described in the [GitLab API Documentation](https://docs.gitlab.com/ee/api/repositories.html#compare-branches-tags-or-commits) to get the results I want. However, looking at `Repositories.compare` I see it only accepts the type `Sudo` for `options`.

```typescript
Repositories.compare(projectId: string | number, from: string, to: string, options?: Sudo): Promise<import("../infrastructure").CamelizedRecord<C, RepositoryCompareSchema>>;
```

Is there a way to do this or is a change required to support it? I was browsing Issues and I came across [this issue](https://github.com/jdalrymple/gitbeaker/issues/2812) that resulted in the type `Sudo` being changed to `BaseRequestOptions` in `Groups.search`. Maybe that would allow me to pass the parameter I want?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
This should be switched as you mentioned!

**Comment by Bmr55** [comment]
I see `Repositories.contributors` also has this problem. Is this a good first issue? If permitted, I'd be willing to make the change.

**Comment by few-bits** [comment]
Hi @Bmr55, @jdalrymple ! So, is it a bug? I want to pass `include_retried` flag for the `Jobs.showPipelineJobs` method, but faced with the same issue: only `JobScope` and `Sudo` are allowed.

**Comment by jdalrymple** [comment]
Yup its a bug! Fixing them in #2258. Feel free to look over the code to ensure i didnt miss any particular pieces of interest.
