### ISSUE TITLE
Stuck on Projects.all for ever

### ISSUE THREAD

**Issue by algorlab** [jdalrymple/gitbeaker#2878]
**Description**

- Node.js version: 19.0.0
- Gitbeaker version: 35.8.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: Ubuntu 22.04

I got stuck on `Projects.all` for ever without receiving any response.

**Steps to reproduce**

This is the code: 

```
  const api = new Gitlab({
    token: <PAT>
  });

    const projects = await api.Projects.all({
      pagination: "offset",
      perPage: pagingType.limit,
      showExpanded: true
    });
```

**Checklist**
- [ x] I have checked that this is not a duplicate issue.
- [ x] I have read the documentation.

**Comment by jdalrymple** [comment]
The paginated results automatically pulls all the results by default. Try setting a max number of pages i.e "maxPages: 3". Right now, the code is trying to pull all the projects you have access to.

**Comment by algorlab** [comment]
Solved. thanks!
