### ISSUE TITLE
Changing Repositories.showArchive to return a stream

### ISSUE THREAD

**Issue by yyxiong** [jdalrymple/gitbeaker#297]
Repositories.showArchive should accept stream option to download archive

**Comment by jdalrymple** [comment]
Yea that would be a good idea. Going to hold off changing this though until #265 is finished.

**Comment by jdalrymple** [comment]
Just waiting to get confirmation for the streaming API in ky :)

**Comment by jdalrymple** [comment]
Putting this on hold until ky supports streaming

**Comment by jdalrymple** [comment]
One solution could be switching KyRequester with a GotRequester for the non browser versions on the rollup build? 🤔

**Comment by jdalrymple** [comment]
Should be streamable now with the @gitbeaker/node package
