### ISSUE TITLE
Missing `erased_at` property in job interface

### ISSUE THREAD

**Issue by DerHerrGammler** [jdalrymple/gitbeaker#3011]
**Description**

- Node.js version: 16.16.0
- Gitbeaker version: 35.8.0
- Gitbeaker release (cli, node, browser, core, requester-utils):
- OS & version:

You can access `erased_at` at the loaded jobs wich is the date of the job log and artifact cleanup/deletion.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by DerHerrGammler** [comment]
i created a pr to fix this issue

**Comment by jdalrymple** [comment]
Fixed in #2258
