### ISSUE TITLE
hi, Using gitbeaker in my project, error Module not found: Error can t resolve 'fs', 'dns', 'http2', 'tls', 'dns' in webpack,  is there any solution

### ISSUE THREAD

**Issue by jiajia756** [jdalrymple/gitbeaker#3060]
**Description**

**Checklist**
- [ ] I have checked that this is not a duplicate issue.
- [ ] I have read the documentation.

**Comment by jdalrymple** [comment]
This is because the package you're using (im guessing not the browser distribution) has dependencies on native nodejs modules. This complexity has been removed in the latest release. Check back in a couple weeks #2258
