### ISSUE TITLE
Create a multi-environment testing script

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/gitbeaker#309]
**Description**
There are three compiled versions of this library, one for the browser, one for commonjs and one as a es module. However, the testing procedures only run on the src and supported nodejs versions. This has led to some problems in the past where the released binaries have errors that were not captured during the testing procedure.

**Proposal**
Overhaul the testing procedure to additionally run the tests on the compiled binaries for each environment.

**Comment by jdalrymple** [comment]
I recently changed the integration tests to run on the compiled binaries in the dist folder. This problem shouldn't arise again BUT we should include browser testing to ensure its compatibility

**Comment by DanielRuf** [comment]
See https://github.com/verdaccio/verdaccio/tree/master/test as example (e2e using puppeteer, unit and integration testing, ...).

**Comment by jdalrymple** [comment]
Added CLI tests and basic browser import tests in the latest release @19.0.0

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`22.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/22.0.0) :rocket:
