### ISSUE TITLE
CLI JSON params

### ISSUE THREAD

**Issue by atillier** [jdalrymple/gitbeaker#3104]
**Description**

I am unable to pass complex params like a JSON object over the CLI. Example:

`gitbeaker merge-requests edit 2 178 '{"assignee_id":2}'`

The params are ignored when doing so which means I get an error like

```
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/Users/adrien/.nvm/versions/node/v19.4.0/lib/node_modules/@gitbeaker/cli/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1678466362837,
    socket: 1678466362839,
    lookup: 1678466362840,
    connect: 1678466362872,
    secureConnect: 1678466362905,
    upload: 1678466362905,
    response: 1678466363007,
    end: 1678466363010,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 1,
      tcp: 32,
      tls: 33,
      request: 0,
      firstByte: 102,
      download: 3,
      total: 173
    }
  },
  description: 'assignee_id, assignee_ids, reviewer_ids, description, labels, add_labels, remove_labels, milestone_id, remove_source_branch, allow_collaboration, allow_maintainer_to_push, squash, target_branch, title, state_event, discussion_locked are missing, at least one parameter must be provided'
}
```

How is the CLI passing params like a JSON object? 

**Checklist**
- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
You should be able to pass those parameters like optional cli arguments. For example --assignee-id=2

**Comment by jdalrymple** [comment]
;) https://github.com/jdalrymple/gitbeaker#getting-started CLI section, first example:

```bash
gitbeaker [service name] [method name] --config_args pos_arg1 pos_arg2 --opts_arg1
```

But yea, I can make it more clear

**Comment by atillier** [comment]
Yeah I 100% saw that one but my mind didn't click for more complexe objects like these edit objects. An example for such could help others like me struggling to connect the dots.

**Comment by jdalrymple** [comment]
Is this a bit clearer? https://github.com/jdalrymple/gitbeaker/tree/test-ci-branch/packages/cli#usage

**Comment by atillier** [comment]
Getting a 404, branch is private somehow?

**Comment by jdalrymple** [comment]
Oh because the branch was deleted one sec

**Comment by jdalrymple** [comment]
https://github.com/jdalrymple/gitbeaker/tree/1897-explicit-typing/packages/cli#usage

**Comment by atillier** [comment]
Yep looks better! 👍 

Small typo on `the this table` though
