### ISSUE TITLE
MR edit not doing anything

### ISSUE THREAD

**Issue by atillier** [jdalrymple/gitbeaker#3113]
**Description**

- Node.js version: 19.4
- Gitbeaker version: 35.8.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: Mac OS Ventura

My MR edit requests are not doing anything on my actual MR. They don't fail but the MRs are not edited as in working in a sort of dry mode. 

**Steps to reproduce**

```
(async() => { 

  try{
  await api.MergeRequests.edit(
    mr.project_id, 
    mr.id,
    {
      title: 'Changed MR title'
    });
  } catch(e){ 
    console.log(e);
  }   
});  
```

**Expected behaviour**

MR is edited

**Actual behaviour**

MR is not edited

**Notes**
I tried via the CLI and it's working fine with the same token. So it's not a permission issue. When I am missing some params or mess around the token in Node I am getting an error / API response back. 

**Checklist**
- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
Hey! So i tested this, with the 35.8.0 release and didn't run into any issues. Can you provide any more information that could possibly affect this? Do you receive anything as a response? 

Just for completeness, this is the MR i was playing with: https://gitlab.com/jdalrymple/sample2/-/merge_requests/1

and here is the code:

```javascript
const api = new Gitlab({
  token: 'xxxxxxx',
})

api.MergeRequests.edit(21015560, 1, { title: 'Testing title 2'})
.then(r => {
  console.log(r)
})
```

I'm running node 18.7.0 on Arch linux

**Comment by atillier** [comment]
Many thanks for trying out ; and yes definitely something wrong on my end... 

I am actually using your lib via Danger JS which is encapsulating your code pretty badly. It means all debug logs were swallowed... But as I tried a direct call with your snippet I can see it wasn't updating the right MR I thought it was. 

Anyway, case closed and thanks again!
