### ISSUE TITLE
Issue importing types from "@gitbeaker/core/dist"

### ISSUE THREAD

**Issue by ItamarMalka** [jdalrymple/gitbeaker#3134]
**Description**
When upgrading from gitbreaker 35.8.0 => 35.8.1 we are experiencing some errors on the type imports from gitbreaker,
importing 
```
import type { UserDetailSchema } from '@gitbeaker/core/dist';
```
results in:
```
error TS2305: Module '"@gitbeaker/core/dist"' has no exported member 'UserDetailSchema'.
```

Is this a known issue that would be fixed or is there any mitigation available for that issue?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Also, what type are you looking for exactly?

**Comment by ItamarMalka** [comment]
There are a couple of them that we use, but the one mentioned I mentioned on the tickets had problems...
I'll have a go at the canary and see if it persists 👍

**Comment by jdalrymple** [comment]
No problem, that type was renamed many years ago to simply UserSchema. See commit: [a02d815f95d1333afa1eefe395222db4df2e078b](https://github.com/jdalrymple/gitbeaker/commit/a02d815f95d1333afa1eefe395222db4df2e078b) from back in 27/09/2020
