### ISSUE TITLE
Missing MergeTrain endpoint

### ISSUE THREAD

**Issue by AJDurant** [jdalrymple/gitbeaker#3141]
**Description**

The Gitlab API has an endpoint for getting data about Merge Trains, and adding MRs to the train, but this is not implemented by gitbeaker.

**Proposal**

I have created a basic implementation [in a fork](https://github.com/AJDurant/gitbeaker/tree/merge-trains), aiming to follow how other elements of gitbeaker work.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Checkout the latest canary release on @gitbeaker/rest
