### ISSUE TITLE
Version 35.8.1 is available in NPM but I didn't find a corresponding tag in this repo, how can I check the release contents ?

### ISSUE THREAD

**Issue by mgarstecki** [jdalrymple/gitbeaker#3151]
**Description**

Hi, I have seen a dependency bump to 35.8.1, but can't find the corresponding tag in this repository, which prevents me from checking the diff. Which version of the code does this version correspond to ?

Thanks !

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
No dep bump. It was simply a rerelease since I mistakenly added a release to latest and was unable to unpublish it immediately after.
