### ISSUE TITLE
Support for personal access token API

### ISSUE THREAD

**Issue by fredricfoo** [jdalrymple/gitbeaker#3177]
**Description**
Would be nice to have support for [Personal Access token API](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/personal_access_tokens.md). It provides useful functionality such as checking the scope assigned to the access token

**Checklist**
 - [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Checkout the @gitbeaker/rest canary release!
