### ISSUE TITLE
Add support to share groups with groups

### ISSUE THREAD

**Issue by abonawit** [jdalrymple/gitbeaker#3191]
**Description**

The groups resource does not currently support sharing groups with other groups.

Enable sharing groups with groups as described here: https://docs.gitlab.com/ee/api/groups.html#share-groups-with-groups

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Yup, should be supported in @gitbeaker/rest canary build!

**Comment by abonawit** [comment]
Awesome. Is there an ETA on that build?

**Comment by jdalrymple** [comment]
ASAP haha, Gitlab keeps updating their API faster than i can validate the release -_-. I have about 10 more APIs to look over to make sure i didn't miss anything major.

**Comment by abonawit** [comment]
Haha perfect. Thank you for the quick responses on this!
