### ISSUE TITLE
Sponsoring gitbeaker

### ISSUE THREAD

**Issue by cosydney** [jdalrymple/gitbeaker#3203]
**Description**
We use GitBeaker in our repository and it has been super helpful thank you for making this. 

I'd like to discuss the possibility of sponsoring the package.

Who should I get in contact with?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Hey! I'm super glad you've found the package so helpful! Just fire my a message at my personal email justin.s.dalrymple@gmail.com
