### ISSUE TITLE
How do I import types at version 37.0.0

### ISSUE THREAD

**Issue by sebsgr** [jdalrymple/gitbeaker#3223]
**Description**

How is it possible to import types of api functions like `MergeRequestSchema`.

Since Version 37.0.0 it is not possible to import types as in older versions like the following snippet.
`import {MergeRequestSchema} from "@gitbeaker/core/dist/types/resources/MergeRequests";`

I have tried the following imports:
`import {MergeRequestSchema} from "@gitbeaker/core";`
`import {MergeRequestSchema} from "@gitbeaker/rest";`

The import from `@gitbeaker/core` leads to a compile error:
> "@gitbeaker/core"' has no exported member named 'MergeRequestSchema'

I think the right way is to export all types which are used by public api functions.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.1.0) :rocket:
