### ISSUE TITLE
Warning when try to import '@gitbeaker/rest' 

### ISSUE THREAD

**Issue by merorafael** [jdalrymple/gitbeaker#3230]
**Description**

- Node.js version: 19.9.0
- Gitbeaker version: 38.0.1
- Gitbeaker release (cli, node, browser, core, requester-utils): rest
- OS & version: Arch Linux

The eslint shows the warning message below
` "@gitbeaker/rest" is not found. eslint[node/no-missing-import]`([node/no-missing-import](https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/no-missing-import.md)) when trying to import `GitLab`  from `@gitbeaker/rest`.

**Steps to reproduce**

Import  `GitLab`  from `@gitbeaker/rest` using the structure below:

````ts
import {Gitlab} from '@gitbeaker/rest'
```` 

It is not relevant information, but the eslint settings use `oclif`  and `oclif-typescript`  rules.

**Expected behaviour**

No warnings when importing the `@gitbeaker/rest` 

**Actual behaviour**

Warning [node/no-missing-import](https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/no-missing-import.md) on ` @gitbeaker/rest` module. 

**Possible fixes**

**Checklist**
- [ ] I have checked that this is not a duplicate issue.
- [ ] I have read the documentation.

**Comment by jdalrymple** [comment]
Odd. From the docs, it seems to say that the module itself does not exist? Do you receive the same errors with different imports ie Projects, Issues, etc? Is it just the Gitlab one?

**Comment by jdalrymple** [comment]
Following up, any more information?

**Comment by merorafael** [comment]
It's only this library.

**Comment by jdalrymple** [comment]
Hmm, im not sure. Though i doubt it would change, have you tried updating the library version youre using, or perhaps refreshing your package-lock or yarn-lock file?

**Comment by jdalrymple** [comment]
Thanks for the additional info! Ill see if i can find some custom eslint resolvers that i could utilize

**Comment by merorafael** [comment]
I put an example in a public repository here. 
Here is the code: https://github.com/merorafael/gitbeaker-error-example/blob/main/src/commands/hello/index.ts

If you need to test, you must clone this repository and run `yarn lint`.

**Comment by jdalrymple** [comment]
Okay few ways to resovle this:

1. Ignore the rule for this library:

```
  "rules": {
    "node/no-missing-import": ["error", { "allowModules": ["@gitbeaker/rest"] }]
  }
```

2.  Use an additional resolver: https://www.npmjs.com/package/eslint-import-resolver-exports, though i didnt have much luck when testing this. 

As @tbazin mentioned, this is because the eslint resolver just doesnt support export keyword as of yet.

**Comment by nawaz-malla** [comment]
File d/contract.py", line 4, in <module>
    app = Application("External Example App")

how can I solve the issue

**Comment by jdalrymple** [comment]
@nawaz-malla Can you provide more information. It looks like the code you included is python..

**Comment by nawaz-malla** [comment]
from beaker import *
from pyteal import Expr, abi

app = Application("External Example App")


@app.external
def add(a: abi.Uint8, b: abi.Uint8, *, output: abi.Uint8) -> Expr:
    return output.set(a.get() + b.get())

**Comment by jdalrymple** [comment]
Again...thats python.

**Comment by nawaz-malla** [comment]
how can i solve , i am following some videos , they use beaker, I am using same code but I face the issue. 
hoiw can I solve the issue.

 algokit doctor
timestamp: 2024-03-27T00:18:17+00:00
AlgoKit: 1.13.1
AlgoKit Python: 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (location: /Users/nawaz/Desktop/Algorand/Library/Application Support/pipx/venvs/algokit)
OS: macOS-14.4-x86_64-i386-64bit
docker: 25.0.2
docker compose: 2.24.3-desktop.1
git: 2.39.3
python: Command not found!
python3: 3.12.1 (location: /usr/local/bin/python3)
pipx: 1.4.3
poetry: 1.8.2
node: 21.6.2
npm: 10.2.4
brew: 4.2.15
there are details I am using

**Comment by jdalrymple** [comment]
@nawaz-malla Feel free to open a new issue with a template project to outline your problem
