### ISSUE TITLE
Pipeline triggering feature was deleted

### ISSUE THREAD

**Issue by cperreaut** [jdalrymple/gitbeaker#3236]
**Description**

At some point in time of this project, the gitlab API could be called to trigger a pipeline on a project (https://github.com/jdalrymple/gitbeaker/commit/5858fc) , but the project structure has changed a lot since then and the trigger feature seems to have been lost in the changes. 
I would expect to find it here : https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/Pipelines.ts or here https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/PipelineTriggerTokens.ts in the trigger method, but the trigger method seems to do the same as the create method.

**Proposal**

Add the trigger pipeline for a project following this documentation : https://docs.gitlab.com/ee/ci/triggers/

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
I must of lost it during the latest updates! Ill fix this today!

**Comment by jdalrymple** [comment]
That method is exactly what you found in PipelineTriggerTokens > trigger. The trigger method and the create method are different if you look at the endpoints used:

[trigger](https://docs.gitlab.com/ee/api/pipeline_triggers.html#trigger-a-pipeline-with-a-token):
      endpoint`projects/${projectId}/pipelines`,

[create](https://docs.gitlab.com/ee/api/pipeline_triggers.html#create-a-trigger-token):
      endpoint`projects/${projectId}/triggers`,

**Comment by WiseBird** [comment]
@jdalrymple [The documentation](https://docs.gitlab.com/ee/api/pipeline_triggers.html#trigger-a-pipeline-with-a-token) says that url for triggering a pipeline is `projects/<project_id>/trigger/pipeline`, but in [the code](https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/PipelineTriggerTokens.ts#L93) it's `projects/${projectId}/pipelines`. Is this an error or did I miss something?

Also, the old code used to pass `isForm` flag:
```
    return RequestHelper.post()(this, endpoint`projects/${projectId}/trigger/pipeline`, {
      isForm: true,
      ref,
      token,
      ...hapiVariables,
    });
```
Do you think it's needed in the new code as well?

**Comment by jdalrymple** [comment]
I recall there being a weird endpoint to trigger a pipeline until recently, but honestly dont remember. Looks like something i overlooked. Ill reopen and fix it up!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.0.0) :rocket:

**Comment by d-fischer** [comment]
Passing variables still doesn't seem to work.

Calling this:

```js
return gitlab.PipelineTriggerTokens.trigger(DEPLOYER_PROJECT_ID, 'master', process.env.DEPLOYER_TRIGGER_TOKEN!, {
  variables,
});
```

Results in this (and actually no variables passed, so our deployment fails):

![screenshot](https://github.com/jdalrymple/gitbeaker/assets/5854687/1fb856a4-7760-4e33-9634-bc9b3513b73e)

**Comment by jdalrymple** [comment]
Typo on my part! Fixing ASAP

**Comment by jdalrymple** [comment]
Should be live now! Tell me if you run into any other problems :D

**Comment by d-fischer** [comment]
Still doesn't work, same call now gives this:

```
Error: Bad Request
    at throwFailedRequestError (file:///app/node_modules/@gitbeaker/rest/dist/index.mjs:56:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultRequestHandler (file:///app/node_modules/@gitbeaker/rest/dist/index.mjs:90:7)
    at async file:///app/node_modules/@gitbeaker/core/dist/index.mjs:132:22
    at async deployStaging (file:///app/dist/deployment/staging.js:54:28)
    at async InstanceService.deployNewInstance (file:///app/dist/services/InstanceService.js:105:17)
```

**Comment by d-fischer** [comment]
I worked around it this way:

```js
gitlab.PipelineTriggerTokens.trigger(
      DEPLOYER_PROJECT_ID,
      'master',
      process.env.DEPLOYER_TRIGGER_TOKEN!,
      Object.fromEntries(Object.entries(variables).map(([key, value]) => [`variables[${key}]`, value])),
    );
```

Still should probably be fixed.

**Comment by jdalrymple** [comment]
Weird, I definitely have a test for those types of serialization in the codebase. Maybe i missed a usecase? Ill double check it today and follow up! Sorry for the hassle.

**Comment by jdalrymple** [comment]
Should be good now! Tell me if you have any more problems!
