### ISSUE TITLE
Projects.upload() always says "The provided content-type 'text/plain' is not supported."

### ISSUE THREAD

**Issue by mbrammer** [jdalrymple/gitbeaker#3256]
**Description**

- Node.js version: 18.16.0
- Gitbeaker version: 38.3.0
- Gitbeaker release (cli, node, browser, core, requester-utils): @gitbeaker/rest

When uploading a file via `Projects.upload()`, I always see this error:
```
{
  description: `"The provided content-type 'text/plain' is not supported."`,
  response: Response {
    size: 0,
    timeout: 300000,
    [Symbol(Body internals)]: [Object],
    [Symbol(Response internals)]: [Object]
  }
}
```
I am passing a base64 image like this:
```
const img = 'data:image/png;base64,[...]'; // also tried without "data:image/png;base64,"
const uploadResponse = await this.gitlab.Projects.upload(
  GITLAB_PROJECTID,
  {
    content: new Blob([img], { type: 'image/png' }),
    filename: 'xyz.png',
  },
);
```
type is set to `image/png`. So why is the API saying I'm using `text/plain`, which seems to be not supported?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by mbrammer** [comment]
Same issue with reading a file via `fs`...
```
const filename = 'screenshot_1683884358617.png';
const img = fs.readFileSync(filename);
const uploadResponse = await this.gitlab.Projects.upload(
  GITLAB_PROJECTID,
  {
    content: new Blob([img], { type: 'image/png' }),
    filename,
  },
);
```

**Comment by jdalrymple** [comment]
Investigating!

**Comment by jdalrymple** [comment]
Just to be clear, this form of upload is for comments/mrs/issues etc. Ive updated the API to make it clearer, now its called uploadForReference. 

To upload a file to the repo, use repositoryFiles.create

I will double check this bug over the weekend and follow up to make sure though!

**Comment by mbrammer** [comment]
Thanks for investigation. I tried uploading to an issue :)

**Comment by jdalrymple** [comment]
This worked without an error:

```js
const file = new Blob([await FS.readFile('./Untitled.png')], { type: 'image/png' });

const api = new Gitlab({
  token: token',
})

api.Projects.uploadForReference(projectId, { content: file,  filename: 'Random.png' })
.then(r => {
  console.log(r)
})
```

**Comment by jdalrymple** [comment]
Closing for now, Ill reopen if youre still running into issues.

**Comment by mbrammer** [comment]
Hey Justin,

I have been on vacation, so I just read your comments.
So I just tested this:
```
fs.readFile('screenshot.png', (error, data) => {
  const file = new Blob([data], { type: 'image/png' });

  this.gitlab.Projects.uploadForReference(projectId, { content: file,  filename: 'Random.png' })
  .then(r => {
    console.log(r);
  });
});
```
with `@gitbeaker/rest: 38.9.0` and I still get an error.
```
[...]/node_modules/@gitbeaker/rest/dist/index.js:78
  throw new Error(response.statusText, {
        ^
Error: Unsupported Media Type
    at throwFailedRequestError ([...]/node_modules/@gitbeaker/rest/dist/index.js:78:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultRequestHandler ([...]/node_modules/@gitbeaker/rest/dist/index.js:110:7)
    at [...]/node_modules/@gitbeaker/core/dist/index.js:138:22
```

**Comment by jdalrymple** [comment]
Can you put together a sample project so i can recreate the error?

**Comment by mbrammer** [comment]
> Can you put together a sample project so i can recreate the error?

Sure

**Comment by mbrammer** [comment]
Okay, I found the issue.  
While duplicating the project and stripping out everything which is not necessary for you to test it, I figured out it's working with the minimal version. So I reverse-engineered and found this inside a module:
```
declare var global: any;
global.fetch = fetch;
```
I think it was an old relict and I removed it. Now it's working 🙏 
Sorry for the circumstances 😞
