### ISSUE TITLE
EditMergeRequestOptions is missing assigneeIds

### ISSUE THREAD

**Issue by smsalisbury** [jdalrymple/gitbeaker#3261]
**Description**

- Node.js version: v18.12.1
- Gitbeaker version: 38.5.0
- Gitbeaker release (cli, node, browser, core, requester-utils): core
- OS & version: Ubuntu 22.04

The type for editing merge requests is missing `assigneeIds` (plural), which is available to Premium and Ultimate users.

https://docs.gitlab.com/ee/api/merge_requests.html#update-mr

**Steps to reproduce**

**Expected behaviour**

**Actual behaviour**

**Possible fixes**

I'll propose a PR to add the missing field.

**Checklist**
- [ ] I have checked that this is not a duplicate issue.
- [ ] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`38.6.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/38.6.0) :rocket:
