### ISSUE TITLE
Add a `wait_for_completion` option

### ISSUE THREAD

**Issue by trevor-vaughan** [jdalrymple/gitbeaker#3266]
**Description**

Actions performed via the GitLab API are not synchronous by default.

While this is fine 90% of the time, occasionally you end up with a workflow where you need to make sure that something has completed prior to moving on to the next step.

For example, if you want to create an issue and give it label `X` but `X` needs to live at a higher level (can't be auto-created) then the order must be:

1. Create label `X`
2. Wait for label `X` to actually exist
    * The response does indicate that one has been created but I'm discovering that there appear to be occasional race conditions where the response has been provided but the actual object has not been created
4. Create the issue with the mentioned label

**Proposal**

I would like a `wait_for_completion` boolean to be added along with a timeout that would alleviate the need for adding independent logic to make sure that the item in the response was actually generated before moving on.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
For the response to occur, generally speaking, the entity must exist. If it doesn't, it would most likely be an error within the order of operations within the Gitlab API logic.  Do you have any repeatable examples where this isn't the case?

**Comment by trevor-vaughan** [comment]
@jdalrymple The only place that I've seen it relatively consistently is when creating labels.

I've had a couple of cases where I've said to create labels and then immediately tried to use them. In this case, I sometimes get an error saying that the label does not exist. Try again after a small sleep and everything is good.

**Comment by trevor-vaughan** [comment]
Yeah, that's fair. For the moment, I have check code in place but it doesn't make sense to add things here to work around upstream issues.
