### ISSUE TITLE
Missing Property Empty Repo

### ISSUE THREAD

**Issue by henrysachs** [jdalrymple/gitbeaker#3269]
**Description**

- Node.js version: 18
- Gitbeaker version: 38.7.0
- Gitbeaker release (cli, node, browser, core, requester-utils): rest
- OS & version MacOs

**Steps to reproduce**

Use the expandedProjectSchema Type and search for empty_repo

**Expected behaviour**

the property is usable in typescript

**Actual behaviour**

property has type unknown

**Possible fixes**

make it an optional property if not all gitlab versions are supporting it.

**Checklist**
- [ x ] I have checked that this is not a duplicate issue.
- [ x ] I have read the documentation.

**Comment by jdalrymple** [comment]
Ill double check the project schema!

**Comment by henrysachs** [comment]
thanks a lot I'm currently migrating from gitbeaker/node to gitbeaker/rest 

Developer Experience is greatly increased anyway so thanks a lot for this

**Comment by henrysachs** [comment]
I also noticed that the ExpandedUserSchema is missing the `is_admin` property. Should i create a separate issue for that?

**Comment by jdalrymple** [comment]
Nah, ill fix it one time. If you notice any others, feel free to add to this issue

**Comment by jdalrymple** [comment]
Will be released by EoD

**Comment by henrysachs** [comment]
Awesome! Thank you so much I'll take a look into this tomorrow.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`38.8.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/38.8.0) :rocket:
