### ISSUE TITLE
Can the supported node version be pulled back to 16.18+ with updated docs?

### ISSUE THREAD

**Issue by trevor-vaughan** [jdalrymple/gitbeaker#3274]
**Description**

The latest version of the library at this time works fine with Node 16.18+ as long as you:
  * Install `node-fetch`
  * Set the following in your entry point:
    * `global.fetch = require('node-fetch')`

I know that this isn't technically "core support" but I was wondering if the supported version could be bumped back along with adding an update to the README with the items above.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
I hear your point, but i really dont want to push back the supported versions beyond the 18lts. With 16's end of life coming up in 5 ish months and v20 out already, it doesnt make the most sense. I can add this info to the FAQ though, which could provide temporary information for anyone who wants to use this.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`38.9.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/38.9.0) :rocket:
