### ISSUE TITLE
Incorrect Type definitions for `MergeRequests.edit`

### ISSUE THREAD

**Issue by Xiot** [jdalrymple/gitbeaker#3284]
**Description**

- Node.js version: 16.19.1
- Gitbeaker version: 38.9.0
- Gitbeaker release (cli, node, browser, core, requester-utils): core
- OS & version: osx

**Steps to reproduce**

Incorrect type definitions

**Expected behaviour**

`EditMergeRequestOptions.targetBranch: string`
`MergeRequests.edit` returns a `Promise<GitlabAPIResponse<ExpandedMergeRequestSchema, C, E, void>>`

**Actual behaviour**

`EditMergeRequestOptions.targetBranch` is currently typed as a `number`.
`MergeRequests.edit` is currently returning a `Promise<ExpandedPipelineSchema>>` however the api response itself should be a `ExpandedMergeRequestSchema`

**Possible fixes**

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`38.10.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/38.10.0) :rocket:
