### ISSUE TITLE
Incorrect/missing null types for MergeRequestSchema and ExpandedMergeRequestSchema

### ISSUE THREAD

**Issue by ravewill** [jdalrymple/gitbeaker#3287]
**Description**

- Node.js version: N/A
- Gitbeaker version: 38.9.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: N/A

I encountered a null reference error today when using this library. The property on an object implementing ExpandedMergeRequestSchema was null, and Typescript hadn't hinted that it could be null. Unfortunately GitLab's API docs don't tell you what values could be null, so I did a GET request to the REST endpoint of my hosted GitLab server (15.11.3) and updated these type definitions on null JSON values I got back.

**Steps to reproduce**
N/A

**Expected behaviour**
N/A

**Actual behaviour**
N/A

**Possible fixes**
1. Continue marking fields as optional. This could be confusing because they are defined, they're just not null
2. Mark the fields as nullable (like I have in #3286)

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`38.10.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/38.10.0) :rocket:
