### ISSUE TITLE
Incorrect types for creating protected repository branches

### ISSUE THREAD

**Issue by hnrch02** [jdalrymple/gitbeaker#3299]
**Description**

- Gitbeaker version: 38.12.1
- Gitbeaker release (cli, node, browser, core, requester-utils): rest

The access levels in `CreateProtectedBranchOptions` are `ProtectedBranchAccessLevel`:

https://github.com/jdalrymple/gitbeaker/blob/3f08cb83dfe66c77782324adfb5da46933f081f8/packages/core/src/resources/ProtectedBranches.ts#L34-L36

But they should be integers according to the API docs: https://docs.gitlab.com/16.0/ee/api/protected_branches.html#protect-repository-branches

**Possible fixes**

Change the type of `mergeAccessLevel`, `pushAccessLevel`, `unprotectAccessLevel` in `CreateProtectedBranchOptions` to be `number`.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.0.0) :rocket:
