### ISSUE TITLE
Missing property "is_admin" for Users

### ISSUE THREAD

**Issue by ozeebee** [jdalrymple/gitbeaker#3303]
**Description**

- Node.js version: 18
- Gitbeaker version: 38.12.1
- Gitbeaker release (cli, node, browser, core, requester-utils): rest
- OS & version: macOS

**Steps to reproduce**

Search for Users; the ExpandedUserSchema is missing the `is_admin` property.

**Expected behaviour**

User object should have the `is_admin` flag.

**Actual behaviour**

This flag is missing.

**Possible fixes**

make it an optional property if not all gitlab versions are supporting it.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Yea i missed it here #3269, ill fix this ASAP

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.0.0) :rocket:
