### ISSUE TITLE
Defer token resolution for when making the call

### ISSUE THREAD

**Issue by theodorvulcan** [jdalrymple/gitbeaker#3310]
**Description**

I am trying to write a service with the use of your library. Because it's running at all times I can't hardcode the API token when I first start it up, as we might very well decide to regenerate it for security purposes. Thus I basically want to resolve the API token whenever I am about to send a request.
I am basically looking at how I could pass a callback for a tokenProvider rather than the actual token into the Gitlab() constructor. 
There isn't much documentation around this project and kudos for how extendable the code is but that makes it really tough to read 😅 
Because of the token checks in the BaseResource constructor I would probably need to send a dummy value just to fool it and then maybe play around with sending a requesterFn that would resolve the token and override the value in the headers before sending it down. 
I do kind of feel a bit dirty to do it this way though 😂 and I was curios if you would have any ideas on how maybe to do it in a cleaner way or maybe if you think it's sensible to switch/extend the constructor from accepting token string values to providers. Performance wise it shouldn't impact anyone as a provider like () => "<key_value>" is the same as passing the string down.

Let me know what you think 😁 

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Why not just reinit the library during the call? 

We could also add a feature that takes in a tokenProvider or something of the sort like you mentioned instead of the many options in the constructor, such that you could fetch a new token or what ever during the call sequence? Wouldnt be a hard thing to add and wouldnt break supported options.

**Comment by theodorvulcan** [comment]
You want me to contribute with a MR on this? or you want to pick it prioritise it on your own time and pick it up? I would be up to contribute if you're too busy 😄

**Comment by jdalrymple** [comment]
I have it written, i just havent had the time to finish testing it up. Ill finish it up over the weekend!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.2.0) :rocket:

**Comment by theodorvulcan** [comment]
Thanks a lot for discussion and quick action! 👏

**Comment by adussarps** [comment]
This feature is really nice !
@theodorvulcan Could you add an example on how do you use it with the Oauth flow ? 🙏
