### ISSUE TITLE
Missing type PipelineTriggerToken.owner

### ISSUE THREAD

**Issue by ArnaudTA** [jdalrymple/gitbeaker#3316]
**Description**

missing type for PipelineTriggerToken
https://github.com/jdalrymple/gitbeaker/blob/b6fa44700d41048369f843b896957de0056b8dd5/packages/core/src/resources/PipelineTriggerTokens.ts#LL19C12-L19C12
Idk why you set owner at null but when i do some call it is more likely an `Omit<UserSchema, 'created_at'>

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
haha i also dont know why i did such a thing. Probs a typo! Fixing now.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.2.0) :rocket:
