### ISSUE TITLE
Issue with `fetch` introduced in 39.2.0

### ISSUE THREAD

**Issue by trevor-vaughan** [jdalrymple/gitbeaker#3329]
**Description**

- Node.js version: 18.16.1
- Gitbeaker version: 39.2.0
- Gitbeaker release (cli, node, browser, core, requester-utils): rest
- OS & version: Various Linux

Code that worked correctly in 39.1.0 is now throwing the following error:

```bash
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (./node_modules/node-fetch/lib/index.js:1327:9)
    at ./node_modules/node-fetch/lib/index.js:1454:19
    at new Promise (<anonymous>)
    at fetch (./node_modules/node-fetch/lib/index.js:1451:9)
    at defaultRequestHandler (./node_modules/@gitbeaker/rest/dist/index.js:103:28)
```

**Steps to reproduce**

Unfortunately, I'm not entirely sure.

@jdalrymple If you recall, I had to fall back to using `node-fetch` to work around random issues with the inbuilt `fetch` method in Node 18.

Do you think that the updates in 39.2.0 would have resolved these? There doesn't seem to be a great way to fully test this since it occurs randomly.

**Expected behaviour**

Fetch things

**Actual behaviour**

Throw an error

**Possible fixes**

Removing `node-fetch` usage appears to work but I worry that I'm going to hit the previous issues. Preserving compatibility with `node-fetch` would be nice in case issues have to be worked around again.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Could you share the request used when this error occurs? The error cause should contain the original request now for debugging purposes

**Comment by trevor-vaughan** [comment]
I think I've got it figured out.

The `Request` object from core Node is not compatible with the one from `node-fetch` and the breaking change appears to be in d5d5879557456e0e868a2aaaf52b5d2ac209d38c where the `Request` object creation was moved into the `for` loop (no idea why that would make a difference).

The full `fetch` instability workaround is now:

```javascript
const semver = require('semver')
// Node 18 has instability in the inbuilt `fetch` library :-(
if ( semver.lt(process.version, '20.0.0') ) {
  global.fetch = require('node-fetch')
  global.Request = fetch.Request
  global.Response = fetch.Response
  global.Headers = fetch.Headers
  global.Body = fetch.Body
}
```

**Comment by jdalrymple** [comment]
Well thats quite the work around. Id figure they would use the native Request/Response etc objects but i guess not

**Comment by trevor-vaughan** [comment]
The `node-fetch` team definitely wants folks to stop using it and use the native stuff moving forward.

Maybe after 18.X stops being crazy :-D.
