### ISSUE TITLE
Add support for rate limiting requests

### ISSUE THREAD

**Issue by trevor-vaughan** [jdalrymple/gitbeaker#3330]
**Description**

@jdalrymple In a past issue, you asked me if I was having trouble with timeouts. Well, at that time (pointing to GitLab 15), no.

Unfortunately, hitting a different GitLab 16 server is triggering timeouts after between 4 and 7 pages of results.

Do you know of anything I can dig into and/or is there a backoff mechanism somewhere?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Hey! Can you throw together a test i could run to validate this? I've been testing against Gitlab 16 without issues, so maybe I'm missing a test case somewhere?

We do employ a back off mech here: https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/src/Requester.ts#L130

**Comment by trevor-vaughan** [comment]
Unfortunately, it's an internal set of servers so not really.

🤔 Do you happen to have what would be returned from GitLab itself for a Timeout or back off request? I suppose that it's possible that it's a proxy or something in the way but very difficult to figure out.

**Comment by jdalrymple** [comment]
If youre getting this:  `Could not successfully complete this request due to Error 429. Check the applicable rate limits for this endpoint.` Then its a too many requests error, but if youre getting somehting like "headers timeout" or "body timeout" then its related to fetch specifically

**Comment by jdalrymple** [comment]
Can you share the exact error youre receiving?

**Comment by trevor-vaughan** [comment]
Yeah, I was just re-running to hit the timeout again.

Interesting, it's an `ETIMEOUT` socket error.

Would this be affected by the `requestTimeout` configuration option?

**Comment by jdalrymple** [comment]
Hmm maybe, though i catch that specific error and return something nicer. Easiest way to test that would be to change the queryTimeout to something > 300000

**Comment by trevor-vaughan** [comment]
Still prodding without a ton of luck so far. It's definitely starting to look like a proxy rate limiter where I may need a hefty cool-down period.

The weird thing is that I'm losing the stack trace through `@gitbeaker` but there's no other place that I'm calling a web request that I know of.

**Comment by jdalrymple** [comment]
That could be the cause, but hard to know for sure.

What is the stacktrace you are currently receiving ? It should point you to this location: https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/src/Requester.ts#L86

**Comment by trevor-vaughan** [comment]
Added some debug code directly into `@gitbeaker/rest` and it looks like I'm definitely hitting [packages/rest/src/Requester.ts#L123](https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/src/Requester.ts#L123).

I guess that the lack of stack trace makes sense (sort of) since it's an Anonymous function floating around in the ether.

I may not be reading things correctly but I'm not 100% sure how that code is going to handle the retry without a split `try/catch`.

**Comment by trevor-vaughan** [comment]
The error is coming out of `ClientRequest.<anonymous>` 🤷

**Comment by trevor-vaughan** [comment]
🤔 @jdalrymple Is there a way for me to tell `@gitbeaker` to internally rate-limit? I feel like I'm hitting an upstream proxy or something and smacking into a hard limit.

If I could tell the library to not send more than `x/second` that might solve things.

**Comment by jdalrymple** [comment]
There is a catch here: https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/src/Requester.ts#L118

So the error occurring isnt a failed http status, its a full on fetch error thats occurring. In which case i return the error completely (Line 123), if its not a timeout error for debugging purposes. 

As of right now, there is no way to rate limit requests beyond the small backoff that exists if the response is a "too many requests" status. It could be a useful feature though obviously.

**Comment by jdalrymple** [comment]
Quickest thing i could think of rn is increasing that delay time, though its only a bandaid solution

**Comment by trevor-vaughan** [comment]
Ahh...I see, you're only delaying in the case of a valid response not "something horribad and unexpected happened".

Changing the timeout didn't seem to help so I'll stick some `sleep` calls 🤢 in my code.

I guess this has turned into a feature request for a message based rate limiter :-D.

As always, appreciate the help.

**Comment by trevor-vaughan** [comment]
That seems reasonable as long as we can shove in our rate  options. Bit of a shame to drag in another dep.

In theory, it could be done with a basic message counter since you funnel everything into a single entry point (I think).

**Comment by trevor-vaughan** [comment]
@jdalrymple 🤔 Would you be OK with adding a HUGE backoff option for unknown errors? That would allow for a temporary workaround.

I did a *very quick and dirty* hackjob that certainly works around the issue but it's a heck of a sledgehammer.

```javascript
async function defaultRequestHandler(endpoint, options) {
    const retryCodes = [429, 502];
    const maxRetries = 10; 
    const { prefixUrl, asStream, searchParams, ...opts } = options || {}; 
    let baseUrl;
    if (prefixUrl)
      baseUrl = prefixUrl.endsWith("/") ? prefixUrl : `${prefixUrl}/`;
    const url = new URL(endpoint, baseUrl);
    url.search = searchParams || ""; 
    const mode = getConditionalMode(endpoint);
    for (let i = 0; i < maxRetries; i += 1) {
      const request = new Request(url, { ...opts, mode }); 
      let response = null
      try {
        response = await fetch(request).catch((e) => {
          if (e.name === "TimeoutError" || e.name === "AbortError") {
            throw new Error("Query timeout was reached");
          }   
  
          throw e
        }); 
      }   
      catch(e) {
        if (e.toString() == 'Query timeout was reached') throw e
  
        if (response == null) {
          console.log("Unexpected error " + e.toString());
          await delay(30*1000);
        }   
        else {
          if (response.ok)
            return parseResponse(response, asStream);
          if (!retryCodes.includes(response.status))
            await throwFailedRequestError(request, response);
          const ldelay = (2 ** i * 0.25);
          console.log('Delaying for ' + ldelay);
          await delay(ldelay);
        }   
  
        continue;
      }   
    }
    throw new Error(
      `Could not successfully complete this request due to Error 429. Check the applicable rate limits for this endpoint.`
    );  
  }
```

This was hacked straight in the `node_modules` directory so not worth anything at all but wanted to toss the idea out there.

**Comment by trevor-vaughan** [comment]
Yeah, the approach above seems to work just fine (well, the edited version anyway).

Moving the `delay` in the `catch` to mirror the other delay pattern but using `( i * 2000 )` seems to hit a reasonable midpoint.

**Comment by jdalrymple** [comment]
The only issue with that is that your delaying an unknown error. This error could be related to the library or fetch itself and not something that just requires more time right?

**Comment by jdalrymple** [comment]
It does look like properly adding rate limiting would be a good idea instead of my simple backoff logic. This could also support some form of configuration which would be nice.

**Comment by trevor-vaughan** [comment]
That certainly works for me! Having it be an option that's entered at initial object creation time would be perfect.

Unfortunately, `bottleneck` seems to be a dead project at this point looking at the git repo.

Maybe `@fastify/rate-limit` instead?

**Comment by trevor-vaughan** [comment]
Ah, nope, that's server side. I'm having trouble finding a lib that doesn't seem abandoned :-/

**Comment by trevor-vaughan** [comment]
[fetch-rate-limit-util](https://www.npmjs.com/package/fetch-rate-limit-util) seems reasonably alive

**Comment by trevor-vaughan** [comment]
The Vercel team also has [async-sema](https://github.com/vercel/async-sema) which should do the job and (hopefully) be reasonably supported since they use it in their own products.

**Comment by jdalrymple** [comment]
> [fetch-rate-limit-util](https://www.npmjs.com/package/fetch-rate-limit-util) seems reasonably alive

but also super fresh haha

**Comment by jdalrymple** [comment]
Looks like async-sema might be the best way to go here. The next question is what should the default rate limit be? According to the docs different entities have completely different [limits](https://docs.gitlab.com/ee/security/rate_limits.html). I could make it REALLY configurable i suppose to handle each case but...seems like overkill maybe haha

**Comment by trevor-vaughan** [comment]
🤔 I would probably go with a blanket approach for the first cut but maybe leave room for folks to specify endpoints and set limits based on the endpoint?

I don't think that would be too much more work since it should just be a tracking object with the endpoint as the key.

**Comment by trevor-vaughan** [comment]
Actually, if this gets in, it might be great to be able to dump a summary of the connections and rates for devs to be able to optimize the heaviest endpoint usage.

**Comment by jdalrymple** [comment]
> Actually, if this gets in, it might be great to be able to dump a summary of the connections and rates for devs to be able to optimize the heaviest endpoint usage.

Can you expand on this?

**Comment by trevor-vaughan** [comment]
In theory, each time the rate limiting is imposed, it could record a summary of the connection counts.

That said, I haven't dug into the library so I have no idea how difficult this would be to implement.

**Comment by jdalrymple** [comment]
Yea that would be some useful info. Though, looking at the library, it doesnt seem to provide a way to access the status like that, at least not with the RateLimit function.

I have a sample implementation of the feature at the moment, basically uses globs to set additional rate limits to matching endpoints, with a default value for everything that doesnt match:

```
const api = new Projects({
  token: 1234
  rateLimits: {
   '*': 30,
   'projects/import/*': 40
  }
})
```

Now that i look at it, I should probably have a way to specify the particular method it applies to. hmm..

**Comment by trevor-vaughan** [comment]
Personally, I prefer the nested object version. Leaves room for fiddling in the future.

The globbing is a great touch for fallbacks.

**Comment by jdalrymple** [comment]
First crack at the functionality. Give the logic a look over to see if i missed anything of importance

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.19.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.19.0) :rocket:

**Comment by trevor-vaughan** [comment]
FYI, this appears to work well, thanks!

**Comment by jdalrymple** [comment]
Only caveat is some issues with SPAs #3427 :confused:

**Comment by jdalrymple** [comment]
The lack of maintencne on the async-sema repo is causing some trouble here. Any suggestions on possible replacements @trevor-vaughan ? I've done a quick search but havent found any of the forks to be released with the latest PRs included and havent found similar libraries that would be a drop in replacement :( 

I've posted on the discussions and on some of those forked repos that are published about merging in those changes, but no resposes thus far

**Comment by jdalrymple** [comment]
Its looking unlikely to happen. Now its whether i fork the repo or spend more time trying to find a maintained alternative

**Comment by trevor-vaughan** [comment]
@jdalrymple [express-rate-limit](https://www.npmjs.com/package/express-rate-limit) seems alive and with no dependencies.

**Comment by trevor-vaughan** [comment]
[node-rate-limiter-flexible](https://www.npmjs.com/package/rate-limiter-flexible) may also work using the native DB.
