### ISSUE TITLE
Migration guide from gitbeaker/node ?

### ISSUE THREAD

**Issue by witek1902** [jdalrymple/gitbeaker#3340]
**Description**

Is there any migration instruction from `gitbeaker/node`?

I'm looking for how to replace the old classes `Types.GroupSchema[]' etc, example:

```
import { Gitlab } from "@gitbeaker/rest";

const GitlabApi = new Gitlab({
      host: process.env.GITLAB_HOST,
      token: process.env.ACCESS_TOKEN,
});

const subgroups = (await GitlabApi.Groups.subgroups(
  1234
)) as unknown as Types.GroupSchema[];

const projects = (await GitlabApi.Groups.projects(groupId, {
  perPage: 500,
  archived: false
})) as Types.ProjectSchema[];
```

How should I do this using the new library?

**Checklist**
- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
This should work!:

```js
import { Gitlab } from "@gitbeaker/rest";

const GitlabApi = new Gitlab({
      host: process.env.GITLAB_HOST,
      token: process.env.ACCESS_TOKEN,
});

const subgroups = await GitlabApi.Groups.allSubgroups(1234)

const projects = await GitlabApi.Groups.allProjects(groupId, {
  archived: false
})
```

**Comment by witek1902** [comment]
Thanks @jdalrymple!

One more question.
In `gitbeaker/node` I could import `import { Types } from "@gitbeaker/node";` and had all classes available (TypeScript). 
Can I do the same here?

**Comment by jdalrymple** [comment]
The types are exported directly now, so you can do:

```typescript
import type {ProjectSchema} from '@gitbeaker/rest'
```
