### ISSUE TITLE
Bad Request when downloading Job Artifact by Ref and Job Name

### ISSUE THREAD

**Issue by michael-smt** [jdalrymple/gitbeaker#3345]
**Description**

- Node.js version: 18
- Gitbeaker version: 39.5.1
- Gitbeaker release (cli, node, browser, core, requester-utils): rest
- OS & version: node:lts container from dockerhub

Downloading a artifacts archive ([GitLab API Docs](https://docs.gitlab.com/ee/api/job_artifacts.html#download-the-artifacts-archive)) via `JobArtifacts.downloadArchive()` fails due to query string getting lost.

**Steps to reproduce**

Try to download the artifacts archive of the latest successful pipeline of the given reference name and job:
```
import { Gitlab } from '@gitbeaker/rest';

const api = new Gitlab({
  host: 'http://example.com',
  token: 'personaltoken',
});

api.JobArtifacts.downloadArchive('myProject', { ref: 'myRef', job: 'myJob' });
```

**Expected behaviour**

Request is sent to `/projects/myProject/jobs/artifacts/myRef/download?job=myJob`

Artifact is returned.

**Actual behaviour**

Request is sent to `/projects/myProject/jobs/artifacts/myRef/download` (note: missing query parameter)

Bad request response from GitLab with cause "job is missing".

**Possible fixes**

Extend the query param instead of resetting it in [`defaultRequestHandler`](
https://github.com/jdalrymple/gitbeaker/blob/112aed2758539a452defd9d03c0d399c43163087/packages/rest/src/Requester.ts#L110C1-L110C35).

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
So i managed to sort it out, but i've been running into difficulty testing, particularly this [issue](https://gitlab.com/gitlab-org/gitlab/-/issues/216055). Ill put out a canary for you to double check everything is good on your end before deployment

**Comment by jdalrymple** [comment]
ugh, probably smh.
