### ISSUE TITLE
`ReleaseSchema.description` should be optional

### ISSUE THREAD

**Issue by privet-kitty** [jdalrymple/gitbeaker#3350]
Hi. Thank you for maintaining this awesome SDK!

**Description**

- Node.js version: any
- Gitbeaker version: 35.1.0
- Gitbeaker release (cli, node, browser, core, requester-utils): core
- OS & version: any

Currently `description` field of `ReleaseSchema` [doesn't allow null](https://github.com/jdalrymple/gitbeaker/blob/873a58b5c2b3849006484928990a01eb6dd457d3/packages/core/src/resources/ProjectReleases.ts#L37), while it's allowed in [GitLab API](https://docs.gitlab.com/16.1/ee/api/releases/#create-a-release). Actually there exists a release out there that contains null in `description` field, which you can get from [tezos](https://gitlab.com/tezos/tezos), for example:

```bash
curl --header "PRIVATE-TOKEN: <your token>" https://gitlab.com/api/v4/projects/3836952/releases/v17.1 | jq .description
# -> null
```

This difference sometimes causes troubles in a software that relies on gitbeaker. My case is [node-gitlab-2-github](https://github.com/piceaTech/node-gitlab-2-github), a migration tool from GitLab to GitHub. This tool trusts gitbeaker's typing, fetches a release from GitLab, and moves it to GitHub, while it incorrectly assumes that `description` be always a string and throws an exception on a GitHub-side stack.

**Steps to reproduce**

**Expected behaviour**

**Actual behaviour**

**Possible fixes**

`descpription` field should be optional.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
  - [found no issues containing ReleaseSchema](https://github.com/search?q=repo%3Ajdalrymple%2Fgitbeaker+ReleaseSchema&type=issues)
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.7.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.7.0) :rocket:
