### ISSUE TITLE
CreateUserOptions['projectsLimit'] should be an integer ?

### ISSUE THREAD

**Issue by clairenollet** [jdalrymple/gitbeaker#3353]
## 

`projectsLimit?: boolean;` seen in `/src/resources/Users.ts - export type CreateUserOptions` - cf [line](https://github.com/jdalrymple/gitbeaker/blob/2e51cfc78bbe14e990e907efa93505ba7f43cf6a/packages/core/src/resources/Users.ts#L164C3-L164C3)

From [Gitlab doc #user-creation](https://docs.gitlab.com/ee/api/users.html#user-creation) - `projects_limit: Number of projects user can create`

**Comment by jdalrymple** [comment]
Yea it should be, ill change that!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.8.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.8.0) :rocket:
