### ISSUE TITLE
Invalid projects/:id/merge_requests api call for gitlab 16

### ISSUE THREAD

**Issue by psznm** [jdalrymple/gitbeaker#3356]
**Description**

- Node.js version: 18
- Gitbeaker version: 39.8.0
- Gitbeaker release: node

I am getting internal server error after updating to Gitlab 16. After some digging where should I report the bug, i found it is issue of gitbeaker because it calls api call in a way that is not correct for Gitlab 16
```
const api = new Gitlab({
    host,
    token,
    requesterFn: () => ({get: (url) => console.log(url)}),
    rejectUnauthorized: false,
});

--- some omitted code ---

    const mrInfos = await Promise.all(openMergeRequestsParsed.map(async ({ iid }) => {
        return api.MergeRequests.show(projectId, iid);
    }));


// console.log displays "projects/1/merge_requests/4337"

```

After checking gitlab API at https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests, I can see that correct way to query is to iid as query parameter.

**Steps to reproduce**

```
# FAIL ( using same url as gitbeaker uses )
curl --insecure "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/merge_requests/4337?private_token=$PRIVATE_TOKEN"
# SUCCESS
curl --insecure "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/merge_requests?private_token=$PRIVATE_TOKEN&iids[]=4337"
```

**Expected behaviour**

Correctly formatted api call to be called.

**Actual behaviour**

Incorrect api call is called.

**Possible fixes**

Fix for Gitlab 16 should be clear from steps to reproduce. Note that in Gitlab 15 both api calls work, but they do have different response schema.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
I may be missing something. 

This call:

```js
api.MergeRequests.show(projectId, iid);
```

Retreives a specific merge request. 

This call:

```js
api.MergeRequests.all(projectId);
```
Retreives all the merge requests for a particular project.

**Comment by psznm** [comment]
I see, I thought that the singular merge request api call stopped existing, but it works just fine on public gitlab. I guess it must be  gitlab issue after all. Even specific to our self hosted instance, since I haven't found any reported issues on gitlab... So no problem here, sorry to bother you.

**Comment by jdalrymple** [comment]
Tis no problem at all, but It should work. Do you mind sharing the exact error youre receiving when making a request for a singular merge request?
