### ISSUE TITLE
MergeRequest allDiffs and allCommits missing pagination options

### ISSUE THREAD

**Issue by dejan-crocoder** [jdalrymple/gitbeaker#3383]
**Description**

the MergeRequest resource operations allDiffs and allCommits do not support pagination parameters in the api, and always auto-extract all pages instead of allowing control over pagination.

The following code works but need to use typedef casting:
```typescript
api.MergeRequests.allDiffs(0, 0, {
  showExpanded: true,
  page: 1,
  perPage: 10
} as Sudo & ShowExpanded<true>).then((res) => {
  console.log('retrieved', res.data.length, 'diffs');
  if ('paginationInfo' in res) console.log(res.paginationInfo);
})
```

**Possible solutions**

I'm not versed in your codebase but I assume you just need to extend the options argument with the ```PaginationRequestOptions<P>``` type and add the template argument ```P extends PaginationType = 'offset'``` to the function signature for the allDiffs and allCommits operations

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [ ] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.12.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.12.0) :rocket:
