### ISSUE TITLE
Retrieve a single merge request

### ISSUE THREAD

**Issue by demedos** [jdalrymple/gitbeaker#3392]
**Description**
Right now, the library doesn't have a way to fetch just one merge request using the provided API. Consumers have to do a search using the .all method and give it a specific ID. It'd be really handy if there was a simple MergeRequests.get(iid) API that lets you directly get info about just one merge request.

[Get Single Merge Request API](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr)

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
It does exist but its under a different name. All the entity APIs have a way to get a single entity using the .show method :D
