### ISSUE TITLE
Missing enum for `DiscussionNoteSchema["type"]`

### ISSUE THREAD

**Issue by NatoBoram** [jdalrymple/gitbeaker#3396]
**Description**

The `DiscussionNoteSchema` type has `type?: string;`, but it's not really *any* string that does there, there's a specific set of string we can obtain.

Being able to compare this with `"DiffNote" | "DiscussionNote"` would allow us to determine if a `DiscussionNoteSchema` is actually a `MergeRequestDiscussionNoteSchema` instead and obtain that discussion's position.

**Possible solutions**

Add missing enum and types

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.13.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.13.0) :rocket:
