### ISSUE TITLE
`straight` should be `boolean` or `"true" | "false"` instead of `string`

### ISSUE THREAD

**Issue by NatoBoram** [jdalrymple/gitbeaker#3399]
**Description**

Looking at this method, it appears `straight` is `string`

https://github.com/jdalrymple/gitbeaker/blob/2481b154629477d1497be3abfb78b6b36635b8e0/packages/core/src/resources/Repositories.ts#L102-L117

If I make a comparison with this in mind

```js
await fetch(
	"/api/v4/projects/13718909/repository/compare?from=997a91b00cd3974ab4aae8275be85e98c7656875&to=f7a4fc34fe6f63ab2cd6b91cc12ddb83ae8d410a&straight=string",
).then(r => r.json())
// { "error": "straight is invalid" }
```

we see that `straight` doesn't actually accept a `string`. According to the docs, it should be a `boolean`.

https://docs.gitlab.com/ee/api/repositories.html#compare-branches-tags-or-commits

**Possible solutions**

Update the types to match the docs

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.13.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.13.0) :rocket:
