### ISSUE TITLE
Wrong type for `noteable_type`

### ISSUE THREAD

**Issue by NatoBoram** [jdalrymple/gitbeaker#3405]
**Description**

In the [discussion api docs](https://docs.gitlab.com/ee/api/discussions.html), we see that `noteable_type` can be `"Issue"`, `"Snippet"`, `"Epic"`, `"Commit"` and `"Merge request"`. However, they are defined as `string` in this package, which is wrong.

https://github.com/jdalrymple/gitbeaker/blob/ce3d4d462f49092dc58ffacd6f9e8436b7d759c7/packages/core/src/resources/IssueNotes.ts#L12-L20

https://github.com/jdalrymple/gitbeaker/blob/ce3d4d462f49092dc58ffacd6f9e8436b7d759c7/packages/core/src/resources/MergeRequestNotes.ts#L12-L20

https://github.com/jdalrymple/gitbeaker/blob/ce3d4d462f49092dc58ffacd6f9e8436b7d759c7/packages/core/src/resources/ProjectSnippetNotes.ts#L12-L16

https://github.com/jdalrymple/gitbeaker/blob/ce3d4d462f49092dc58ffacd6f9e8436b7d759c7/packages/core/src/resources/EpicNotes.ts#L12-L16

https://github.com/jdalrymple/gitbeaker/blob/ce3d4d462f49092dc58ffacd6f9e8436b7d759c7/packages/core/src/templates/ResourceNotes.ts#L14-L20

**Possible solutions**

Update the types to reflect the documentation (and note that the docs is wrong about `"Merge request"`, it's actually `"MergeRequest"`: https://gitlab.com/api/v4/projects/13718909/merge_requests/2/discussions/f2b28d3774d7f759c47106dcb7ddb4b10aa9b763)

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.14.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.14.0) :rocket:

**Comment by JounQin** [comment]
We have `"noteable_type": "MergeRequest"` on our GitLab CE v13.12.15.

<img width="405" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/8336744/1bcd0ce4-6e7e-4702-a600-478ca30251e5">

@jdalrymple
