### ISSUE TITLE
`MergeRequestEvent` is missing `changes.draft` and `changes.description`

### ISSUE THREAD

**Issue by NatoBoram** [jdalrymple/gitbeaker#3412]
**Description**

In `MergeRequestEvent`, `Changes` can contain a `description`, a `draft` and an `assignees` key.

The `draft` key is documented at https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events, but the `description` is not documented.

For example, in a webhook I received, I got this `changes` object:

```json
{
	"changes": {
		"description": {
			"previous": "This is a previous description",
			"current": "This is the new description"
		},
		"last_edited_at": {
			"previous": "2023-09-22 19:04:21 UTC",
			"current": "2023-09-22 19:22:19 UTC"
		},
		"last_edited_by_id": { "previous": 15780915, "current": 1769747 },
		"updated_at": {
			"previous": "2023-09-22 19:06:44 UTC",
			"current": "2023-09-22 19:22:19 UTC"
		},
		"updated_by_id": { "previous": 15780915, "current": 1769747 }
	}
}
```
```json
{
	"changes": {
		"assignees": {
			"previous": [],
			"current": [
				{
					"id": 1769747,
					"name": "Nato Boram",
					"username": "NatoBoram",
					"avatar_url": "https://gitlab.com/uploads/-/system/user/avatar/1769747/avatar.png",
					"email": "example@example.org"
				}
			]
		}
	}
}
```

**Possible solutions**

Test webhook events and add the missing keys to `changes`.

**Checklist**
- [ ] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
I may be missing something here, but where do you see the types for MergeRequestEvent?

**Comment by NatoBoram** [comment]
Wrong repo, sorry about that. I was getting a bit hasty because of how badly documented the GitLab API is :laughing:

**Comment by jdalrymple** [comment]
> Wrong repo, sorry about that. I was getting a bit hasty because of how badly documented the GitLab API is 😆

Preach :joy:
