### ISSUE TITLE
Browser usage seems to require `https` node module

### ISSUE THREAD

**Issue by jonathanhudak** [jdalrymple/gitbeaker#3416]
**Description**

Hello! Trying to use `@gitbeaker/rest` in browser environment because the package says:

> A typed [GitLab](https://gitlab.com/gitlab-org/gitlab/) SDK for Browser, Node.js, Deno and CLI usage.

However, I am finding I need to polyfill `https` because it is used here:
https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/src/Requester.ts#L20

Webpack config: 

```
target: 'web',
resolve: {
    fallback: {
      https: 'https-browserify',
      http: 'stream-http',
    },
  },
```

Did I miss anything in the documentation?

I saw the recommendation to use but I cannot use external CDNs for my project so need to bundle it.

```
<script type="module">
  import { Gitlab } from 'https://esm.sh/@gitbeaker/rest';
</script>
```

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Simply use the externals config to point to a dummy variable so webpack doesnt cause an issue. https://webpack.js.org/configuration/externals/
