### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by batjko** [jdalrymple/gitbeaker#3419]
**Description**

I am new to this package, and for the life of me, I cannot find any documentation as to how to use it!
There's nothing in the README and even the two files currently in the `docs` folder only give away how to import some of the modules, but not how to actually use them.

What is the SDK's API? What objections and methods are available? How do they work? What should I know about them?

I assume I'm just not seeing something because this is a popular package, but... where is it? 

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [ ] I have read the documentation.

(This item above makes me think there is documentation somewhere... I just couldn't find it)

**Comment by jdalrymple** [comment]
haha https://github.com/jdalrymple/gitbeaker/tree/main/packages/rest

Ill make it more obvious in the future

**Comment by jdalrymple** [comment]
There hasnt been any extensive docs on the entire API, as this would take a substantial amount of time. I should add back all the exposed API's though. Ill do this over the week. If there are specific things you feel should be added, lmk. Feedback is always welcome!

**Comment by batjko** [comment]
Appreciate the quick response!
No worries about being too complete, but I think people need at least an obvious entrypoint. The link to the Rest module is good enough for sure to get started, I would just maybe add a link to that back into the main package's README?

Anyway thanks a lot 🙏

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.18.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.18.0) :rocket:
