### ISSUE TITLE
Group SAML Links

### ISSUE THREAD

**Issue by sam-mccarty-mavenclinic** [jdalrymple/gitbeaker#3420]
**Description**

I was hoping to use the Group SAML link code added in 36.0.0, however it does not appear it is being exported, unlike most of the other new API support that was added in the major release. Was this deliberate or an oversight?

**Checklist**
- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
Thats an oversight! Ill fix that ASAP

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.18.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.18.0) :rocket:
