### ISSUE TITLE
IssueLinks.create returning incorrect response due to incorrect request type

### ISSUE THREAD

**Issue by ashby** [jdalrymple/gitbeaker#3429]
**Description**

- Node.js version: 18.0.0
- Gitbeaker version: 39.19.0
- Gitbeaker release (cli, node, browser, core, requester-utils): rest
- OS & version: NA

When I execute `IssueLinks.create`, the response is an array of issues instead of an object containing `source_issue` and `target_issue`. I think it's because [this code](https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/IssueLinks.ts#L69) should be `post()` and not a `get()`, according to the [Gitlab issue links api](https://docs.gitlab.com/ee/api/issue_links.html#create-an-issue-link).

Since `create` is a `GET`, it's returning the array of issues as if it were `all`.

From the core/dist/index.js on line 3328:
```
var IssueLinks = class extends requesterUtils.BaseResource {
  all(projectId, issueIId, options) {
    return RequestHelper.get()(
      this,
      endpoint`projects/${projectId}/issues/${issueIId}/links`,
      options
    );
  }
  create(projectId, issueIId, targetProjectId, targetIssueIId, options) {
    return RequestHelper.get()(
      this,
      endpoint`projects/${projectId}/issues/${issueIId}/links`,
      {
        targetProjectId,
        targetIssueIid: targetIssueIId,
        ...options
      }
    );
  }
  remove(projectId, issueIId, issueLinkId, options) {
    return RequestHelper.del()(
      this,
      endpoint`projects/${projectId}/issues/${issueIId}/links/${issueLinkId}`,
      options
    );
  }
};
```

**Steps to reproduce**

Just use `IssueLinks.create` out of the box.

**Expected behaviour**

Using `IssueLinks.create` should return an object with `source_issue` and `target_issue`.

**Actual behaviour**

Using `IssueLinks.create` returns a list of issues that are link to the issue with iid passed in as the source image iid paramater.

**Possible fixes**

For `create` switch `RequestHelper.get()` to `RequestHelper.post()` [here](https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/IssueLinks.ts#L69).

**Checklist**
- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.20.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.20.0) :rocket:
