### ISSUE TITLE
MergeRequestDiscussions.create line_code=>can't be blank

### ISSUE THREAD

**Issue by ZeroCool-85** [jdalrymple/gitbeaker#3433]
**Description**

- Node.js version: v18.12.1
- Gitbeaker version: 39.20.0
- Gitbeaker release (cli, node, browser, core, requester-utils): 39.20.0
- OS & version: MacOS

Here is my code:

```
async function postReviewThreadToChangedFile(mergeRequest: MergeRequest, threadPosition: ThreadPosition, content: string) {
    const headers = new Headers();

    headers.append('PRIVATE-TOKEN', process.env.GITLAB_API_TOKEN || '')
    headers.append('Content-Type', 'application/json')
    try {
        if(!process.env.CI_MERGE_REQUEST_PROJECT_ID) {
            throw Error('no project id found')
        }
        
        return await gitlabApi.MergeRequestDiscussions.create(process.env.CI_MERGE_REQUEST_PROJECT_ID, mergeRequest.iid, content, {
            position: {
                positionType: 'text',
                baseSha: threadPosition.baseSha,
                headSha: threadPosition.headSha,
                startSha: threadPosition.startSha,
                newPath: threadPosition.newPath,
                newLine: threadPosition.newLine,
                oldPath: threadPosition.oldPath,
                oldLine: threadPosition.endLine,
            }
        })
    } catch (e) {
        console.log(e)
    }
}
```

Error Message:
```
 description: `"400 Bad request - Note {:line_code=>[\\"can't be blank\\", \\"must be a valid line code\\"], :position=>[\\"is incomplete\\"]}"`,
```

**Steps to reproduce**
1. call the code snipped for the gitbeaker above

**Expected behaviour**

Call doesn throw an error or line_range can be set.

**Actual behaviour**

Error is thrown that line_code cannot be blank, but its also not possible to add it.

**Possible fixes**

- add line_code as property 

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Hmm, looking into the docs, i dont see that the line_code portion as required :thinking: https://docs.gitlab.com/ee/api/discussions.html#parameters-for-multiline-comments

**Comment by jdalrymple** [comment]
Did find this though: https://stackoverflow.com/questions/65926187/what-is-a-gitlab-line-code-as-referenced-when-creating-a-new-merge-request-threa
