### ISSUE TITLE
Deployment Approvals

### ISSUE THREAD

**Issue by tanema** [jdalrymple/gitbeaker#3436]
**Description**
I would like to use gitlab deployment approval functionality which is only available on premium. I know the status of approval data is in a weird state between 16 and 17 but it would be nice to have access to this data. 

Deployments model: https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/Deployments.ts
Deployments docs: https://docs.gitlab.com/ee/api/deployments.html#get-a-specific-deployment

You can find the discrepancy where show would show approval data, however the approval data does not exist in any of the deployment schemas.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.21.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.21.0) :rocket:

**Comment by tanema** [comment]
So quick! Thank you so much!
