### ISSUE TITLE
Support Service Account Users API (Groups)

### ISSUE THREAD

**Issue by claudio-vellage** [jdalrymple/gitbeaker#3437]
**Description**

I want to be able to manage service accounts with this library, I will consider adding this support myself, but maybe someone is faster than me. [GitLab Documentation for Service Accounts](https://docs.gitlab.com/ee/user/profile/service_accounts.html)

This feature has been added in GitLab 16.1.

**Proposal**

I would like to edit the [Groups.ts](https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/Groups.ts) to add this api, but looking at the files, it doesn't seem like the right place for it. A pointer where exactly this should be added is appreciated.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
From what it looks like in the docs, this is already supported in the library. Simply using the GroupMembers/ProjectMembers exports, and then using a service user id when editing or creating

**Comment by claudio-vellage** [comment]
I think there might be a misunderstanding. Basically there is a new API in GitLab 16.1, which can be used to create service accounts and access tokens for those service accounts. This is only available at the top level group. Those users are not billable users, but there is no option to create them in the UI. Is this what you describe can be achieved with GroupMembers? Because it doesn't look like it.

**Comment by jdalrymple** [comment]
haha im dumb. I though the docs you linked WHERE those docs and i was confused. Its kinda small, but i would probably make it owns export. Ill through something together!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.21.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.21.0) :rocket:
