### ISSUE TITLE
Get projects marked for deletion

### ISSUE THREAD

**Issue by dsebastien** [jdalrymple/gitbeaker#3443]
**Description**

I would like to be able to list projects that have been marked for deletion

**Proposal**

- [x] Add the `marked_for_deletion_on` property to `ProjectSchema`
- [ ] Add `markedForDeletion: boolean` to `AllProjectsOptions`
- [ ] Add `markedForDeletion: boolean` to `AllGroupsOptions`

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
>Add markedForDeletion: boolean to AllProjectsOptions

Where do you see this in the docs for the all projects query? https://docs.gitlab.com/ee/api/projects.html#list-all-projects

**Comment by dsebastien** [comment]
Sorry for the confusion. You're right, it doesn't seem to be supported yet. I'll continue filtering on the client side for now

**Comment by dsebastien** [comment]
I have introduced issues to request this for groups and projects:

- https://gitlab.com/gitlab-org/gitlab/-/issues/429315
- https://gitlab.com/gitlab-org/gitlab/-/issues/429316

**Comment by jdalrymple** [comment]
Ill update the type for now, but will keep this issue open for better tracking!

**Comment by jdalrymple** [comment]
I updated the types on the ProjectSchema, but am awaiting the results of those two issues to update options schema

**Comment by jdalrymple** [comment]
> I have introduced issues to request this for groups and projects:
> 
> * https://gitlab.com/gitlab-org/gitlab/-/issues/429315
> * https://gitlab.com/gitlab-org/gitlab/-/issues/429316

The first one has been sorted, the last one is still opened

**Comment by jdalrymple** [comment]
Seems to also be done, but we have a duplicate. The other case is: https://gitlab.com/gitlab-org/gitlab/-/issues/463939.

Ill add the options ASAP and close this.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.1.2`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.1.2) :rocket:
