### ISSUE TITLE
Wrong type of `commitId` in `CommitDiscussions` interface

### ISSUE THREAD

**Issue by kamil1094** [jdalrymple/gitbeaker#3466]
**Description**
In the [commit discussion api docs](https://docs.gitlab.com/ee/api/discussions.html#commits) `commit_id` is a string and on the other hand in `CommitDiscussions` interface it is defined as number.

**Possible fixes**
Update the types to reflect the documentation.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.25.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.25.0) :rocket:
