### ISSUE TITLE
Get group variables

### ISSUE THREAD

**Issue by dsebastien** [jdalrymple/gitbeaker#3472]
**Description**

The current codebase allows retrieving project variables via `ProjectVariables.all`, but the equivalent on the project side only accepts a `projectId` as parameter (which feels weird), and thus does not seem to allow retrieving a group's variables.

It seems supported by the official API: https://docs.gitlab.com/ee/api/group_level_variables.html#list-group-variables

**Proposal**

Add a `groupId` parameter to the `all` method of `GroupVariables` and, when provided, return the list of group variables

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by dsebastien** [comment]
I suppose that the method argument is just positional and that the fact it is called `projectId` in the codebase (https://github.com/jdalrymple/gitbeaker/blob/e057fcfabda761e5d5b30c4a54549a6c79cb2305/packages/core/src/resources/GroupVariables.ts#L14) doesn't really matter

**Comment by jdalrymple** [comment]
Its a naming typo

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.25.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.25.0) :rocket:

**Comment by dsebastien** [comment]
Thank you @jdalrymple
