### ISSUE TITLE
Is there a method for forcing termination of all gitbeaker connections on termination?

### ISSUE THREAD

**Issue by trevor-vaughan** [jdalrymple/gitbeaker#3477]
**Description**

I'm currently wrapping my CLI tool using gitbeaker in Jest tests and, while this works, there are dangling file descriptors related to attempting to contact gitlab servers that do not exist remaining after execution.

This seems to be causing Jest to kill unrelated tests at random intervals.

While I could possibly mock out all remote connections, that's a heck of a lot of effort.

So is there:

* A better way to do this?
* A way to tell the object to terminate all connections at the end of a test?

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
The only time it reaches out to a gitlab server is when there is a request, so would a request timeout work here?

**Comment by jdalrymple** [comment]
Any chance you could share the code youre working on? Might help seeing the exact context youre working with.

**Comment by jdalrymple** [comment]
Similar to what i do In the CLI [tests](https://github.com/jdalrymple/gitbeaker/blob/main/packages/cli/test/e2e/resources/Projects.ts) of the library? 

Is there anyway for you to abstract out a sample project that has the same issue?

**Comment by trevor-vaughan** [comment]
Ah yes, very similar to that test!

I'm not quite following how you're mocking out the server connection though.

**Comment by jdalrymple** [comment]
In that particular test, im not. Its a full e2e test. [Here](https://github.com/jdalrymple/gitbeaker/blob/main/packages/cli/test/unit/index.ts), i mock the whole rest package though.
