### ISSUE TITLE
Gitbeaker attempts to use NodeJS types in browser environment

### ISSUE THREAD

**Issue by nhollander-alert** [jdalrymple/gitbeaker#3480]
**Description**

- Node.js version: n/a
- Gitbeaker version: 39.19.0 - 39.25.0
- Gitbeaker release (cli, node, browser, core, requester-utils): requester-utils
- OS & version: n/a

Since version `39.19.0` the `@gitbeaker/requester-utils` package has added a dependency on [`async-sema`](https://www.npmjs.com/package/async-sema) and [`picomatch`](https://www.npmjs.com/package/picomatch) (via [`micromatch`](https://www.npmjs.com/package/micromatch)) breaking `@gitbeaker/browser` due to a reliance on NodeJS specific types. These changes were introduced in #3426 and affect all package versions since then.

 * `async-sema` uses [NodeJS' Events module](https://nodejs.org/api/events.html) (see [`index.ts:1`](https://github.com/vercel/async-sema/blob/main/src/index.ts#L1))
 * `picomatch` uses [NodeJS' Process module](https://nodejs.org/api/process.html) prior to version 3.0.0 (Current dependency is 2.3.1) (see [utils.js:4](https://github.com/micromatch/picomatch/blob/2.3.1/lib/utils.js#L4))

**Steps to reproduce**

Clone [this minimal reproduction](https://github.com/nhollander-alert/gitbeaker-compat-error).

Test `^39.25.0`:
```
git checkout d1356e9e7ed4418063c23f194e926db1a25739f8
npm install
npm run dev
```
Open the browser and view the developer console. You should see a message like `TypeError: events_1.default is not a constructor`

Test `39.19.0` (Tag bug was introduced in)
```
git checkout 10012f86e376e64cccff0e6f517a965424fba27a
npm install
npm run dev
```
Open the browser and view the developer console. The same message should be present.

Test `39.18.0` (Last working version)
```
git checkout 4ca222bb6ad2af37536921d1f8ccff8543bd0e88
npm install
npm run dev
```

Open the browser and view the developer console. A`Gitlab` object should be printed.

**Expected behaviour**

I expect the behavior to be consistent across all three versions

**Actual behaviour**

Versions from `39.19.0` can not be used in the browser.

**Possible fixes**

Unknown

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Working on this! #3428

**Comment by jdalrymple** [comment]
Gonna close, since im addressing it in #3427
