### ISSUE TITLE
Type is wrong for `forceRandomPassword` in `Users.create()`

### ISSUE THREAD

**Issue by domharrington** [jdalrymple/gitbeaker#3481]
**Description**

- Node.js version: v18.18.2
- Gitbeaker version: 39.25.0
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: macOS 13.5.2 (22G91)

The type for `forceRandomPassword` in `CreateUserOptions` is incorrect, it should be a boolean:

https://github.com/jdalrymple/gitbeaker/blob/fd19ac3b3aaebdea71adee99661565d3836a7ac2/packages/core/src/resources/Users.ts#L154

API Docs: https://docs.gitlab.com/ee/api/users.html#user-creation

> `force_random_password` Set user password to a random value - true or false (default)

**Steps to reproduce**

Try to pass a boolean to forceRandomPassword:

<img width="630" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/848223/3de9b6de-52f1-4f30-a549-e7bc5a273e44">

**Expected behaviour**

Should work

**Actual behaviour**

Type error

**Possible fixes**

Update type to boolean

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

Happy to put in a PR if you want me to, but hopefully should be a one line fix!

**Comment by jdalrymple** [comment]
Its definitely a one line fix! Feel free to through up a PR, I can have it merged today.

**Comment by domharrington** [comment]
I also just noticed that `PersonalAccessTokenSchema.token` should be required instead of optional?

https://github.com/jdalrymple/gitbeaker/blob/fd19ac3b3aaebdea71adee99661565d3836a7ac2/packages/core/src/resources/PersonalAccessTokens.ts#L21

Afaict the `token` is always going to be returned from [this API](https://docs.gitlab.com/ee/api/users.html#create-a-personal-access-token)?

**Comment by jdalrymple** [comment]
Same one is fine!
