### ISSUE TITLE
MergeRequestDiscussions.create does not create note at line

### ISSUE THREAD

**Issue by nopol10** [jdalrymple/gitbeaker#3494]
**Description**

- Node.js version: 18.15.0
- Gitbeaker version: 39.26.1
- Gitbeaker release (cli, node, browser, core, requester-utils): node
- OS & version: Windows 10

When I pass in a position object into `MergeRequestDiscussions.create`, I expected my MR comment to appear on a given line.
However it appears directly in the Overview tab.

**Steps to reproduce**

Invoke the api with appropriate arguments.

**Expected behaviour**

Comment created on a diff line.

**Actual behaviour**

Comment created as a standalone note.

**Possible fixes**

Looking at the request and response that was sent, it seems that the type of the created note is "DiscussionNote" when it should be "DiffNote".
I went and tried the same request and body in postman and was able to get it to work (it returned "DiffNote" and the comment appeared on the line). This was when the data was sent as form-data.
However when I changed the body to JSON (with Content-Type = application/json), it generated a "DiscussionNote" instead.

If I forcefully add "isForm" to the options passed to `MergeRequestDiscussions.create`, it works as expected.
Should `isForm` be defaulted to true for this? Otherwise position options don't work as expected.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
100p on me. I switched this up in #3478. This latest PR should address this one piece though #3497

**Comment by jdalrymple** [comment]
Give the https://www.npmjs.com/package/@gitbeaker/rest/v/39.28.0--canary.3497.1119579763.0 version a look. It should solve the issue, but best to double check first!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.28.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.28.0) :rocket:
