### ISSUE TITLE
Is "forked_from_project" a supported field?

### ISSUE THREAD

**Issue by profblackjack** [jdalrymple/gitbeaker#3506]
I have a usecase of crawling fork relationships to build out lists, and ideally I'd like to be able to crawl both up and down relationships.

Gitlab's rest documentation states that project schemas will contain parent fork info if one exists (under `forked_from_project`), but I don't see the particular field anywhere in gitbeaker

[Link to the relevant section of the Projects api](https://docs.gitlab.com/ee/api/projects.html#get-single-project:~:text=If%20the%20project%20is%20a,the%20upstream%20project%20by%20default.)

**Comment by profblackjack** [comment]
After doing some experimenting, I've determined that the field is present in the responses, but not made explicit in the ProjectSchema type. I'll open an enhancement requesting typing updates!

**Comment by HugoFujuy** [comment]
Hello team,
I have the same issue and I don't find any other issue about this one. What about the field `forked_from_project` please ? 
Have a nice day
