### ISSUE TITLE
Webhook interfaces

### ISSUE THREAD

**Issue by mbrammer** [jdalrymple/gitbeaker#3507]
Hey Justin,

I know this is a bit off topic from your project, but I was wondering if you know of any up-to-date TypeScript interfaces for the [Gitlab Webhooks](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html)?

**Comment by jdalrymple** [comment]
Unfortunately I don't, though it may be worth adding them to the project for completeness.

**Comment by mbrammer** [comment]
> Unfortunately I don't, though it may be worth adding them to the project for completeness.

Let me know if I can assist ;)

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.31.1`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.31.1) :rocket:
