### ISSUE TITLE
Add premium/ultimate missing Project attributes

### ISSUE THREAD

**Issue by ArielPrevu3D** [jdalrymple/gitbeaker#3509]
**Description**

Add the missing attributes of the Project schema that are marked as "Premium" or "Ultimate" in the Gitlab docs (e.g `merge_requests_template`).

https://docs.gitlab.com/ee/api/projects.html#templates-for-issues-and-merge-requests

Other "Premium" attributes such as `mirror_trigger_builds` are missing from the schema typing, event though they are present in the ProjectSchema object.

**Proposal**

Add `merge_requests_template` and `issues_template` to `ProjectSchema` typing.

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.31.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.31.0) :rocket:
