### ISSUE TITLE
Build files are missing in published versions

### ISSUE THREAD

**Issue by kaufmo** [jdalrymple/gitbeaker#3521]
**Description**

- Node.js version: 20.9.0
- Gitbeaker version: 39.33.2
- Gitbeaker release (cli, rest, core, requester-utils): all
- OS & version: Ubuntu 23.10

**Steps to reproduce**

install newest version and use it

**Possible fixes**

add missing builded source code to the published packages

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by nejch** [comment]
I'm guessing something in https://github.com/jdalrymple/gitbeaker/commit/f277995994829138a7fb67358c312d5f485713ee broke this as the previous versions still had the code on npmjs (39.33.0).

**Comment by kaufmo** [comment]
> I'm guessing something in [f277995](https://github.com/jdalrymple/gitbeaker/commit/f277995994829138a7fb67358c312d5f485713ee) broke this as the previous versions still had the code on npmjs (39.33.0).

yes I think the build is missing for the release pipeline

**Comment by jet-esavichev** [comment]
+1 for this issue. Had to rollback the version as it broke our workflow.

**Comment by jet-esavichev** [comment]
> Also I think that packages should be strictly versioned for dependencies, i.e. without ^. Because when installing certain version of @gitbeacker/rest - dependent @gitbeaker/* packages can be newer packages, so may be incompatible or broken.

That's what I did as a workaround. And agree, it's a good practice for production.

The issue appeared on 39.33.1 Versions 39.33.0 and before are OK.

**Comment by jdalrymple** [comment]
Found the problem. For future reference, Gitlab CI artifacts don't automatically get included in upstream jobs unless the job explicitly `need`s the job where those artifacts are created. Even if you `need` a job that is upstream from the one that build the artifacts.

**Comment by jdalrymple** [comment]
As soon as the latest built is completed, ill deploy!

**Comment by jdalrymple** [comment]
Building has started, should be release in 5ish min
