### ISSUE TITLE
Rest Package Depends on a Node Dependency

### ISSUE THREAD

**Issue by kingmesal** [jdalrymple/gitbeaker#3539]
**Description**

I've run into this problem where I'm trying to run my code which is using GitBeaker Rest client in a Cloudflare worker and it blows up on

```
@gitbeaker+rest@39.34.1/node_modules/@gitbeaker/rest/dist/index.mjs:9:37:
      9 │       const { Agent } = await import('https');
The package "https" wasn't found on the file system but is built into node.
Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
 ```
I don't know what the resolution to this problem is, as the [cloudflare docs ](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) don't list the https library as a node compatible library, so adding that compat flag alone doesn't help me. At least not in my test.

Is there anyway to put a guard rail around this so that I can use this library in Cloudflare workers?

I feel like this could be solved, but I'm not sure how...

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
See #3505

**Comment by jdalrymple** [comment]
Hmm, its definitely similar to #3505

**Comment by kingmesal** [comment]
Agreed. It is the same... It didn't occur to me from the titles of the issues.
Duplicate of #3505
