### ISSUE TITLE
Pagination - how do I know if I'm getting everything

### ISSUE THREAD

**Issue by kingmesal** [jdalrymple/gitbeaker#3544]
**How to get all files from a repo**

If using the gitlab api directly, I know how to loop using the header link to make sure I get all the files from a repo.

When using `api.Repositories.allRepositoryTrees(projectId, {recursive: true})`, what do I do? is it just built into the api to iterate can fetch everything?

Is there a code snippet of what to do here?

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by kingmesal** [comment]
I think I will close this as I have run quite a few tests with page sizes that are far less than my repo holds and I appeared to be getting everything back. It appears that gitbeaker has magical internals and must iterate over the return header page links. YAY.

It might be helpful if this were a bit more obvious in the docs.

**Comment by jdalrymple** [comment]
;) https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/README.md#offset-pagination

I definitely need to improve the docs organization
