### ISSUE TITLE
Rebase - SKIP_CI

### ISSUE THREAD

**Issue by kingmesal** [jdalrymple/gitbeaker#3548]
**Description**

It would appear that there is a flag on rebase `skip_ci` which doesn't appear to be in the gitbeaker API

https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request

**Proposal**

Would be a nice option to have to ensure a pipeline doesn't get triggered.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.0.0) :rocket:
