### ISSUE TITLE
AccessTokenSchema.token is not optional when create 

### ISSUE THREAD

**Issue by ArnaudTA** [jdalrymple/gitbeaker#3553]
**Description**

Hello, 
I noticed `AccessTokenSchema` has optional `token` key, it makes sense when you use `api.GroupAccessTokens.show` but not on `api.GroupAccessTokens.create` method.

It's not urgent or important but if you can fix it would be nice :)

**Possible solutions**
I don't have solution that meet your code quality, my ideas are pretty ugly :/ 

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.0.0) :rocket:
