### ISSUE TITLE
Missing a method to set 'job_token_scope'?

### ISSUE THREAD

**Issue by ForbiddenEra** [jdalrymple/gitbeaker#3564]
**Description**

In order for pipelines to be able to trigger other pipelines (downstream or 'multi-project pipelines'), the triggered project needs the parent project set in it's 'job_token_scope' or to have the feature disabled.

https://archives.docs.gitlab.com/16.4/ee/api/project_job_token_scopes.html

I searched for `job_token_scope` in the sources and API docs but it was only found in one place, related to an actual job itself.

**Proposal**

Add the missing API calls. :-)

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by ForbiddenEra** [comment]
<3

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.1.0) :rocket:
