### ISSUE TITLE
missing projectId in return type of api.Search.all('commits' ... )

### ISSUE THREAD

**Issue by aljorhythm** [jdalrymple/gitbeaker#3568]
**Description**

`projectId` is present in searches that are scoped to 'commits' in gitlab API https://docs.gitlab.com/ee/api/search.html#scope-commits. This is not refected in the return type of `api.Search.all('commits', ...)`

**Steps to reproduce**

<img width="480" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/1833207/c530ff2c-5c24-4181-aa3b-95bdd5e6fdb6">

**Expected behaviour**

**Actual behaviour**

Type not found

**Possible fixes**

modify Search.ts
<img width="786" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/1833207/52b86a93-7bb9-49ac-b857-495213db362b">

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.0.3`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.0.3) :rocket:
