### ISSUE TITLE
.env file not actually checked?

### ISSUE THREAD

**Issue by joshuahhh** [jdalrymple/gitbeaker#3578]
https://www.npmjs.com/package/@gitbeaker/cli indicates env vars can "be set globally or using a .env file in the project folder." But this doesn't work for me, and looking through the source code, it doesn't seem like any code in this repo imports dotenv or otherwise accesses a .env file. (I might be missing something tho.) Thanks!

**Comment by jdalrymple** [comment]
Looks like either I mistyped or lost some functionality along the way. I'll determine which and follow up! Sorry for the inconvenience.

**Comment by jdalrymple** [comment]
So i did some digging and apparently we've never supported that at all -_-. Perhaps it was an idea when i first put together the library, but never implemented it to reduce deps. I'll remove it from the docs to get rid of the confusion.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.1.0) :rocket:
