### ISSUE TITLE
the export of @gitbaker/core was overwritten by the export of @gitbaker/rest

### ISSUE THREAD

**Issue by s952787097** [jdalrymple/gitbeaker#3604]
**Description**

**Reproduction steps:**
---
When I was creating a Gitlab REST API instance, I needed to extract some methods according to their functionality. However, when setting function parameter types, I encountered a problem, as shown in the following figure

<img width="943" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/26595017/517638e0-437d-42fb-a22e-f7e5f576c2e4">

I checked the d.ts file and found that the export of @ gitbaker/core was overwritten by the export of @ gitbaker/rest

<img width="1102" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/26595017/f11b25e8-dc24-496a-b921-9c3baec83bd9">

**Temporary plan:**
---
Through the following method, I temporarily installed @ gitbaker/core in my project to solve the issue of being overwritten. However, I don't think this is a very reasonable way of using it

<img width="778" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/26595017/506766a5-62b8-45ca-be39-f0e3f7df7c46">

**Suggestion:**
---
Can the d.ts file be modified to export CORE through @ gitbaker/rest

<img width="1060" alt="image" src="https://github.com/jdalrymple/gitbeaker/assets/26595017/af19c634-facc-416f-a250-58e893791c45">

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Hmm, thats odd that it would override just that one export, and not the others like that. Ill give it a look!

**Comment by jdalrymple** [comment]
For now, if you use this format it should work correctly:

```
function func(api: InstanceType<typeof Gitlab>) {
...
}
```

**Comment by jdalrymple** [comment]
It looks like some part of the  typing are lost after going deeper into the export chain. Even without the export on line 2 there, the results are the same. 

For example, the export on line 1:

```
import * as CORE from '@gitbeaker/core';
```

Returns an object whose properties are :

```
...
Gitlab: typeof Core.Gitlab
...
```

And the export of the file itself is an object with properties:

```
...
Gitlab: typeof Core.Gitlab
...
```

The difference between this and the import directly from CORE, is the latter contains the typing for the interface and class and the former only has a reference via typeof. Not sure what a better way of handling this would be, besides importing all the modules individually.

**Comment by s952787097** [comment]
> For now, if you use this format it should work correctly:
> 
> ```
> function func(api: InstanceType<typeof Gitlab<false>>) {
> ...
> }
> ```

I'm sorry for only seeing your message now. I tried this method and it was feasible. This should be a misunderstanding on my part. I forgot that this type should be an instance rather than a class. Thank you very much for your reply.😊
