### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by jeinwag** [jdalrymple/gitbeaker#3607]
Are there any plans for the new release? We'd like to use some functions which are already there, but not in the lastest release.

Thank you.

**Checklist**

- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
Hopefully soon, I ran into some problems with the GL docker image used in CI/CD script for testing and I havent had the time to sort it out lately. Sorry for the delay!!

**Comment by jdalrymple** [comment]
Released :rocket:

**Comment by jeinwag** [comment]
Thank you, that was fast!
