### ISSUE TITLE
Incorrect type in WebhookMergeRequestEventSchema

### ISSUE THREAD

**Issue by ttdung24** [jdalrymple/gitbeaker#3610]
**Description**

Wrong `reviewers` type in WebhookMergeRequestEventSchema.

[Gitlab Event Schema](https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events)

[See code here](https://github.com/jdalrymple/gitbeaker/blob/0df30514d4c744489862d57b85bddfde13b4aecb/packages/core/src/resources/Webhooks.ts#L381)

**Possible solutions**

Change the type of `reviewers` to be the same as `assignees`.

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.1.3`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.1.3) :rocket:
