### ISSUE TITLE
Type for uploading a user avatar is incorrect and  requires adding `isForm: true` to work

### ISSUE THREAD

**Issue by mdsummers** [jdalrymple/gitbeaker#3611]
**Description**

- Node.js version: 18.20.3
- Gitbeaker version: `@gitbeaker/rest@40.1.2`
- Gitbeaker release (cli, rest, core, requester-utils): rest
- OS & version: macOS 14.5

The type for the `avatar` field for creating / editing a user is defined as follows: 

https://github.com/jdalrymple/gitbeaker/blob/e9ca9e97f85e4b5bbc9aaeb240bfefe01569478a/packages/core/src/resources/Users.ts#L159

(an object with a content and filepath field). However, this does not work, a "Bad Request" is returned from gitlab. Non-working example:

```
await api.Users.edit(userId, {
  avatar: {
    content: new Blob([imageBuffer], { type: 'image/png' }),
    filepath: 'avatar.png'
  }
}); // throws GitbeakerRequestError: Bad request
```

Searching through the source code for `isForm: true` seems to indicate that there should be an implementation for Users.ts that takes avatar in the above form and converts it to a tuple adding `isForm: true`. As such the following is a workaround right now:

```
await api.Users.edit(userId, {
  avatar: [new Blob([imageBuffer], { type: 'image/png' }), 'avatar.png'],
  isForm: true
});
```

**Steps to reproduce**

The first snippet above shows a bit of code which reproduces

**Expected behaviour**

We don't get a 400 Bad Request back

**Actual behaviour**

We get a 400 Bad Request back.

**Possible fixes**

Add handling in Users.ts to take avatar in the format indicated by the type into form format.

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`41.1.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/41.1.0) :rocket:
