### ISSUE TITLE
ProjectRemoteMirrors is missing `sync`

### ISSUE THREAD

**Issue by unilynx** [jdalrymple/gitbeaker#3616]
**Description**

Support for "Force push mirror update" is missing - https://docs.gitlab.com/ee/api/remote_mirrors.html#force-push-mirror-update

**Proposal**

I hotfixed the NPM module as follows, adding sync() to ProjectRemoteMirrors:

```
  sync(projectId, mirrorId) {
    return RequestHelper.post()(
      this,
      endpoint`projects/${projectId}/remote_mirrors/${mirrorId}/sync`
    );
  }
```

This seems to work

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.2.0) :rocket:
