### ISSUE TITLE
Missing closed date option for issues

### ISSUE THREAD

**Issue by Kalimorr** [jdalrymple/gitbeaker#3619]
**Description**

- Node.js version: 20.13.1
- Gitbeaker version: 40.1.3
- OS & version: Windows

Hi,

I try to get all the issues of a project closed after a defined date by there is no options for that.
There is the option `updatedAfter` but if a closed issue is updated for any reason after being closed the results of the the request becomes wrong.

**Steps to reproduce**

```typescript
const api = new Gitlab({
  host: config.public.gitlabHost,
  token: config.public.gitlabToken,
});

const allReleasedIssues = await api.Issues.all({
    projectId: project.id,
    state: 'closed',
    labels: releasedLabel,
    updatedAfter: formattedDateLimit,
});
```

**Expected behaviour**

```typescript
const allReleasedIssues = await api.Issues.all({
    projectId: project.id,
    state: 'closed',
    labels: releasedLabel,
    closedAfter: formattedDateLimit,
});
```

**Possible fixes**

It would by nice to add those options to the `AllIssuesOptions` type : 

```typescript
type AllIssuesOptions = {
...
closedAfter?: string;
closedBefore?: string;
}
```

And look at the field `closed_at` of GitLab API to get the right data.

Thanks !

**Comment by jdalrymple** [comment]
Just looking through the docs, it doesnt look like "closedAfter" and "closedBefore" are documented: https://docs.gitlab.com/ee/api/issues.html#list-issues

Did i miss something? or are their own docs out of date?

**Comment by jdalrymple** [comment]
I just reread this. I dont intend on adding any shortcuts (if i can avoid it) that are not natively supported by the GL API, to avoid headache in the future in terms of parity. Id suggest pitching this idea in the GL issue board to have it officially added. It could definitely be useful!

**Comment by jdalrymple** [comment]
I see a related issue here: https://gitlab.com/gitlab-org/gitlab/-/issues/440227
