### ISSUE TITLE
🐞 Deployment Create Tag (string v boolean)

### ISSUE THREAD

**Issue by mxbaylee** [jdalrymple/gitbeaker#3625]
**Description**

- Node.js version: v21.7.3
- Gitbeaker version: 40.1.3
- Gitbeaker release (cli, rest, core, requester-utils): core
- OS & version: Sonoma 14.3

I might be using the API incorrectly but I'm noticing a discrepency attempting to create a preview deployment on a merge request.

* [Gitlab Deployment Create Docs](https://docs.gitlab.com/ee/api/deployments.html#create-a-deployment)
  * This suggests `tag` is a boolean
* [Internal Code](https://github.com/jdalrymple/gitbeaker/blob/main/packages/core/src/resources/Deployments.ts#L96)
  * This suggests `tag` is a string

I might be missing something here, but I think this is incorrect.

**Comment by jdalrymple** [comment]
Youre not missing anything, this is a mistake on my end!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.2.2`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.2.2) :rocket:
