### ISSUE TITLE
Missing typescript overload for Issues.all({ showExpanded: true, withLabelDetails: true })

### ISSUE THREAD

**Issue by kouak** [jdalrymple/gitbeaker#3633]
**Description**

- Node.js version: 22.8.0
- Gitbeaker version: 40.3.0
- Gitbeaker release (cli, rest, core, requester-utils): rest
- OS & version: Linux

Basically, a missing overload/case regarding `Issues.all()`.

![image](https://github.com/user-attachments/assets/cf15eba7-559d-49f3-9fb5-a64627b6a365)

**Steps to reproduce**

```typescript
      const issues = await gitlab.Issues.all({
        projectId: 1,
        withLabelsDetails: true,
        showExpanded: true,
      });
```

**Expected behaviour**

`issues` should be `{ paginationInfo: OffsetPagination, data: IssueSchemaWithExpandedLabels[] }`

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.6.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.6.0) :rocket:
