### ISSUE TITLE
`Namespaces.all` is missing `topLevelOnly` option

### ISSUE THREAD

**Issue by yousinix** [jdalrymple/gitbeaker#3636]
The `Namespace.all` endpoint is missing the `topLevelOnly` option.

[🔗 Reference
](https://docs.gitlab.com/17.4/ee/api/namespaces.html#list-namespaces)

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/ffc2dc4c-10eb-4328-9a7f-dc0cd3fb7a33">

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`40.5.1`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.5.1) :rocket:
