### ISSUE TITLE
AllGroupProjectsOptions missing topic parameter

### ISSUE THREAD

**Issue by amiceli** [jdalrymple/gitbeaker#3647]
**Description**

- Node.js version: v18
- Gitbeaker version: 41.1.0
- Gitbeaker release (cli, rest, core, requester-utils): rest
- OS & version: MacOS

`AllGroupProjectsOptions` used with `Groups.allProjects` missing `topic` parameter allowed in [gitlab group api](Groups.allProjects).

```typescript
const projects = await this.api.Groups.allProjects(groupId, {
    // @ts-ignore
    topic: 'front' // it works
})
```

**Steps to reproduce**

```typescript
const projects = await this.api.Groups.allProjects(groupId, {
    // @ts-ignore
    topic: 'front' // it works
})
```

**Expected behaviour**

Allow to filter group projects with topic.

**Actual behaviour**

It works only with.a `@ts-ignore`.

**Possible fixes**

Add `topic` in `AllGroupProjectsOptions`.

**Checklist**

- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`41.1.1`](https://github.com/jdalrymple/gitbeaker/releases/tag/41.1.1) :rocket:
