### ISSUE TITLE
`DeployToken.create` 's API is more limited than underlying GitLab REST API

### ISSUE THREAD

**Issue by mpsanchis** [jdalrymple/gitbeaker#3648]
**Description**

The current implementation of `DeployToken.create` allows to pass an arbitrary list of arguments in the options object (in JS), but the type definitions don't. Therefore, when using strict Typescript, we cannot pass options `username` and `expires_at` unless we add something like `@ts-ignore`.

**Expected behaviour**

The `DeployToken.create` API should match the underlying Gitlab REST API: https://docs.gitlab.com/ee/api/deploy_tokens.html#create-a-project-deploy-token

Which exposes the parameters:
* name
* scopes
* expires_at
* username

**Actual behaviour**

The current implementation of the `DeployToken.create` is:
```typescript
  create<E extends boolean = false>(
    name: string,
    scopes: string[],
    {
      projectId,
      groupId,
      ...options
    }: OneOf<{ projectId: string | number; groupId: string | number }> &
      Sudo &
      ShowExpanded<E> = {} as any,
  ): Promise<GitlabAPIResponse<DeployTokenSchema, C, E, void>> {
  ```
  
  Which exposes the parameters:
  * name
  * scopes
  
  and is therefore missing:
  * username
  * expires_at

**Possible fixes**

We could:
a. Simply add them to the function definition as optional (`?`) parameters, or
b. If that is exposing too many parameters, we could create a `DeployTokenCreateOptions` type that contains them all.

I would do (b.), I think it looks cleaner to have something like:
```typescript
create<E extends boolean = false>(
  {projectId, groupId}: OneOf<{ projectId: string | number; groupId: string | number }>,
  options: DeployTokenCreateOptions & Sudo & ShowExpanded<E> = {} as any
): Promise<GitlabAPIResponse<DeployTokenSchema, C, E, void>> {
```

and then define the options that Gitlab's REST API exposes in a:
```typescript
interface DeployTokenCreateOptions {
  name: string,
  scopes: ('read_repository' | 'read_registry' | 'write_registry' | 'read_package_registry' | 'write_package_registry' )[],
  expires_at?: string,
  username?: string,
}
```

**Checklist**

- [X] I have checked that this is not a duplicate issue.
- [X] I have read the documentation.

**Note**

I'd be happy to open a pull request, but I saw in the contribution guide that you'd rather have an issue/discussion first. Let me know what's your preferred approach 😄

**Comment by jdalrymple** [comment]
Great summary in the issue and your implementation `DeployTokenCreateOptions` is solid too. Feel free to throw it into a PR and ill add it ASAP!

**Comment by mpsanchis** [comment]
Thanks for the quick reply @jdalrymple ! 😄 
I have made the PR here: https://github.com/jdalrymple/gitbeaker/pull/3652

Let me know if I need to do some extra stuff (each repo has their own rules..)

Cheers
