### ISSUE TITLE
GroupJobTokenScopes should expect a project_id and a target_group_id

### ISSUE THREAD

**Issue by clario-masonb** [jdalrymple/gitbeaker#3649]
https://github.com/jdalrymple/gitbeaker/blob/77a20d94db8c03c70b372f8bffdb1594c18aa514/packages/core/src/resources/GroupJobTokenScopes.ts#L8

Groups do not have Job Token allow lists, only Projects have job token allow lists. 

The nuance is a project can either add a target group or a target project to its allow list.

https://docs.gitlab.com/ee/api/project_job_token_scopes.html#add-a-group-to-a-cicd-job-token-allowlist

**Comment by jdalrymple** [comment]
Not sure how I overlooked this when i implemented it. Thanks for the clarification

**Comment by jdalrymple** [comment]
I think i got all the references correct, but if you have a minute, give the PR a once over :pray:

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`41.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/41.2.0) :rocket:
