### ISSUE TITLE
add field in the WebhookMergeRequestEventSchema

### ISSUE THREAD

**Issue by xojlodok** [jdalrymple/gitbeaker#3661]
**Description**

Missing field in the WebhookMergeRequestEventSchema.changes

`changes.reviewers`

webhook has this field

![image](https://github.com/user-attachments/assets/f17ed7c2-001e-4f08-91e9-a53240142b99)

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`42.0.1`](https://github.com/jdalrymple/gitbeaker/releases/tag/42.0.1) :rocket:
