### ISSUE TITLE
Add "internal" to merge request note options

### ISSUE THREAD

**Issue by Kirdock** [jdalrymple/gitbeaker#3662]
**Description**

According to the [documentation](https://docs.gitlab.com/ee/api/notes.html#create-new-merge-request-note), you can set an `internal` boolean flag but this is currently not possible within the options of [MergeRequestNotes.create](https://github.com/jdalrymple/gitbeaker/blob/5e70aa3e612a2b16436c3d39412191689ee00ed3/packages/core/src/resources/MergeRequestNotes.ts#L32)

**Checklist**

- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`42.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/42.0.0) :rocket:
