### ISSUE TITLE
JEST test is breaking due to async callback was not invoked. 

### ISSUE THREAD

**Issue by pratikjagrut** [jdalrymple/gitbeaker#398]
We discussed the [timeout issue](https://github.com/jdalrymple/node-gitlab/issues/396#issuecomment-516014362), and it is fixed in the latest release. But I'm still facing a similar problem while I'm running a test written using JEST. 

This is a small method 
```
async getRepoBranchList(): Promise<BranchList> {
    try {
        const projectID = await this.getProjectId(); //e.g 123456789
        const resp = await this.client.Branches.all(projectID)
        const list = resp.map(branch => {
          return new Branch(branch.name);
        });
        return new BranchList(resp, list)
    }catch (e) {
        throw e;
    }
  }
```
I get an expected output when I run it manually.

Test:
Here GitSource is a wrapper, it will initialize `Gitlab()` client
```
it('should list all branches of existing public gitlab repo', (done: any) => {
    const gr = new GitSource(
      "https://gitlab.com/team-xyz/xyz.git",
      SecretType.NO_AUTH,
      null,
    );

    const gs = new GitlabService(gr);
    gs.getRepoBranchList()
      .then((r: any)=> {
        assert.ok("List of branches", r);
        done()
      })
      .catch((err: Error) => {
        done(err);
        assert.fail("Repo is existing")
      })
  });
```

This same test is working for other git clients (as Github and Bitbucket clients).

The test is throwing an error:
```
Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:
```
I tried increasing timeout limit but the end result is the same, it's failing.
Somehow gitlab client methods are not able to return promise to the JEST, or I might have made any mistake but not able to catch.

But the code is running fine when I run it individually, I mean directly like `npm start` it returning branch list. But tests are not able to invoke async callback.

**Comment by jdalrymple** [comment]
Hmm, do you get similar results if the test is changed a bit to:

```javascript
...

const gs = new GitlabService(gr);

return gs.getRepoBranchList()
      .then((r: any)=> {
        assert.ok("List of branches", r);
      })
      .catch((err: Error) => {
        assert.fail("Repo is existing")
      })
  });
```

Also how long does it take to get the response when you run it outside of the test? im guessing much less than 10k ms

**Comment by pratikjagrut** [comment]
I tried as you said but it's still failing and outside the test, it taking `6579 ms` less than 10k ms as you guessed.

**Comment by jdalrymple** [comment]
Hmm, im not really sure :( Its odd that it only happens in jest situations

**Comment by pratikjagrut** [comment]
Any updates on this, any workaround to this bug? Or do you know anyway changes which I can do in tests to make it work?

**Comment by jdalrymple** [comment]
@pratikjagrut As of right now, not yet :( Still trying to narrow down the problem.

**Comment by jdalrymple** [comment]
@pratikjagrut  Could you put together a small sample project with this issue?
