### ISSUE TITLE
Updating Group Organization - Thoughts?

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/gitbeaker#483]
**Description**
Just thinking about how to better organize the group for ease of use by developers looking for Gitlab add-ons.

1. Similar to the thoughts in https://github.com/moul/node-gitlab/issues/191#issuecomment-381260105 It would be nice to clean up the group. Maybe change it to some generic name to host gitlab wrappers? Where each internal repo would be node-gitlab, python-gitlab etc
2. Archiving older repos in the group that are no longer in use or are duplicates?
3. Mirroring on gitlab. Right now its just on my personal account, but since weve moved the repo to this group, it has become inconsistent.
4. Keep things as they were, redirect traffic from the archived repo

Anyways just looking for thoughts!! :D

**Comment by casz** [comment]
I see you already moved it to node-gitlab/node-gitlab 😆

**Comment by jdalrymple** [comment]
lol, we can always move it around :P hence the request for Ideas. One of the biggest issues was that the google searches were pointing to node-gitlab/node-gitlab which isnt really useful for those looking for this repo.

**Comment by jdalrymple** [comment]
*cricket sounds* Kinda leaning towards #4 since it would be a bit less work lol

**Comment by casz** [comment]
I think you could split the bin out into a separate repo 😄
To avoid unnecessary dependencies for those who do not use the bin?

**Comment by jdalrymple** [comment]
We could also do a monorepo and split the packages similarly to jest

**Comment by casz** [comment]
Ya that could work too lerna is awesome 😄

**Comment by jdalrymple** [comment]
I agree!! But that still doesnt solve what we should do about the group lol

**Comment by casz** [comment]
Still not sure what you had in mind for the group, do you want to move all gitlab wrappers to a new group? ie. 
Do you want to move something like https://github.com/nmklotas/GitLabApiClient ?

**Comment by jdalrymple** [comment]
That's what I'm trying to figure out, whats the purpose of the group?

**Comment by jdalrymple** [comment]
Side note: We could setup an organization, and publish for cli, core (nodejs) and move the types to the @types repo or its own package. This would reduce the size of the published packages as well. 

Problems with this move are the change of the npm package name :/ and intuitive organization name (@gitlab is already taken)

Just thinking outloud! More ideas are welcome :D

**Comment by jdalrymple** [comment]
So I've come to a decision that I'm going to try and complete over the holidays. Basically, I want to follow along the octokit path and rebrand the repo/npm package.

The thrown around name is Gitbeaker, playing off the Gitlab name. The logo design is still up in the air, but will probably be one of the three below:

![image](https://user-images.githubusercontent.com/3743662/71356902-ed46b900-2583-11ea-83a6-75578a8850a0.png)

The npm package Gitlab will be deprecated and will reroute to the @gitbeaker/core package. There will also be a @gitbeaker/cli package for the cli build and a @gitbeaker/browser for the browser build.

I've decided to split the browser and node builds because the support available in ky doesn't take advantage of streaming, and the owner doesn't foresee adding that functionality in the near future. Thus, the core library will take advantage of got, while the browser will continue to use ky. This will close #338 and #279 issue, which is also a benefit.

Finally, there will be a new repo, gitbeaker. It will be a mono repo with three subpackages: core, cli, and browser. Why a mono repo? Well, since each of these npm packages would need to be updated/deployed when the core package was updated, it made more sense to have it all in one place. This *should* avoid version mismatches between the different releases.

This repo will also be mirrored on gitlab (since it should be there :joy:)

**Comment by casz** [comment]
I like gitbeaker what do you think if the C# implementation joined? 
https://github.com/nmklotas/GitLabApiClient

WDYT @nmklotas ?

**Comment by casz** [comment]
I like the third logo because it adds a bit of color.

**Comment by casz** [comment]
@jdalrymple you could rename the old npm package name point to the new npm package even show a deprecation warning? Such things are supported.

https://stackoverflow.com/questions/28371669/renaming-a-published-npm-module

**Comment by nmklotas** [comment]
@casz I'm lost, what is git beaker ?:D how its connected to gitlab and gitlab api client for .net? :)

**Comment by jdalrymple** [comment]
Just a bit delayed. Need to fix the release automation. Apparently semantic release doesnt fully support monorepos :(
