### ISSUE TITLE
Improve typing for API responses

### ISSUE THREAD

**Issue by Aetherall** [jdalrymple/gitbeaker#492]
The typings of the outputs of the api are wrapped on a Response type which does not let access to the real interface representing the api output data. Please expose the real interface in a way allowing production use :)

**Comment by avevlad** [comment]
@jdalrymple any news?

**Comment by jdalrymple** [comment]
Would be cool to autogen the types based on the sample code from gitlab using https://jvilk.com/MakeTypes/

**Comment by jdalrymple** [comment]
Been working on this one as part of #1104  but its going to take a bit of time to go through each of the services currently supported and write up their schema types. bear with me!

**Comment by jdalrymple** [comment]
Should be available now! Check out Release 29.0.0
