### ISSUE TITLE
pagination does not work for ResourceMembers

### ISSUE THREAD

**Issue by jiadi0801** [jdalrymple/gitbeaker#518]
"gitlab": "^14.0.1",

```js
// Jest
test('api /projects/${repoName}/members', async function (done) {
    let members = await api.ProjectMembers.all('namespace/name', {
      page: 1,
      showPagination: true,
      maxPages: 3
    }) as any;
    expect(Array.isArray(members)).toBe(true);  // always be true here
    console.log(members)
    done();
 });
```
when I use `ProjectMembers` to get members with `PaginatedRequestOptions`,  it always return array. 

I tried `ProjectMembers` and some other services, they work fine.

I got the compiled position in dist/index.js （`https://github.com/jdalrymple/gitbeaker/blob/c6f4c51d585c3906547334256e01c31e1ddced14/src/core/infrastructure/RequestHelper.ts#L78`） ，write  'console.log' here to see what happened, the log makes me confused.

dist/index.js
```
case 3:console.log(p);return[2,(p.page||c.length>0)&&o?{data:c,pagination:a}:c]
```

terminal output
```
  ✓ api /projects/${repoName}/members (203ms)

  console.log node_modules/gitlab/dist/index.js:1
    {}

  console.log node_modules/gitlab/dist/index.js:1
    { options: { page: 1, showPagination: true, maxPages: 3 } }
```

Shouldn't it only be executed once，and the console.log(p) print `{ page: 1, showPagination: true, maxPages: 3 }` ?

**Comment by jiadi0801** [comment]
seems found the issue。

In ResourceMembers.ts, the all and show method params here `return RequestHelper.get(this, url.join('/'), { options });` should be `return RequestHelper.get(this, url.join('/'), { ...options });`

**Comment by casz** [comment]
Send a PR?
