### ISSUE TITLE
Invalid json response body when using the Jira services API

### ISSUE THREAD

**Issue by jetersen** [jdalrymple/gitbeaker#555]
**Description**

**Steps to reproduce**

api/v4/projects/id/services/jira is very buggy and for some reason throws non JSON when erroring.

**Expected behaviour**

I'd like to understand what is wrong but I cannot debug into the code and find the body response.

**Actual behaviour**

Useless FetchError

**Possible fixes**

Log the body response

**Comment by jdalrymple** [comment]
Thats really odd, ill try and give it a look over the weekend!

**Comment by casz** [comment]
Perhaps it would help debug if distributed had source maps

**Comment by jdalrymple** [comment]
Any updates on this?

**Comment by jetersen** [comment]
Yes, I stopped using Gitlab 😆

**Comment by jdalrymple** [comment]
Alright, going to close this then!
