### ISSUE TITLE
How to submit a different namespace to ProjectImportExport.import() ?

### ISSUE THREAD

**Issue by SirkoS** [jdalrymple/gitbeaker#568]
From reading [the Gitlab documentation on importing project from a file](https://docs.gitlab.com/ee/api/project_import_export.html#import-a-file) there are some more parameters then `file` ad `path`, that are [supported here](https://github.com/jdalrymple/gitbeaker/blob/master/src/core/services/ProjectImportExport.ts#L22).

```typescript
import(content: string, path: string, options?: Sudo) {
```

Using the general `options` is of no use, as the parameters there will be [overwritten later on](https://github.com/jdalrymple/gitbeaker/blob/master/src/core/infrastructure/RequestHelper.ts#L99) in the execution pipeline.

```typescript
const response = await service.requester.post(service, endpoint, {
    body: form || body,
    sudo,
  });
```

I have have commit that fixes that over in [my fork](https://github.com/SirkoS/gitbeaker) (in particular [this commit](https://github.com/SirkoS/gitbeaker/commit/c90fabf303f1f50576f4f79f8a70fd38545793be)). However, before I make  a pull request, please check, if the implementation fits your code-style or you prefer something different.

**Comment by jdalrymple** [comment]
Hmm you actually found a pretty important edge case. To avoid solving it for just this use case, I'm going to fix up the functionality in the RequestHelper. I'll post something up in the next couple hours!
