### ISSUE TITLE
Unsupport /api/v4/session as it was removed in Gitlab 9.5

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [jdalrymple/gitbeaker#637]
session api is 404
`
{
    "error": "404 Not Found"
}
`

**Comment by Jetersen** [comment]
Session API has been removed since 9.5
Finding the docs that says it was removed is a little harder.
https://forum.gitlab.com/t/gitlab-session-api-is-not-working-in-gitlab-ce-10-3-5/13976/6

**Comment by jdalrymple** [comment]
Apparently already did [this](https://github.com/jdalrymple/gitbeaker/releases/tag/10.0.3)
