### ISSUE TITLE
Upgrade from node-gitlab 14.2.2

### ISSUE THREAD

**Issue by oocl-kevinha** [jdalrymple/gitbeaker#691]
Can I  upgrade from 14.2.2 to gitbreaker latest version without breaking ?
I am using node 10.18.1

**Comment by jetersen** [comment]
@oocl-kevinha check the release notes: https://github.com/jdalrymple/gitbeaker/releases

**Comment by jdalrymple** [comment]
If youre still having trouble after reading the release notes, ask away :)
