### ISSUE TITLE
How to resolve a merge request discussion

### ISSUE THREAD

**Issue by lev-kuznetsov** [jdalrymple/gitbeaker#692]
Hi, I don't see any other way to ask questions, I'm trying to figure out how to resolve a merge request discussion. It seems to be possible via API: https://docs.gitlab.com/ee/api/discussions.html#modify-an-existing-merge-request-thread-note but I don't see an edit method on the merge request discussion only editNote.

**Comment by jdalrymple** [comment]
You can use the `editNote` function. Here is some pseudo code to do such a thing:

```javascript
...
const service = new MergeRequestDiscussions(...);

service.editNote(
id,
mergeRequestIId,
discussionId,
noteId,
null,
{ resolved: true }
)
```

Apparently the body is no longer a required parameter. I will move it to the optional arguments in the next release of the library :nerd_face:
