### ISSUE TITLE
Gitbreaker node script hangs when calling all projects

### ISSUE THREAD

**Issue by damusix** [jdalrymple/gitbeaker#751]
**Description**
Whenever I use `ProjectsBundle` or `Gitlab` constructor, my script hangs forever. It doesn't error out, or ever finish. I have looked at closed tickets to see if this was a thing before, but didn't find anything relevant.

**Steps to reproduce**

```bash
mkdir testGitbeaker && cd "$_"
npm init -y
npm i --save 
```

`index.js`
```js
const { ProjectsBundle } = require('@gitbeaker/node');

const services = new ProjectsBundle({
  token: 'XXXXXXXXXXXX',
});


setInterval(() => console.log(new Date()), 1000);

services.Projects.all().then(console.log);
```

```bash
node .
```

**Expected behaviour**
Should give me a list of projects

**Actual behaviour**
Script hangs forever

![Screen Shot 2020-05-04 at 3 38 59 PM](https://user-images.githubusercontent.com/4218587/81007747-cc3e8080-8e1f-11ea-8c69-16e1b042c04d.png)

**Comment by jetersen** [comment]
No it doesn't :)
Your querying against gitlab.com it will take ages to get all the projects.

**Comment by damusix** [comment]
@jetersen Documentation is not very descriptive of how someone should go about querying their own projects, or scoped within their group. I tried the following:

```js

const services = new GroupsBundle({
  token: 'xxxxxxxxxxx',
});

const resp = await services.Groups.all({
  search: 'zencare'
})
```

---

```js

const { data, pagination } = await services.Projects.all({
  perPage:40,
  maxPages:2,
  showPagination: true
});
```


All hang for over 10 seconds.

**Comment by damusix** [comment]
Also, adding scope to `all()` function gives me these log warnings:

```
(node:54144) ExperimentalWarning: The dns.promises API is experimental
(node:54144) ExperimentalWarning: The fs.promises API is experimental
```

**Comment by jetersen** [comment]
https://docs.gitlab.com/ee/api/projects.html#list-all-projects

You can try using `membership: true` or `owned: true` in your options object.

> Also, adding scope to all() function gives me these log warnings:

Those warnings are coming from nodejs, not sure you can hide them based on this:
https://github.com/nodejs/node/issues/19704

**Comment by jdalrymple** [comment]
Hmm, when you run this:
```
const { data, pagination } = await services.Projects.all({
  perPage:1,
  maxPages:1,
  showPagination: true
});
```

Does it hang as well?

**Comment by damusix** [comment]
@jetersen I tried `owned: true` and it didn't work. I tried `search('myProject')` for both Project and Group and nothing. Same thing, it hangs.

@jdalrymple Just tried these:

```js
const { data, pagination } = await services.Projects.all({
    perPage:1,
    maxPages:1,
    showExpanded: true,
    // owned: true,
    membership: true
});
```

---

```js
const { data, pagination } = await services.Projects.all({
    perPage:1,
    maxPages:1,
    showExpanded: true,
    owned: true,
    // membership: true
});
```

---


```js
const { data, pagination } = await services.Projects.all({
    perPage:1,
    maxPages:1,
    showExpanded: true,
    owned: true,
    membership: true
});
```


Same thing. Hangs for over 10 seconds.

**Comment by damusix** [comment]
Also, I tried hitting the API directly using Axios and it is response immediately, so It's definitely not latency on Gitlab's part. Anyway to debug the internal request / response?

**Comment by jdalrymple** [comment]
Well that's really odd. Currently there isnt a very convenient way to debug. When i do it myself I add console logs in the RequestHelper file and rebuilt, and then npm link my local files. Kinda a pain. 

Definitely should expose a way to view more information without having to run a local version.

Any chance you could create the same behaviour with a public repository? That way i could help debug on my end as well

**Comment by jetersen** [comment]
What version of nodejs are you using?

**Comment by damusix** [comment]
@jdalrymple @jetersen  https://github.com/damusix/gitbeaker-issues

I tried Node 10, 12 and 14. Same issue.

**Comment by jetersen** [comment]
Can you try using

```javascript
const { Gitlab } = require('@gitbeaker/browser');
```

or 

```javascript
import { Gitlab } from '@gitbeaker/browser';
```

**Comment by damusix** [comment]
@jetersen that's how I originally had it, same results.

**Comment by jdalrymple** [comment]
Bleh, im sorry this isnt cooperating :/ Would you be able to put together a test project to recreate the issue?

**Comment by damusix** [comment]
@jdalrymple that repo I mentioned in my previous comment is it. Create a gitlab token and run it. See if you re-create it. I am just trying to get started, I have no project yet.

**Comment by jdalrymple** [comment]
Oops! Missed that. Ill look into it!

**Comment by jdalrymple** [comment]
> @jdalrymple @jetersen https://github.com/damusix/gitbeaker-issues
> 
> I tried Node 10, 12 and 14. Same issue.

I tested this on node 14 and received the response immediately :/

**Comment by jetersen** [comment]
What OS, are you running behind a firewall, VPN, or proxy?

**Comment by damusix** [comment]
> What OS, are you running behind a firewall, VPN, or proxy?

Latest osx. No proxy, no vpn. 🤔

**Comment by jdalrymple** [comment]
Hmm, do you receive similar results if you perform the same request with got? Does it hang?

**Comment by abhiaiyer91** [comment]
I'm having the same issue. I have an app where my host is gitlab.com, I'd like to find all groups the authenticated user is part of. 

The code:

```
  const gitlab = new Gitlab({
    authToken: `XXXXXXX`,
  })

 await gitlab.Groups.all({ maxPages: 1 })
```

I would have expected this request to be scoped to my auth token but instead it fetches all. The host is intended to be the default.


If i do this with fetch all is well and returns expected results

```
    const res = await fetch(`https://gitlab.com/api/v4/groups?per_page=5000`, {
      method: `GET`,
      headers: {
        Authorization: `Bearer XXXXXX`,
      },
    })

    return res.json()
```

**Comment by jdalrymple** [comment]
@abhiaiyer91 Please check the [README.md](https://github.com/jdalrymple/gitbeaker#getting-started) for the proper configuration properties that can be passed. authToken isnt a supported property.
