### ISSUE TITLE
Creating Projects for groups seems not to be possible

### ISSUE THREAD

**Issue by sedrubal** [jdalrymple/gitbeaker#772]
**Description**
As far as I understand, it is only possible to [create a project for a user](https://docs.gitlab.com/ee/api/projects.html#create-project-for-user) but not not create [just a project (with a namespace)](https://docs.gitlab.com/ee/api/projects.html#create-project)

**Proposal**
This API should be implemented: https://docs.gitlab.com/ee/api/projects.html#create-project

**Comment by jetersen** [comment]
Sure it is: https://github.com/jdalrymple/gitbeaker/blob/0f0d2d7a150d2bacb070112f597455a9bf280e9a/packages/gitbeaker-core/src/services/Groups.ts#L46

**Comment by sedrubal** [comment]
You're right, it really works. But actually I searched for this route when there is no `userId` given:

https://github.com/jdalrymple/gitbeaker/blob/0f0d2d7a150d2bacb070112f597455a9bf280e9a/packages/gitbeaker-core/src/services/Projects.ts#L64

I must have missed it.

**Comment by jdalrymple** [comment]
> You're right, it really works. But actually I searched for this route when there is no `userId` given:
> 
> https://github.com/jdalrymple/gitbeaker/blob/0f0d2d7a150d2bacb070112f597455a9bf280e9a/packages/gitbeaker-core/src/services/Projects.ts#L64
> 
> I must have missed it.

Yea this should probably set a default object or it would error when no userId is given. Ill fix this up

**Comment by jdalrymple** [comment]
More of a problem with the typing info than anything. You must pass path or name to the create function. Since one of those two properties are required, userId can be null without any problems.

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`19.6.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/19.6.0) :rocket:
