### ISSUE TITLE
Add support for managing approval rules on projects

### ISSUE THREAD

**Issue by sampsasaarela** [jdalrymple/gitbeaker#799]
Am I correct, but there is no support to manage to merge request/project level [approval rules](https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule) in this package? At least I didn't find anything related to it. If not, it would be nice to feature add.

**Comment by jdalrymple** [comment]
Not yet! Ill add this to the list, thanks!

**Comment by nlochschmidt** [comment]
@sampsasaarela @jdalrymple is there anything in progress here? Otherwise I would be happy to provide a PR.

**Comment by jdalrymple** [comment]
Still on the back burner, feel free to send a PR!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`25.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/25.0.0) :rocket:
