### ISSUE TITLE
Use custom request options (such as search_namespaces) in Projects API

### ISSUE THREAD

**Issue by xatavian** [jdalrymple/gitbeaker#800]
**Description**
The GITLAB API includes a lot of query parameters for Projects such as search, search_namespaces, visibility, ... Currently the `Projects` service and its `Projects.search` method does not allow optional query parameters. 

In particular, `search_namespaces` is interesting because it would allow one to search for `namespace/project` instead of just `project` (eg. `jdalrymple/gitbeaker` instead of just `gitbeaker`). 

**Proposal**

Add `BaseRequestOptions` to `Projects.search`: 

```
class Projects extends BaseService {
  // ...
  search(projectName: string, options?: BaseRequestOptions);
}
```

**Comment by xatavian** [comment]
By the way, that could be nice if `projectName` was URI-encoded in search as well. Otherwise, we get weird request URLs :smile:

**Comment by jdalrymple** [comment]
This is an easy one to fix up. Thanks for pointing it out!

**Comment by xatavian** [comment]
Well, I can probably make the change if you'd like :smile:

**Comment by xatavian** [comment]
I have trouble setting up my project to use a local installation of gitbeaker though. I make `@gitbeaker/node` point to my local installation but then it requires a remote `@gitbeaker/core` which actually is the real package that needs change. Should I change the core's package.json as well ?

**Comment by jdalrymple** [comment]
Hehe yea it can be a little confusing. I should add this to the docs. You just have to update @gitbeaker/core, thats where all the logic is. The steps:

1. Update core
2. run yarn build / npm run build
3. go into the gitbeaker-node folder and run npm link
4. test
