### ISSUE TITLE
MergeRequests.all filter by merge request state and label

### ISSUE THREAD

**Issue by DavidFaizulaev** [jdalrymple/gitbeaker#816]
Hello,

I'm using the package for integrating with gitlab API and it seems that I cannot filter `MergeRequests.all` results.

In gitlab's API I can filter results by various values, such as state or labels.
https://docs.gitlab.com/ee/api/merge_requests.html

But it seems this option is not supported at the moment, or am I doing something wrong ?

**Steps to reproduce**
`
const mergeRequestParams = {
    labels: 'some_label',
    state: 'opened'
};
const getMergeRequestsOptions = { projectId: 11111, options: mergeRequestParams };
const response = await gitlabAPI.MergeRequests.all(getMergeRequestsOptions);`

**Proposal**
Allow to filter by various values (as in the API)

**Comment by jdalrymple** [comment]
Close! the options parameter isnt needed, you can just include the options directly in the root object:
```js
const getMergeRequestsOptions = { projectId: 11111, labels: 'some_label', state: 'opened' };
```
