### ISSUE TITLE
PaginationResponse not returning object as expected

### ISSUE THREAD

**Issue by sdc224** [jdalrymple/gitbeaker#839]
**Description**

I want to paginate the fetching process of all Projects through some button click. To do that, I need to know the total no of pages in the response. As per the docs, I have written

```ts
public getAllProjects = async (pagination?: PaginatedRequestOptions) => {
    const response = await this.gitlab!.Projects.all({
      showExpanded: true,
      ...pagination
    });
    return response;
};
```

Now, the res contains pagination, which is not the expected ```PaginationResponse``` as mentioned in the docs.

I have sent ```PaginatedRequestOptions``` as 

```js
{
    perPage: 10,
    page: 1
}
```

Besides this, I am also getting some type issues in the pagination as ```Projects.all()``` returns only ```ProjectSchema[]```, though is beyond the scope of the issue (I solved that by converting it to ```unknown``` first, then the respective response)

*Note* 
I have tried maxPages option with perPage as mentioned in one issue, still I am getting the same response.

**Steps to reproduce**

Send ```PaginatedRequestOptions``` as 

```js
{
    perPage: 10,
    page: 1
}
```

**Expected behaviour**

```PaginationResponse``` should return as mentioned in the docs

**Actual behaviour**
The output what I am getting as response is

```js
data: (10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
pagination:
current: 1
next: null
perPage: NaN
previous: null
total: NaN
totalPages: NaN
```

**Possible fixes**
 Don't have any idea how to fix the issue 😅😅

**Comment by jdalrymple** [comment]
Well that doesn't look good! Ill see if i can sort out why the pagination info is missing

**Comment by sdc224** [comment]
@jdalrymple any update over this?

**Comment by jdalrymple** [comment]
Not yet sorry! been a busy week

**Comment by jdalrymple** [comment]
So i just ran a local tests on the gitlab.com webpage. When using:

```javascript
const { Projects } = require("@gitbeaker/node");

const projects = await services.all({
	showExpanded: true,
        perPage:10,
        page:1
})
```
I received back:

```
  data(...),
  pagination: {
    total: NaN,
    next: 2,
    current: 1,
    previous: null,
    perPage: 10,
    totalPages: NaN
  }
}

```

I was curious though about the NaN, and then i found [this](https://docs.gitlab.com/ee/api/#other-pagination-headers) from the gitlab docs:
>For performance reasons since GitLab 11.8 and behind the api_kaminari_count_with_limit feature flag, if the number of resources is more than 10,000, the X-Total and X-Total-Pages headers as well as the rel="last" Link are not present in the response headers.

**Comment by sdc224** [comment]
Sorry for late reply, busy in the last week actually.

For my case no of all Projects I am fetching is nearabout 43. Still I am getting this. Is this related to what you commented?

Why it is NaN? I mean can we get the exact string/Response value, cause maybe it is not a number and we are still trying to parse it. Maybe in the totalPages we can get an error message if totalPages are not available in Response headers.

**Comment by sdc224** [comment]
Just a small doubt, can I know when my access token will expire through Gitlab APIs?

**Comment by jdalrymple** [comment]
> Just a small doubt, can I know when my access token will expire through Gitlab APIs?

You would receive an unauthorized error from Gitlab if it was expired.

**Comment by jdalrymple** [comment]
> Sorry for late reply, busy in the last week actually.
> 
> For my case no of all Projects I am fetching is nearabout 43. Still I am getting this. Is this related to what you commented?
> 
> Why it is NaN? I mean can we get the exact string/Response value, cause maybe it is not a number and we are still trying to parse it. Maybe in the totalPages we can get an error message if totalPages are not available in Response headers.

Hmm, maybe create a sample project. Maybe there is something else going on that im not catching :/

**Comment by sdc224** [comment]
Let me try to find the same in normal gitlab account, coz in Enterprise account I am getting this.

**Comment by sdc224** [comment]
> > Just a small doubt, can I know when my access token will expire through Gitlab APIs?
> 
> You would receive an unauthorized error from Gitlab if it was expired.

Yes I know that, but my question is, is there any API for knowing the expiration date for an access token? For e.g., On creation of Gitlab constructor or by using some other API, can I get that when my access token will expire?

```ts
const gitlab = new Gitlab({token});    // returns an object, mentioning the expiry date of access token
```

or maybe
```ts
const token = new AccessToken(token); // returns an object, mentioning the expiry date of access token
```

That way I can notify any user about the expiry of his/her gitlab access token 😎😎

**Comment by jdalrymple** [comment]
> > > Just a small doubt, can I know when my access token will expire through Gitlab APIs?
> > 
> > 
> > You would receive an unauthorized error from Gitlab if it was expired.
> 
> Yes I know that, but my question is, is there any API for knowing the expiration date for an access token? For e.g., On creation of Gitlab constructor or by using some other API, can I get that when my access token will expire?
> 
> ```ts
> const gitlab = new Gitlab({token});    // returns an object, mentioning the expiry date of access token
> ```
> 
> or maybe
> 
> ```ts
> const token = new AccessToken(token); // returns an object, mentioning the expiry date of access token
> ```
> 
> That way I can notify any user about the expiry of his/her gitlab access token sunglassessunglasses

not that im aware of

**Comment by sdc224** [comment]
I think I should raise an issue(feature-requested) in gitlab API.

**Comment by sdc224** [comment]
Maybe [this](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#programmatically-creating-a-personal-access-token) is what I want.

**Comment by jdalrymple** [comment]
> Maybe [this](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#programmatically-creating-a-personal-access-token) is what I want.

perhaps, though this is directly using the gitlab server's ruby commands.

**Comment by sdc224** [comment]
I think for the pagination, it is not related to this nodejs API, it is dependent to the Gitlab API services. Correct me if I am wrong, I will close this request then.

**Comment by sdc224** [comment]
> > Maybe [this](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#programmatically-creating-a-personal-access-token) is what I want.
> 
> perhaps, though this is directly using the gitlab server's ruby commands.

Anyway, can we call those ruby commands through nodejs by some kind of ```sudo```?

**Comment by jdalrymple** [comment]
> > > Maybe [this](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#programmatically-creating-a-personal-access-token) is what I want.
> > 
> > 
> > perhaps, though this is directly using the gitlab server's ruby commands.
> 
> Anyway, can we call those ruby commands through nodejs by some kind of `sudo`?

That wouldnt be the best idea. You would be better off running a separate command outside of this library. You can see an example of those ruby commands in the scripts folder in this repo

**Comment by jdalrymple** [comment]
> I think for the pagination, it is not related to this nodejs API, it is dependent to the Gitlab API services. Correct me if I am wrong, I will close this request then.

Its possible. Do you get similar results when you run a request on the official gitlab.com ?

**Comment by sdc224** [comment]
> > I think for the pagination, it is not related to this nodejs API, it is dependent to the Gitlab API services. Correct me if I am wrong, I will close this request then.
> 
> Its possible. Do you get similar results when you run a request on the official gitlab.com ?

Sorry @jdalrymple , I tried in official gitlab also, getting same result.
Will invesigate a bit more on that, and update you.

**Comment by jdalrymple** [comment]
Perhaps create a sample project?

**Comment by sdc224** [comment]
Yes and will share you here

**Comment by sdc224** [comment]
> > > > Maybe [this](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#programmatically-creating-a-personal-access-token) is what I want.
> > > 
> > > 
> > > perhaps, though this is directly using the gitlab server's ruby commands.
> > 
> > 
> > Anyway, can we call those ruby commands through nodejs by some kind of `sudo`?
> 
> That wouldnt be the best idea. You would be better off running a separate command outside of this library. You can see an example of those ruby commands in the scripts folder in this repo

Can you tell me how you are calling the ruby script?

**Comment by sdc224** [comment]
Closing this for now, will reopen once I get time to create a sample repository 😅😅.

@jdalrymple  please tell me how you are calling the `ruby` scripts

**Comment by jdalrymple** [comment]
> Closing this for now, will reopen once I get time to create a sample repository sweat_smilesweat_smile.
> 
> @jdalrymple please tell me how you are calling the `ruby` scripts

https://github.com/jdalrymple/gitbeaker/blob/master/.gitlab-ci.yml 

Look at the integration test script
