### ISSUE TITLE
Concurrency get would be better?

### ISSUE THREAD

**Issue by uinz** [jdalrymple/gitbeaker#873]
https://github.com/jdalrymple/gitbeaker/blob/7f0114d3e08a76cc8177d51d53e5276dfd0a7529/packages/gitbeaker-core/src/infrastructure/RequestHelper.ts#L77-L85

As get all list by default, `Concurrency Mode` maybe is a better way

**Comment by jdalrymple** [comment]
> https://github.com/jdalrymple/gitbeaker/blob/7f0114d3e08a76cc8177d51d53e5276dfd0a7529/packages/gitbeaker-core/src/infrastructure/RequestHelper.ts#L77-L85
> 
> As get all list by default, `Concurrency Mode` maybe is a better way

Could you explain this further?

**Comment by jdalrymple** [comment]
@uinz Im going to close due to lack of information. If you have more to add ill reopen!
