### ISSUE TITLE
Repositories API - Corrupt compressed tarball

### ISSUE THREAD

**Issue by menonsoftware** [jdalrymple/gitbeaker#881]
Hello,

First of all, thank you for writing gitbreaker :) . I am new to nodejs however have got to
the point where I can list project trees and blobs.

While using the following code to download repositories I seem to get corrupt tar.gz files

const repoApi = new Repositories({host:gitlab.com, token:xxxxxxxx});
await repoApi.showArchive(req.body.projectid, { "sha": "master" }).then((data) => {
            console.log(data);
            fs.writeFileSync('../public/archive.tar.gz', data);
        });

Am I missing something? Can you please advise?

**Comment by jdalrymple** [comment]
Hmm that should work. Its possible the encoding is getting broken at some point. Ill give it a look and follow up.

**Comment by ajaymenon78** [comment]
So what I wanted to achieve was to list all folders/files in a project and download them...what I did as a workaround was to use repoApi.tree to list all folders inside and create the necessary structure for folders. I then downloaded the blobs using repositoryFiles api :)...Mission accomplished!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`23.4.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/23.4.0) :rocket:
