### ISSUE TITLE
Broken compilation from bad import of FormData

### ISSUE THREAD

**Issue by tlebreton** [jdalrymple/gitbeaker#882]
**Description**

Hi

I think the problem that was resolved with https://github.com/jdalrymple/gitbeaker/issues/417 is back.
I think it's a regression from the monorepo commit the 1 Feb 2020

` node_modules/@gitbeaker/requester-utils/node_modules/form-data/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
    
    1 import FormData from 'form-data';
             ~~~~~~~~
    
      node_modules/@gitbeaker/requester-utils/node_modules/form-data/index.d.ts:10:1
        10 export = FormData;
           ~~~~~~~~~~~~~~~~~~
        This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

`

**Expected behaviour**
build succes

**Actual behaviour**
build error

**Possible fixes**
In the RequesterUtils.ts replace 
`import FormData from 'form-data';	`
By
`import * as FormData from 'form-data';`

**Comment by jdalrymple** [comment]
oops! I'll fix this up over the weekend

**Comment by jdalrymple** [comment]
This one isnt that straight forward. Replacing with: 

```
 import * as FormData from 'form-data';
```

Just returns another error:
```
src/RequesterUtils.ts:44:53 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

44   if (typeof body === 'object' && !(body instanceof FormData)) {
                                                       ~~~~~~~~
```

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`21.4.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/21.4.0) :rocket:

**Comment by tlebreton** [comment]
Hi 
Thanks for the quick resolve.
But there is the same problem for the same import in another file :  (Utilis.d.ts in infrastructure of @gitbeaker/core)

```
ERROR in node_modules/@gitbeaker/core/dist/types/infrastructure/Utils.d.ts:1:8 - error TS1259: Module '"/var/www/html/BackOffice/node_modules/@gitbeaker/core/node_modules/form-data/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import FormData from 'form-data';
         ~~~~~~~~

  node_modules/@gitbeaker/core/node_modules/form-data/index.d.ts:10:1
    10 export = FormData;
       ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

Do i need to open another issue or it's good ?

Thank for you reactivity.

**Comment by jdalrymple** [comment]
I know what I need to fix, ill look at it today!

**Comment by jdalrymple** [comment]
bleh same fix wont work. Ill need to figure it out another way. Sorry for the inconvenience. :s

**Comment by tlebreton** [comment]
No problem :) 
Take your time
Thanks for the communication

**Comment by jdalrymple** [comment]
Check out the canary build for #893
