### ISSUE TITLE
Add support to get related related MRs and MRs that close an issue 

### ISSUE THREAD

**Issue by fbridault** [jdalrymple/gitbeaker#897]
**Description**
The `Issues` service does not propose the following routes :
https://docs.gitlab.com/ce/api/issues.html#list-merge-requests-related-to-issue
https://docs.gitlab.com/ce/api/issues.html#list-merge-requests-that-will-close-issue-on-merge

**Proposal**
Add support for both, which should be quite straightforward. I can propose a contribution if you want.

**Comment by jdalrymple** [comment]
We always welcome PR's! :heart_eyes:

**Comment by fbridault** [comment]
Ok great 👍

**Comment by fbridault** [comment]
I proposed the PR, but I am quite confused with your change about the description. I really intended to get merge requests, not users... :wink:

**Comment by jdalrymple** [comment]
haha, i misread the title, i thought it said: "mr and mrs" which i figured was weird. Ill fix it up sorry!

**Comment by fbridault** [comment]
Ha ha ha sorry for that, I'm more used to the GitLab terminology than GitHub, so that acronym was obvious, but I can understand the confusion... :rofl:

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`22.0.1`](https://github.com/jdalrymple/gitbeaker/releases/tag/22.0.1) :rocket:
