### ISSUE TITLE
Get Users example is not working

### ISSUE THREAD

**Issue by JaredDahlke** [jdalrymple/gitbeaker#923]
Hey guys thank you for the library, but for some reason my code is not working, a point in the right direction would be much appreciated!

This is my app.js:

```
const { Gitlab } = require('@gitbeaker/node');



var express = require('express');
var port = process.env.PORT || 3003;
var app = express();





app.get('/users', async function (req, res) {
  
  const api = new Gitlab({
    token: 'myPersonalToken'.  // I got this from GitLab, allowed all permissions
  });

  console.log('inside get')   // <-- THIS IS GETTING LOGGED AS EXPECTED
  let users = await api.Users.all();
  console.log('passed await')         // <-- THIS IS NOT GETTING LOGGED, IE it is getting stuck on the API call
  res.send(users);
  

});
app.listen(port, function () {
 console.log('Example app listening on port !');
});
```

**Comment by jdalrymple** [comment]
Ill give it a look!

**Comment by JaredDahlke** [comment]
@jdalrymple just glancing at my code do you see anything I messed up / any reason it wouldn't work. Do you think using const { Gitlab } = require('@gitbeaker/node');  should be working fine?

**Comment by JaredDahlke** [comment]
i changed it from
`let users = await api.Users.all();`
to
`let users = await api.Users.all({ maxPages: 2 });`

and now I'm getting a response, but it's random Users that I have never heard of, it does not seem to be pulling my actual data but unrelated users

**Comment by JaredDahlke** [comment]
ok so after reading the gitlab api docs it says if the user is not properly authenticated then the API returns public data. I think that's what it is doing. Is there some code that I'm missing above that is causing me to not be properly authenticated?

**Comment by JaredDahlke** [comment]
here is my  GitHub Project 
https://github.com/JaredDahlke/gitlabTest

to run it locally so you can see what it's doing just clone it and do the following:
npm i

npm start

then navigate to:  http://localhost:3003/projects

**Comment by jdalrymple** [comment]
I think youre looking for [this](https://docs.gitlab.com/ee/api/projects.html#list-user-projects) functionality. To do that with this library, use :

```js
let user = await api.Users.current(); // Gives you your userId
let projects = await api.Users.projects(user.id); // Gets you the projects of a specific user
```
