### ISSUE TITLE
cdn for browser

### ISSUE THREAD

**Issue by carlogonzalo** [jdalrymple/gitbeaker#927]
Hello,

for using in browser is it availabe to download via a cdn? or how about adding to www.pika.dev which is an npm package cdn?

Thanks

**Comment by jdalrymple** [comment]
I think you can use the github cdn, but im not sure. Ill verify and checkback

**Comment by jdalrymple** [comment]
Yup, jsdeliver can link to github, npm, and unpkg can link from npm easily. Here is an example:

`https://unpkg.com/@gitbeaker/browser@23.0.0/dist/index.js`
