### ISSUE TITLE
MergeRequests.closesIssues calls wrong endpoint

### ISSUE THREAD

**Issue by abrenneke** [jdalrymple/gitbeaker#932]
https://github.com/jdalrymple/gitbeaker/blob/61798eb735f9ecaac3aa30b79d4da48b72965011/packages/gitbeaker-core/src/services/MergeRequests.ts#L217

Per the [GitlLab documentation](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-that-will-close-on-merge), should be 

```typescript
 `projects/${pId}/merge_requests/${mIid}/closes_issues`, 
```

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`23.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/23.2.0) :rocket:
