### ISSUE TITLE
[429 Too Many Requests] How to solve that?

### ISSUE THREAD

**Issue by alexisfrjp** [jdalrymple/gitbeaker#960]
Reference to #73, I still get lots of `429 Too Many Requests` using `api.ProjectImportExport.schedule(id)` and `api.ProjectImportExport.download(id)`.

The error is catch using `catch()` but there is no way to see the `Retry-After`.

From #73, it seems that should be handled inside Gitbeaker. Am I wrong?

Thanks.

**Comment by jdalrymple** [comment]
I think that section of the code might of been during one of the rewrites. Ill double check and re-add it

**Comment by alexisfrjp** [comment]
Indeed, after a quick look at the code, it disappeared.
Sorry, I don't have enough knowledge of the code to add it by myself.
Thanks!

**Comment by jdalrymple** [comment]
Yea i think it was removed because got handles it internally with their retry api. but its possible it doesnt capture the retry after header.

**Comment by jdalrymple** [comment]
Yea apparently, got handles this internally. Im guessing you're using the node version of the library?

**Comment by alexisfrjp** [comment]
Excatly, `@gitbeaker/node@23.4.0`.

**Comment by jdalrymple** [comment]
Yea it [definitely](https://github.com/sindresorhus/got/blob/3745efc9d9d03c78c898f357a34524524cce514d/source/as-promise/calculate-retry-delay.ts#L32) does this. I wonder what is happening that causes this to skip out...

**Comment by jdalrymple** [comment]
Might be [related](https://gitlab.com/gitlab-org/gitlab/-/issues/199738)

**Comment by alexisfrjp** [comment]
Oh ok...
I just updated from 17.* to 23.*. I don't know if that was already there for v17 but let me check with a clean npm installation tomorrow (it's night here).
I'll also try to check if the `Retry-After` is present.

I'll keep you updated. Thanks @jdalrymple !

**Comment by alexisfrjp** [comment]
Sorry for the delay, `"@gitbeaker/node": "^23.4.0"` I still get **Response code 429 (Too Many Requests)**.

As expected, there is no `Retry-After` but there is a `ratelimit-reset` header.

```
{
  "date": "Tue, 14 Jul 2020 12:59:04 GMT",
  "content-type": "application/json",
  "content-length": "89",
  "connection": "close",
  "set-cookie": [
    "__cfduid=***; expires=Thu, 13-Aug-20 12:59:04 GMT; path=/; domain=.gitlab.com; HttpOnly; SameSite=Lax; Secure"
  ],
  "cache-control": "no-cache",
  "vary": "Origin",
  "x-content-type-options": "nosniff",
  "x-frame-options": "SAMEORIGIN",
  "x-request-id": "***",
  "x-runtime": "0.039779",
  "ratelimit-limit": "600",
  "ratelimit-observed": "64",
  "ratelimit-remaining": "536",
  "ratelimit-reset": "1594731604",
  "ratelimit-resettime": "Tue, 14 Jul 2020 13:00:04 GMT",
  "gitlab-lb": "fe-03-lb-gprd",
  "gitlab-sv": "localhost",
  "cf-cache-status": "DYNAMIC",
  "cf-request-id": "***",
  "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
  "server": "cloudflare",
  "cf-ray": "***-NRT"
}
```

**Comment by jdalrymple** [comment]
Well thats frustrating. Ill give it a week or so to see what the Gitlab folks want to do about it. If they dont intend on bringing back Retry-After, we can begin adding the custom functionality to support it

**Comment by max-wittig** [comment]
I've created an upstream issue: https://gitlab.com/gitlab-org/gitlab/-/issues/230914

**Comment by max-wittig** [comment]
python-gitlab does a constant retry for up to ten times, if the header is missing. If GitLab doesn't deliver, this might be the best thing to do here as well: https://github.com/python-gitlab/python-gitlab/blob/1606310a880f8a8a2a370db27511b57732caf178/gitlab/__init__.py#L549

**Comment by jdalrymple** [comment]
Yea leaning towards that now @max-wittig

**Comment by alexisfrjp** [comment]
Yes that makes sense if the default timeout isn't too small since the rate limit is around 10min. I don't know if that makes sense to have a background process waiting for minutes tho.

**Comment by jdalrymple** [comment]
Are these headers always returned on the 429 error?

```
{
  "ratelimit-limit": "600",
  "ratelimit-observed": "64",
  "ratelimit-remaining": "536",
  "ratelimit-reset": "1594731604",
  "ratelimit-resettime": "Tue, 14 Jul 2020 13:00:04 GMT"
}
```

**Comment by max-wittig** [comment]
@jdalrymple Just on gitlab.com. Not on self-managed.

**Comment by jdalrymple** [comment]
Well thats frustrating

**Comment by jdalrymple** [comment]
Going to wait for Gitlab's response to the issue posted above before making any changes

**Comment by max-wittig** [comment]
I guess GitLab doesn't really care. They added the `minor inconvenience` label

**Comment by max-wittig** [comment]
What's the reason for having multiple requesters in the first place?

https://github.com/sindresorhus/ky-universal would support node and the browser.

**Comment by jdalrymple** [comment]
> What's the reason for having multiple requesters in the first place?
> 
> https://github.com/sindresorhus/ky-universal would support node and the browser.

I attempted to get it all setup with ky-universal original but kept running into problems specifically for streaming support, which ky really doesnt handle (at the time) though they might have added a [polyfill](https://github.com/sindresorhus/ky-universal/pull/12/files) for support since..

**Comment by max-wittig** [comment]
Btw. does ky even work in the browser currently? I'm trying it out, but I'm only getting the first page back?

**Comment by jdalrymple** [comment]
Haha it should since it was created specifically for the browser

**Comment by jdalrymple** [comment]
Looks like they are finally looking into fixing this :crossed_fingers:
