### ISSUE TITLE
Repositories.tree() not return pagination response as expected 

### ISSUE THREAD

**Issue by kunyan** [jdalrymple/gitbeaker#983]
**Description**
```js

const response = await gitlab.Repositories.tree(projectId, {
      ref,
      path,
      perPage,
      page
    });
```

The response always `object[]` not the `PaginationResponse` which I expected

I also checked the source
https://github.com/jdalrymple/gitbeaker/blob/a6fd10fab785d9b5113b17503ed03147c82b9795/packages/gitbeaker-core/src/services/Repositories.ts#L49-L53

The option is using `BaseRequestOptions ` not `PaginatedRequestOptions`.
I don't know if that is the reason cause .

**Steps to reproduce**

I already show the code

**Expected behaviour**

When I add `page` and `perPage`, the response format should be `PaginationResponse`
**Actual behaviour**

`object[]`
**Possible fixes**

**Comment by jdalrymple** [comment]
You mean youre looking for the pagination information?

**Comment by kunyan** [comment]
@jdalrymple Yeah, I tried to send page and perPage as option with `tree()`. but can not get the totalPage from response

**Comment by jdalrymple** [comment]
pass { showExpanded: true } as another option.

**Comment by kunyan** [comment]
@jdalrymple it's works now
